import {NextResponse} from 'next/server';
import {serverDb} from '@/lib/server/firebase-admin';
import {requireStaff} from '@/lib/server/staff-permission';
import {PICKUPS,changePickup,pickupPrefill,createPickupInvoice,requireValue} from '@/lib/service-pickups.mjs';
import {calculateInvoice,validateInvoiceData} from '@/lib/calculations';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store'};
const fail=(e:any)=>NextResponse.json({error:e.message||'Pickup operation failed.'},{status:e.message==='FORBIDDEN'?403:e.message==='SIGN_IN_REQUIRED'?401:400,headers});
export async function GET(req:Request){try{await requireStaff(req,'appointments','read');const db=serverDb(),id=new URL(req.url).searchParams.get('id');if(id){requireValue(/^[\w-]{10,100}$/.test(id),'Invalid pickup reference.');const p=await db.doc(PICKUPS+'/'+id).get();requireValue(p.exists,'Pickup not found.');const booking={...p.data(),id:p.id};return NextResponse.json({booking,prefill:pickupPrefill(booking)},{headers});}const [active,recent]=await Promise.all([db.collection(PICKUPS).where('status','in',['scheduled','picked_up']).limit(501).get(),db.collection(PICKUPS).orderBy('date','desc').limit(100).get()]);const records=[...new Map([...recent.docs,...active.docs].map(d=>[d.id,d])).values()];return NextResponse.json({bookings:records.map(d=>({...d.data(),id:d.id})),more:active.size>500},{headers});}catch(e){return fail(e);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw Error('Use the admin website.');await requireStaff(req,'appointments','write');const raw=await req.text();requireValue(raw.length<=2000000,'Request too large.');const b=JSON.parse(raw),u=await requireStaff(req,b.action==='invoice'?'invoices':'appointments','write');if(b.action==='invoice'){requireValue(b.collection==='invoices','Pickup invoices use the main showroom invoice collection.');const d=b.data;requireValue(d&&d.sourcePickupId===b.pickupId&&d.soldTo&&Array.isArray(d.items)&&d.items.length<=100,'Invalid invoice data.');requireValue(['WASH','INVOICE'].includes(d.documentType)&&['wash','retail','wholesale','retail-per-rug','wholesale-per-rug','retail-per-sqft','wholesale-per-sqft'].includes(d.mode),'Choose a service or sale invoice.');requireValue(/^MP\d{8}$/.test(d.invoiceNumber||''),'Use the reserved Marco Polo invoice number.');const errors=validateInvoiceData(d);requireValue(errors.length===0,errors.join(' '));const total=calculateInvoice(d).totalDue;requireValue(Number.isFinite(total)&&total>=0,'Invoice amount is invalid.');return NextResponse.json(await createPickupInvoice(serverDb(),{pickupId:b.pickupId,data:d,total,actor:u.uid}),{headers});}return NextResponse.json(await changePickup(serverDb(),b,u.uid),{headers});}catch(e){return fail(e);}}
