import {NextResponse} from 'next/server';
import {caller,serverAuth,serverDb} from '@/lib/server/firebase-admin';
import {check} from '@/lib/auction/engine.mjs';
import {accountFields,buyerProjection,buyerInvoice} from '@/lib/auction/account.mjs';
import {DEFAULT_SETTINGS,AUCTION_SETTINGS,publicSettings,termsText,storageSummary} from '@/lib/auction/settlement.mjs';
export const dynamic='force-dynamic';export const runtime='nodejs';
async function identity(req:Request){const u=await caller(req);check(u.email&&u.firebase?.sign_in_provider!=='anonymous','SIGN_IN_REQUIRED');return serverAuth().getUser(u.uid);}
function fail(e:any){return NextResponse.json({error:e?.message==='SIGN_IN_REQUIRED'?'Please sign in.':'Account could not load or save. Please retry.'},{status:e?.message==='SIGN_IN_REQUIRED'?401:503});}
export async function GET(req:Request){try{const u=await identity(req),db=serverDb();const [p,invoices,policy,watch]=await Promise.all([db.doc('auction_profiles/'+u.uid).get(),db.collection('auction_buyer_invoices_v2').where('buyerId','==',u.uid).limit(101).get(),db.doc(AUCTION_SETTINGS+'/current').get(),db.collection('auction_watchlists').doc(u.uid).collection('lots').limit(101).get()]);const settings=policy.data()||DEFAULT_SETTINGS;return NextResponse.json({profile:buyerProjection(p.data()),email:u.email,emailVerified:u.emailVerified,invoices:invoices.docs.slice(0,100).map(d=>{const i={...d.data(),id:d.id};return {...buyerInvoice(i),storage:storageSummary(i)};}),moreInvoices:invoices.size>100,watchCount:watch.size,settings:publicSettings(settings),terms:termsText(settings),publicEnabled:false,paymentMethods:[],cardSetupEnabled:false},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return fail(e);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return NextResponse.json({error:'Use the auction website.'},{status:403});const u=await identity(req);check(u.emailVerified,'Verify your email before saving bidder settings.');const raw=await req.text();check(raw.length<=12000,'Account form is too large.');let fields:any;try{fields=accountFields(JSON.parse(raw));}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Check your details.'},{status:400});}const db=serverDb(),ref=db.doc('auction_profiles/'+u.uid),counter=db.doc('auction_private_counters/bidders');await db.runTransaction(async tx=>{const [profile,count]=await tx.getAll(ref,counter);let number=profile.data()?.bidderNumber;if(!number){const next=Number(count.data()?.value||0)+1;check(Number.isSafeInteger(next),'Bidder counter requires review.');number='MPB-'+String(next).padStart(6,'0');tx.set(counter,{value:next});}tx.set(ref,{...fields,email:u.email,bidderNumber:number,updatedAt:Date.now()},{merge:true});});return NextResponse.json({saved:true});}catch(e){return fail(e);}}
