import {isRugOnReviewHold} from '../catalog-visibility.mjs';
import {checkoutOriginKnown} from '../server/checkout-region.mjs';
import {createHash} from 'node:crypto';
import {check,placeMaximum,settle,cents} from './engine.mjs';
import {buildInvoices,choiceId,publicSettings,liveTerms} from './settlement.mjs';
export const LIVE_EVENTS='auction_live_events',LIVE_LOTS='auction_lots',LIVE_CHOICES='auction_live_choices',LIVE_INVOICES='auction_buyer_invoices_v2';
const hash=s=>createHash('sha256').update(s).digest('hex');
export async function scheduleLiveAuction(db,input,actor,now=Date.now()){
 check(/^[\w-]{10,100}$/.test(input.id),'Invalid auction reference.');check(Array.isArray(input.lotIds)&&input.lotIds.length>0&&input.lotIds.length<=100&&new Set(input.lotIds).size===input.lotIds.length,'Choose 1–100 distinct lots.');
 const event=db.doc(LIVE_EVENTS+'/'+input.id),refs=input.lotIds.map(id=>{check(/^[\w-]{1,100}$/.test(id),'Invalid lot.');return db.doc(LIVE_LOTS+'/'+id);});
 return db.runTransaction(async tx=>{const [prior,...snapshots]=await tx.getAll(event,...refs);check(!prior.exists,'Auction already scheduled.');const active=await tx.get(db.collection(LIVE_LOTS).where('status','==','scheduled').limit(101));check(active.size+input.lotIds.length<=100,'At most 100 lots can be scheduled simultaneously.');
 const lots=snapshots.map(d=>{const l=d.data();check(d.exists&&['draft','preview'].includes(l.status),'Only saved draft or preview lots can be scheduled.');check(Number.isSafeInteger(l.startAt)&&Number.isSafeInteger(l.endAt)&&l.startAt>=now+60000&&l.endAt>l.startAt,'Set opening at least one minute ahead and a later closing for every lot.');check(l.condition?.length>=10&&l.snapshot?.images?.length&&l.snapshot?.dimensions&&l.startingCents>=100,'Complete photos, condition and opening price first.');return {...l,id:d.id};});
 check(lots.every(l=>l.eventTitle===lots[0].eventTitle),'Choose lots from one auction event.');const rugIds=lots.map(l=>l.snapshot.rugId);check(new Set(rugIds).size===rugIds.length,'A rug cannot appear twice.');const rugRefs=rugIds.map(id=>db.doc('showroom_rugs/'+id)),rugs=await tx.getAll(...rugRefs);
 rugs.forEach(r=>{check(r.exists&&r.data().availability==='In Stock'&&!r.data().liveOrderId&&!r.data().auctionLotId,'A rug is no longer available.');check(!isRugOnReviewHold({...r.data(),id:r.id})&&checkoutOriginKnown(r.data()),'A rug requires listing review.');});
 const endAt=Math.max(...lots.map(l=>l.endAt));tx.create(event,{id:input.id,title:lots[0].eventTitle,status:'scheduled',lotIds:input.lotIds,endAt,createdAt:now,createdBy:actor,mode:'live',version:1});
 lots.forEach((l,i)=>{tx.update(refs[i],{auctionId:input.id,mode:'live',status:'scheduled',leaderId:'',currentCents:l.startingCents,bidCount:0,version:l.version+1});tx.update(rugRefs[i],{availability:'Reserved',auctionLotId:l.id,auctionId:input.id});});return {id:input.id};
 });
}
export async function acceptLiveBid(db,lotId,buyer,input,settings,now=Date.now()){
 check(/^[\w-]{1,100}$/.test(lotId)&&/^[\w-]{10,100}$/.test(input.requestId),'Invalid bid reference.');const ref=db.doc(LIVE_LOTS+'/'+lotId),event=ref.collection('events').doc(input.requestId),profile=db.doc('auction_profiles/'+buyer.uid),card=db.doc('auction_live_cards/'+buyer.uid),rate=db.doc('auction_bid_limits/'+buyer.uid);
 const fingerprint=hash(JSON.stringify({buyer:buyer.uid,lotId,input}));
 return db.runTransaction(async tx=>{const [lotSnap,prior,p,c,limits,launch,visibility,worker]=await tx.getAll(ref,event,profile,card,rate,db.doc('auction_launch/current'),db.doc('auction_visibility/current'),db.doc('auction_worker_status/current'));if(prior.exists){check(prior.data().fingerprint===fingerprint,'Bid operation conflict.');return prior.data().result;}check(worker.data()?.lastSuccessAt>=now-180000&&worker.data()?.degraded!==true,'Bidding is paused while the scheduled worker is reviewed.');check(!launch.data()?.pilotOnly||launch.data()?.pilotBuyerIds?.includes(buyer.uid),'This auction is in a private launch rehearsal.');check(launch.data()?.biddingEnabled===true&&visibility.data()?.mode==='open','Bidding is paused.');const lot=lotSnap.data(),contact=p.data(),payment=c.data();
 check(lotSnap.exists&&lot.mode==='live'&&lot.status==='scheduled','This lot is not open.');check(buyer.emailVerified&&buyer.phoneNumber&&buyer.phoneNumber===contact?.phone,'Verify your email and profile phone number before bidding.');check(contact?.accountStatus!=='suspended'&&['firstName','lastName','phone','address1','city','region','postalCode','country'].every(k=>contact?.[k]),'Complete your bidder profile.');check(payment?.verified===true&&payment.mode==='live'&&payment.consent===true,'Save and verify your payment card first.');check(!buyer.staff,'Staff may not bid.');check(!limits.data()?.lastAt||now-limits.data().lastAt>=1000,'Please wait a second before another bid.');
 const choiceRef=db.doc(LIVE_CHOICES+'/'+choiceId(lot.auctionId,buyer.uid)),rugRef=db.doc('showroom_rugs/'+lot.snapshot.rugId);const [choice,rug,bidders]=await Promise.all([tx.get(choiceRef),tx.get(rugRef),tx.get(ref.collection('bidders'))]);
 check(!isRugOnReviewHold({...rug.data(),id:rug.id})&&rug.data()?.auctionLotId===lotId&&rug.data()?.availability==='Reserved','This rug requires showroom review.');check(bidders.size<1000||bidders.docs.some(d=>d.id===buyer.uid),'This auction has reached bidder capacity.');let selected=choice.data();
 if(!selected){check(input.accepted===true&&input.policyVersion===settings.policyVersion,'Read and accept the current terms.');check(['pickup_self','pickup_assisted','shipping'].includes(input.delivery?.method),'Choose pickup or shipping.');let delivery={method:input.delivery.method,address:''},shippingFees={};if(delivery.method==='shipping'){check(lot.shippingOffered===true,'This lot is available for pickup only.');check(/^[\w-]{10,100}$/.test(input.shippingQuoteId||''),'Request a shipping quote from the showroom first.');const q=(await tx.get(db.doc('auction_live_shipping_quotes/'+input.shippingQuoteId))).data();check(q&&q.buyerId===buyer.uid&&q.auctionId===lot.auctionId&&q.expiresAt>lot.endAt,'Your shipping quote is missing or expired.');delivery={method:'shipping',address:q.address};shippingFees=q.lotFees;}selected={buyerId:buyer.uid,auctionId:lot.auctionId,delivery,shippingFees,policy:publicSettings(settings),acceptedAt:now,cardConsent:true,termsSnapshot:liveTerms(settings)};}
 if(selected.delivery.method==='shipping')check(selected.shippingFees?.[lotId]!==undefined,'Your accepted shipping quote does not cover this rug. Contact the showroom before bidding.');const shippingCents=selected.delivery.method==='shipping'?cents(selected.shippingFees?.[lotId]):0;
 const next=placeMaximum({...lot,mode:'sandbox'},bidders.docs.map(d=>d.data()),buyer.uid,input.maximumCents,selected.delivery,now),result={accepted:true,currentCents:next.lot.currentCents,endAt:next.lot.endAt,leading:next.lot.leaderId===buyer.uid};
 if(!choice.exists)tx.create(choiceRef,selected);tx.set(ref,{...next.lot,mode:'live',updatedAt:now});tx.set(ref.collection('bidders').doc(buyer.uid),{...next.bidders.find(b=>b.bidderId===buyer.uid),shippingCents});tx.create(event,{action:'bid',actor:buyer.uid,at:now,fingerprint,result});tx.set(rate,{lastAt:now});
 if(lot.leaderId&&lot.leaderId!==next.lot.leaderId)tx.create(db.doc('auction_notification_outbox/'+hash(lotId+'|'+input.requestId+'|outbid')),{kind:'outbid',buyerId:lot.leaderId,lotId,status:'pending',createdAt:now});return result;
 });
}
export async function closeLiveLot(db,id,now=Date.now()){
 const ref=db.doc(LIVE_LOTS+'/'+id);return db.runTransaction(async tx=>{const doc=await tx.get(ref),lot=doc.data();if(!doc.exists||lot.mode!=='live'||lot.status!=='scheduled'||now<lot.endAt)return {skipped:true};
 const rugRef=db.doc('showroom_rugs/'+lot.snapshot.rugId),rug=await tx.get(rugRef);check(rug.data()?.auctionLotId===id&&rug.data()?.availability==='Reserved','Inventory reservation requires review.');const closed=settle({...lot,mode:'sandbox'},now);let choice,winningShippingCents=0;
 if(closed.status==='sold'){choice=(await tx.get(db.doc(LIVE_CHOICES+'/'+choiceId(lot.auctionId,lot.leaderId)))).data();check(choice,'Winning buyer choice is missing.');winningShippingCents=cents((await tx.get(ref.collection('bidders').doc(lot.leaderId))).data()?.shippingCents||0);}
 tx.update(ref,{...closed,mode:'live',...(choice?{winningDelivery:choice.delivery,winningPolicy:choice.policy,winningShippingCents}:{}),closedAt:now});if(closed.status==='unsold')tx.update(rugRef,{availability:'In Stock',auctionLotId:null,auctionId:null});return {status:closed.status};
 });
}
export async function consolidateLiveAuction(db,id,settings,now=Date.now()){
 const eventRef=db.doc(LIVE_EVENTS+'/'+id);return db.runTransaction(async tx=>{const e=await tx.get(eventRef),event=e.data();check(e.exists&&event.mode==='live','Unknown auction.');if(event.status==='consolidated')return {invoiceIds:event.invoiceIds};const refs=event.lotIds.map(l=>db.doc(LIVE_LOTS+'/'+l)),docs=await tx.getAll(...refs),lots=docs.map(d=>({...d.data(),id:d.id,mode:'sandbox'}));const built=buildInvoices(id,lots,settings,now);
 const invoiceRefs=built.map(i=>db.doc(LIVE_INVOICES+'/'+i.id.replace('TEST-AI-','MPA-'))),old=await tx.getAll(...invoiceRefs);check(old.every(d=>!d.exists),'Invoices already exist; reconcile before retrying.');
 const contacts=await tx.getAll(...built.map(i=>db.doc('auction_profiles/'+i.buyerId)));built.forEach((i,n)=>{if(i.delivery.method==='shipping'){i.shipping=lots.filter(l=>l.leaderId===i.buyerId&&l.status==='sold').reduce((n,l)=>n+cents(l.winningShippingCents||0),0);i.tax=Math.round((i.subtotal+i.premium+i.loading+i.shipping)*i.policy.taxBps/10000);i.total=cents(i.subtotal+i.premium+i.loading+i.shipping+i.tax);}const number='MPA-'+hash(id+'|'+i.buyerId).slice(0,8).toUpperCase(),invoiceId=invoiceRefs[n].id;tx.create(invoiceRefs[n],{...i,id:invoiceId,number,buyerName:[contacts[n].data()?.firstName,contacts[n].data()?.lastName].filter(Boolean).join(' '),buyerEmail:contacts[n].data()?.email||'',mode:'live'});tx.create(db.doc('auction_notification_outbox/'+invoiceId+'-won'),{kind:'won',buyerId:i.buyerId,invoiceId,status:'pending',createdAt:now});i.items.forEach(item=>tx.update(db.doc(LIVE_LOTS+'/'+item.lotId),{consolidatedInvoiceId:invoiceId}));});const invoiceIds=invoiceRefs.map(r=>r.id);tx.update(eventRef,{status:'consolidated',invoiceIds,consolidatedAt:now,version:event.version+1});return {invoiceIds};});
}
export async function cancelLiveLot(db,id,actor,reason,now=Date.now()){
 check(/^[\w-]{1,100}$/.test(id)&&typeof reason==='string'&&reason.trim().length>=10&&reason.length<=500,'Choose a lot and explain the withdrawal.');const ref=db.doc(LIVE_LOTS+'/'+id);return db.runTransaction(async tx=>{const d=await tx.get(ref),l=d.data();check(l?.mode==='live'&&l.status==='scheduled'&&l.bidCount===0,'Only an unbid scheduled lot can be withdrawn.');const r=db.doc('showroom_rugs/'+l.snapshot.rugId),rug=await tx.get(r);check(rug.data()?.auctionLotId===id&&rug.data()?.availability==='Reserved','Reservation needs review.');tx.update(ref,{status:'cancelled',cancelReason:reason,version:l.version+1,cancelledAt:now,cancelledBy:actor});tx.update(r,{availability:'In Stock',auctionLotId:null,auctionId:null});return {saved:true};});
}
