import {createHash} from 'node:crypto';
import {check,cents} from './engine.mjs';
export const AUCTION_SETTINGS='auction_settings_v2';
export const SANDBOX_INVOICES='auction_sandbox_invoices_v2';
export const SANDBOX_SALES='auction_sandbox_sales_v2';
export const SANDBOX_CHOICES='auction_sandbox_choices_v2';
export const DEFAULT_SETTINGS={version:1,policyVersion:'auction-preparation-2026-10-03-v1',graceBusinessDays:10,storageDailyCents:4000,taxBps:600,buyerPremiumBps:0,closedDates:[],publicEnabled:false};
export function publicSettings(input){return Object.fromEntries(Object.keys(DEFAULT_SETTINGS).map(k=>[k,input[k]??DEFAULT_SETTINGS[k]]));}
export function validateSettings(input,version){
 const out={...DEFAULT_SETTINGS,version:version+1,policyVersion:'auction-preparation-2026-10-03-v'+(version+1)};
 for(const [key,min,max]of [['graceBusinessDays',1,60],['storageDailyCents',0,100000],['taxBps',0,1500],['buyerPremiumBps',0,2500]]){const value=Number(input[key]);check(Number.isSafeInteger(value)&&value>=min&&value<=max,'Invalid '+key+'.');out[key]=value;}
 check(Array.isArray(input.closedDates)&&input.closedDates.length<=100,'Use at most 100 closure dates.');out.closedDates=[...new Set(input.closedDates.map(v=>{check(validDate(v),'Use closure dates YYYY-MM-DD.');return v;}))].sort();return out;
}
export function validDate(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;}
export const nyDate=at=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(at);const part=key=>parts.find(p=>p.type===key).value;return part('year')+'-'+part('month')+'-'+part('day');};
const nextDate=d=>new Date(Date.parse(d+'T12:00:00Z')+86400000).toISOString().slice(0,10);
const weekDay=d=>new Date(d+'T12:00:00Z').getUTCDay();
const observed=d=>weekDay(d)===0?nextDate(d):weekDay(d)===6?new Date(Date.parse(d+'T12:00:00Z')-86400000).toISOString().slice(0,10):d;
function nth(year,month,weekday,n){let d=`${year}-${String(month).padStart(2,'0')}-01`;while(weekDay(d)!==weekday)d=nextDate(d);for(let i=1;i<n;i++)for(let j=0;j<7;j++)d=nextDate(d);return d;}
function last(year,month,weekday){let d=new Date(Date.UTC(year,month,0,12)).toISOString().slice(0,10);while(weekDay(d)!==weekday)d=new Date(Date.parse(d+'T12:00:00Z')-86400000).toISOString().slice(0,10);return d;}
export function holidays(year){return new Set([observed(`${year}-01-01`),nth(year,1,1,3),nth(year,2,1,3),last(year,5,1),observed(`${year}-06-19`),observed(`${year}-07-04`),nth(year,9,1,1),nth(year,10,1,2),observed(`${year}-11-11`),nth(year,11,4,4),observed(`${year}-12-25`),observed(`${year+1}-01-01`)]);}
export function pickupDeadline(readyDate,settings){check(validDate(readyDate),'Invalid ready date.');let date=readyDate,count=0;while(count<settings.graceBusinessDays){date=nextDate(date);const day=weekDay(date);if(day!==0&&day!==6&&!holidays(Number(date.slice(0,4))).has(date)&&!settings.closedDates.includes(date))count++;}return date;}
export function storageSummary(invoice,at=Date.now()){
 if(invoice.paymentStatus!=='paid'||!invoice.readyDate||invoice.delivery.method==='shipping')return {dueDate:null,days:0,cents:0,rows:[]};
 const settings=invoice.policy,dueDate=pickupDeadline(invoice.readyDate,settings),today=nyDate(at);
 const rows=invoice.items.map(item=>{const until=item.collectedDate&&item.collectedDate<today?item.collectedDate:today;const days=Math.max(0,Math.round((Date.parse(until+'T12:00:00Z')-Date.parse(dueDate+'T12:00:00Z'))/86400000));return {lotId:item.lotId,sku:item.sku,days,cents:days*settings.storageDailyCents};});
 const amount=rows.reduce((n,r)=>n+r.cents,0),waived=invoice.storageWaiverCents||0;return {dueDate,days:Math.max(0,...rows.map(r=>r.days)),cents:Math.max(0,amount-waived),grossCents:amount,waivedCents:waived,rows};
}
export function invoiceId(auctionId,buyerId){return 'TEST-AI-'+createHash('sha256').update(auctionId+'\0'+buyerId).digest('hex').slice(0,24);}
export function choiceId(auctionId,buyerId){return createHash('sha256').update(auctionId+'\0'+buyerId).digest('hex');}
export function buildInvoices(auctionId,lots,settings,now){
 check(lots.length>0&&lots.length<=100,'An auction supports 1–100 test lots.');check(lots.every(l=>l.mode==='sandbox'&&['sold','unsold','cancelled'].includes(l.status)),'Close every lot before creating the consolidated invoices.');
 const seen=new Set(),groups=new Map();for(const lot of lots){if(lot.status!=='sold')continue;check(lot.leaderId&&lot.winningDelivery,'Winning bidder or delivery choice is missing.');check(!seen.has(lot.snapshot?.rugId),'Duplicate rug in this auction. Review the test copies.');seen.add(lot.snapshot?.rugId);check(lot.paymentStatus!=='paid'&&lot.fulfillmentStatus!=='complete','A lot was already paid or fulfilled separately. Do not consolidate it again.');const list=groups.get(lot.leaderId)||[];list.push(lot);groups.set(lot.leaderId,list);}
 return [...groups].map(([buyerId,wins])=>{
 const policy=publicSettings(wins[0].winningPolicy||settings);check(wins.every(l=>JSON.stringify(publicSettings(l.winningPolicy||settings))===JSON.stringify(policy)),'Accepted fee policies differ. Review before consolidation.');const delivery=wins[0].winningDelivery;check(wins.every(l=>JSON.stringify(l.winningDelivery)===JSON.stringify(delivery)),'Pickup / delivery choices differ. Resolve the test auction before consolidating.');
 const items=wins.map(l=>({lotId:l.id,rugId:l.snapshot.rugId,sku:l.snapshot.sku||'',title:l.title,amount:cents(l.currentCents),loadingCents:delivery.method==='pickup_assisted'?cents(l.loadingCents||0):0,collectedDate:null}));
 const subtotal=items.reduce((n,l)=>n+l.amount,0),premium=Math.round(subtotal*policy.buyerPremiumBps/10000),loading=items.reduce((n,l)=>n+l.loadingCents,0),shipping=delivery.method==='shipping'?cents(delivery.shippingCents||0):0,tax=Math.round((subtotal+premium+loading+shipping)*policy.taxBps/10000),total=cents(subtotal+premium+loading+shipping+tax);
 return {id:invoiceId(auctionId,buyerId),number:'TEST-'+createHash('sha256').update(auctionId+'\0'+buyerId).digest('hex').slice(0,8).toUpperCase(),auctionId,buyerId,buyerName:'Fictional '+buyerId,mode:'sandbox',items,delivery,subtotal,premium,loading,shipping,tax,total,paymentStatus:'unpaid',paymentFailure:'',createdAt:now,version:1,policy:{...policy},readyDate:null,storageWaiverCents:0};
 });
}
export function termsText(settings){return `Auction terms — preparation version ${settings.policyVersion}. Public auctions remain under construction. Before your first bid in each auction, choose pickup or delivery and accept these terms and authorization to charge your saved card automatically for all winning lots on one invoice after the auction closes. Winning bids are binding. Buyer's premium: ${(settings.buyerPremiumBps/100).toFixed(2)}%. Sales tax: ${(settings.taxBps/100).toFixed(2)}%. Delivery and assisted-loading charges must be disclosed and accepted before bidding. A declined card does not cancel your winning obligation; your account will show an unpaid invoice and staff will see the buyer and balance. Payment must be verified before release. Pickup storage starts only when paid rugs are marked ready for collection. Collect within ${settings.graceBusinessDays} business days after the ready date; the ready date itself is not counted. Business days exclude Saturdays, Sundays, observed U.S. federal holidays and listed showroom closure dates. Beginning the next calendar day after that deadline, storage is $${(settings.storageDailyCents/100).toFixed(2)} per calendar day per uncollected rug, including weekends. Partial pickups stop new storage for the rugs collected. Delivery orders awaiting showroom dispatch do not accrue customer pickup storage. Storage fees and waivers are shown separately and are not silently added to an already-paid winning invoice. Staff must review identity and payment before pickup. Condition reports, dimensions, photos, bid increments, reserves, late-bid extensions, refund exceptions and dispute procedure must be disclosed before launch.`;}

export function liveTerms(settings){return termsText(settings).replace('Auction terms — preparation version','Auction terms — version').replace('Public auctions remain under construction. ','').replace(/Condition reports, dimensions[\s\S]*$/, 'Bidders must be at least 18 years old. Inspect condition reports, photographs and exact dimensions before bidding. All sales are final; contact the showroom about a material discrepancy before collection. Do not collect or arrange delivery until payment is verified. Questions and disputes: (703) 461-0207, 3260 Duke Street, Alexandria, VA 22314. Shipping fees are the approved per-lot quote accepted with your first bid; those fees are added for the lots you win.');}
