'use client';
import {useState} from 'react';
import {withCompany,workLeftBehind,leftBehind} from '@/lib/washing-priority.mjs';
import s from './Washing.module.css';
const labels:Record<string,string>={acknowledge:'Confirm company receipt',start:'Start washing',ready:'Finished · ready to return',planReturns:'Plan delivery',dispatchReturns:'Confirm departure',receive:'Receive at showroom',accept:'Pass inspection',rewash:'Send for correction',delay:'Report delay'};
export default function BulkWashingControls({jobs,visible,selection,setSelection,vendor,busy,error,today,onSubmit,onDone,onClearError}:{jobs:any[];visible:any[];selection:string[];setSelection:(ids:string[])=>void;vendor:boolean;busy:boolean;error:string;today:string;onSubmit:(body:any)=>Promise<any>;onDone:(note:string)=>void;onClearError:()=>void}){
 const [modal,setModal]=useState<any>(null),[form,setForm]=useState<any>({}),[submitting,setSubmitting]=useState(false);
 const picked=jobs.filter(j=>selection.includes(j.id)&&!j.closed),eligible=visible.filter(j=>!j.closed&&(!vendor||withCompany(j)));
 const allSelected=eligible.length>0&&eligible.every(j=>selection.includes(j.id)),oneCompany=new Set(picked.map(j=>j.companyId)).size===1;
 const enabled=(action:string)=>picked.length>0&&picked.length<=100&&(action==='receive'?!vendor&&picked.every(withCompany):action==='accept'?!vendor&&picked.every(j=>j.status==='Needs inspection'):action==='rewash'?!vendor&&picked.every(j=>['Needs inspection','Inspection issue'].includes(j.status)):action==='start'?picked.every(j=>['At company','Washing'].includes(j.status)):action==='ready'?picked.every(j=>['At company','Washing','Ready'].includes(j.status)):action==='planReturns'?oneCompany&&picked.every(withCompany):action==='dispatchReturns'?oneCompany&&picked.every(j=>withCompany(j)&&j.plannedDate):picked.every(withCompany));
 function open(action:string){onClearError();const snapshot=picked.map(j=>({...j}));setModal({action,jobs:snapshot,requestId:crypto.randomUUID()});setForm({note:'',priorityAcknowledged:false,loadedChecked:false,clean:false,conditionChecked:false,plannedDate:today,receivedDate:today,sentDate:today,dueDate:new Date(Date.parse(today+'T12:00:00Z')+7*86400000).toISOString().slice(0,10),checks:Object.fromEntries(snapshot.map(j=>[j.id,{confirmSku:'',photoMatched:false}]))});}
 const skipped=modal&&['start','ready'].includes(modal.action)?workLeftBehind(jobs,modal.jobs):[];
 const deliveryDate=modal?.action==='dispatchReturns'?today:form.plannedDate;
 const behind=modal&&['planReturns','dispatchReturns'].includes(modal.action)?leftBehind(jobs,modal.jobs,deliveryDate,today):[];
 const late=modal&&['planReturns','dispatchReturns'].includes(modal.action)?modal.jobs.filter((j:any)=>(j.returnBy||j.dueDate)<deliveryDate):[];
 const warning=skipped.length>0||behind.length>0||late.length>0;
 async function submit(e:any){e.preventDefault();if(submitting||busy)return;setSubmitting(true);try{const delivery=['planReturns','dispatchReturns'].includes(modal.action),body={...form,action:delivery?modal.action:'bulk',bulkAction:modal.action,requestId:modal.requestId,companyId:modal.jobs[0].companyId,rugs:modal.jobs.map((j:any)=>({id:j.id,version:j.version}))};const result=await onSubmit(body);if(result){const text=labels[modal.action]+' · '+modal.jobs.length+' rugs saved.';setSelection([]);setModal(null);onDone(text);}}finally{setSubmitting(false);}}
 return <>
 <section className={`${s.panel} ${s.noPrint} ${s.bulkBar}`} aria-label="Bulk rug actions"><h2>Bulk actions · {picked.length} selected</h2><div className={s.actions}><button className={s.secondary} disabled={busy||!eligible.length} onClick={()=>setSelection(allSelected?[]:eligible.map(j=>j.id))}>{allSelected?'Deselect all':'Select all visible'} · {eligible.length}</button><button className={s.secondary} disabled={busy||!picked.length} onClick={()=>setSelection([])}>Clear selection</button></div><p className={s.small}>Select individual rugs, a pickup batch, or all eligible rugs in this view. Up to 100 rugs per update. Actions enable when every selected rug is in the correct stage; delivery must be for one company.</p>{picked.length>100&&<p className={s.error}>Choose 100 or fewer rugs for this update.</p>}<div className={s.actions}>{Object.entries(labels).filter(([action])=>!vendor||!['receive','accept','rewash'].includes(action)).map(([action,label])=><button key={action} className={s.secondary} disabled={busy||!enabled(action)} onClick={()=>open(action)}>{label}</button>)}</div></section>
 {modal&&<div className={s.modal} role="dialog" aria-modal="true" aria-labelledby="washing-bulk-title"><form className={s.dialog} onSubmit={submit}><h2 id="washing-bulk-title">{labels[modal.action]} · {modal.jobs.length} rugs</h2><p>Selected MPWs: {modal.jobs.map((j:any)=>j.sku).join(', ')}</p><p className={s.small}>Every selected rug is checked before saving. A failed check or outdated record stops the entire update.</p>
 {modal.action==='receive'&&<><label>Actual return date<input type="date" required min={modal.jobs.map((j:any)=>j.sentDate).sort().at(-1)} max={today} value={form.receivedDate} onChange={e=>setForm({...form,receivedDate:e.target.value})}/></label>{modal.jobs.map((j:any)=><fieldset className={s.bulkCheck} key={j.id}><legend>{j.sku} · {j.description}</legend>{j.photo&&<img src={j.photo} alt={'Match '+j.sku} referrerPolicy="no-referrer"/>}<label>Type the MPW from its physical tag<input required value={form.checks[j.id].confirmSku} onChange={e=>setForm({...form,checks:{...form.checks,[j.id]:{...form.checks[j.id],confirmSku:e.target.value}}})}/></label><label><input type="checkbox" required checked={form.checks[j.id].photoMatched} onChange={e=>setForm({...form,checks:{...form.checks,[j.id]:{...form.checks[j.id],photoMatched:e.target.checked}}})}/>This rug matches its reference photo or description.</label></fieldset>)}</>}
 {modal.action==='accept'&&<><label><input type="checkbox" required checked={form.clean} onChange={e=>setForm({...form,clean:e.target.checked})}/>I inspected every selected rug and its cleaning is satisfactory.</label><label><input type="checkbox" required checked={form.conditionChecked} onChange={e=>setForm({...form,conditionChecked:e.target.checked})}/>I checked every selected rug’s condition against its original record.</label><p className={s.small}>Invoice readiness still waits for all rugs and required repairs. Rugs with a problem should be deselected and reported separately.</p></>}
 {modal.action==='planReturns'&&<label>Delivery date<input type="date" required min={today} value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label>}
 {modal.action==='dispatchReturns'&&<label><input type="checkbox" required checked={form.loadedChecked} onChange={e=>setForm({...form,loadedChecked:e.target.checked})}/>I checked the physical MPW tags. These exact rugs are loaded and leaving for the showroom today.</label>}
 {modal.action==='rewash'&&<><label>Correction sent date<input type="date" required value={form.sentDate} onChange={e=>setForm({...form,sentDate:e.target.value})}/></label><label>Company return deadline<input type="date" required min={form.sentDate} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><p className={s.small}>Each rug keeps its recorded customer pickup date and original pickup batch.</p></>}
 {warning&&<div className={s.error}><strong>Priority warning</strong>{skipped.length>0&&<p>Earlier work left behind: {skipped.map((j:any)=>j.sku).join(', ')}</p>}{behind.length>0&&<p>Earlier returns left behind: {behind.map((j:any)=>j.sku).join(', ')}</p>}{late.length>0&&<p>Return deadline missed: {late.map((j:any)=>j.sku).join(', ')}</p>}<label><input type="checkbox" required checked={form.priorityAcknowledged} onChange={e=>setForm({...form,priorityAcknowledged:e.target.checked})}/>I checked the priorities and will explain the change.</label></div>}
 <label>Notes<textarea maxLength={500} required={warning||modal.action==='delay'} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{error&&<p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button disabled={busy||submitting}>{busy||submitting?'Saving…':'Confirm '+modal.jobs.length+' rugs'}</button><button type="button" className={s.secondary} disabled={busy||submitting} onClick={()=>setModal(null)}>Cancel</button></div></form></div>}
 </>;
}
