'use client';
import {useEffect,useState,useRef} from 'react';
import {auth} from '@/lib/auth';
import {getAllInvoices} from '@/lib/invoice-storage';
import {getServiceVendors} from '@/lib/service-vendor-storage';
import {getStorePrefix} from '@/lib/user-storage';
import {useStaffAccess} from '@/hooks/useStaffAccess';
import {canAccess} from '@/lib/access-policy';
import s from './Washing.module.css';
async function compressPhoto(source:string){if(!source)return '';if(source.startsWith('https://'))return source;return new Promise<string>(resolve=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,640/image.width,640/image.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return resolve('');ctx.drawImage(image,0,0,canvas.width,canvas.height);let result='';for(const quality of [.75,.55,.35,.2]){result=canvas.toDataURL('image/jpeg',quality);if(result.length<60000)break;}resolve(result.length<60000?result:'');};image.onerror=()=>resolve('');image.src=source;});}
const day=(d:string,n:number)=>{const date=new Date(d+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);};
const display=(d:string)=>d?new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'Not set';
export default function WashingBoard({vendor=false}:{vendor?:boolean}){
 const {staff,loading:staffLoading}=useStaffAccess();
 const [token,setToken]=useState(''),[tokenReady,setTokenReady]=useState(false),[data,setData]=useState<any>({companies:[],jobs:[],exceptions:[],today:'2026-01-01'}),[company,setCompany]=useState(''),[tab,setTab]=useState('active'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[note,setNote]=useState(''),[link,setLink]=useState('');
 const [newCompany,setNewCompany]=useState(''),[vendorNames,setVendorNames]=useState<string[]>([]),[batchOpen,setBatchOpen]=useState(false),[candidates,setCandidates]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[batch,setBatch]=useState(''),[sent,setSent]=useState(''),[due,setDue]=useState('');
 const [dialog,setDialog]=useState<any>(null),[form,setForm]=useState<any>({}),[history,setHistory]=useState<any[]>([]);
 const requestId=useRef(''),canWrite=vendor||canAccess(staff,'services','write');
 useEffect(()=>{if(vendor){setToken(window.location.hash.slice(1));setTokenReady(true);}else setTokenReady(true);},[vendor]);
 async function request(body?:any,query=''){
  const headers:Record<string,string>={'Content-Type':'application/json'};
  if(vendor){if(!token)throw Error('Ask Marco Polo Rugs for your private company link.');headers['x-wash-link']=token;}else{if(!auth.currentUser)throw Error('Please sign in.');headers.Authorization='Bearer '+await auth.currentUser.getIdToken();}
  const r=await fetch('/api/washing'+query,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Please retry.');return d;
 }
 async function refresh(){setError('');try{const d=await request(undefined,company&&!vendor?'?company='+encodeURIComponent(company):'');setData(d);setSent(v=>v||d.today);setDue(v=>v||day(d.today,7));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(!tokenReady||(!vendor&&(staffLoading||!staff)))return;void refresh();},[tokenReady,token,company,staffLoading,staff?.uid]);
 useEffect(()=>{if(!tokenReady||(!vendor&&!staff))return;const timer=setInterval(()=>{if(!busy)void refresh();},45000);return()=>clearInterval(timer);},[tokenReady,token,company,busy,staff?.uid]);
 useEffect(()=>{if(vendor||!staff)return;void getServiceVendors().then(v=>setVendorNames(v.map(c=>c.name))).catch(()=>{});},[vendor,staff?.uid]);
 async function mutate(body:any){if(busy)return;setBusy(true);setError('');try{const result=await request(body);await refresh();return result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 const today=data.today,weekEnd=day(today,6),open=data.jobs.filter((j:any)=>!j.closed),atCompany=(j:any)=>['At company','Ready','Delivery planned'].includes(j.status),overdue=open.filter((j:any)=>atCompany(j)&&j.dueDate<today),dueWeek=open.filter((j:any)=>atCompany(j)&&j.dueDate>=today&&j.dueDate<=weekEnd),inspect=open.filter((j:any)=>!atCompany(j));
 const filtered=data.jobs.filter((j:any)=>{const match=(j.sku+' '+j.description+' '+j.batch+' '+(vendor?'':j.customerName||'')).toLowerCase().includes(search.toLowerCase());return match&&(tab==='history'?j.closed:tab==='overdue'?overdue.includes(j):tab==='week'?dueWeek.includes(j):tab==='inspection'?inspect.includes(j):!j.closed);});
 async function loadCandidates(){setBusy(true);setError('');try{if(!canAccess(staff,'invoices','read'))throw Error('Invoice read permission is needed to select saved wash rugs.');const invoices=await getAllInvoices();setCandidates(invoices.filter(i=>i.data.documentType==='WASH'||i.data.mode==='wash').filter(i=>i.data.status!=='picked_up').flatMap(i=>i.data.items.filter(r=>/^MPW\d+$/i.test(r.sku)).map(r=>({key:i.id+':'+r.id,invoiceId:i.id,itemId:r.id,sku:r.sku,description:r.description,customer:i.data.soldTo.name,pickup:i.data.pickupDate||'',photo:r.images?.[0]||r.image||''}))));setSelected([]);setBatch('Weekly handoff · '+today);requestId.current=crypto.randomUUID();setBatchOpen(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function openDialog(job:any,action:string){setError('');setHistory([]);setDialog({job,action});setForm({note:'',confirmSku:'',photoMatched:false,clean:false,conditionChecked:false,receivedDate:today,plannedDate:today,sentDate:action==='reschedule'?job.sentDate:today,dueDate:action==='reschedule'?job.dueDate:day(today,7),pickupDate:job?.pickupDate||'',photo:''});}
 async function submitDialog(e:any){e.preventDefault();const body={...form,action:dialog.action,id:dialog.job?.id,version:dialog.job?.version,companyId:company||data.companies[0]?.id};const result=await mutate(body);if(result)setDialog(null);}
 async function showHistory(job:any){setDialog({job,action:'history'});setBusy(true);try{const d=await request(undefined,'?history='+encodeURIComponent(job.id));setHistory(d.history);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className={s.shell}>
  <header className={s.hero}><div><span className={s.eyebrow}>Marco Polo Rugs · Washing care</span><h1>{vendor?data.companies[0]?.name||'Your weekly rug returns':'Every rug. Every return.'}</h1><p>{vendor?'Your handoff list, return dates, and delivery updates in one place. Match each MPW tag to its rug before loading.':'A clear journey from showroom to washing company—and safely back to the customer.'}</p></div><button type="button" className={s.noPrint} onClick={()=>window.print()}>Print list / save PDF</button></header>
  {error&&<p role="alert" className={s.error}>{error}</p>}{note&&<p role="status" className={s.notice}>{note}</p>}
  <div className={s.stats}>{[[open.filter(atCompany).length,'At washing company'],[dueWeek.length,'Due in next 7 days'],[overdue.length,'Overdue'],[inspect.length,'Awaiting inspection']].map(([n,label])=><div className={s.stat} key={label}><strong>{n}</strong>{label}</div>)}</div>
  <div className={s.toolbar}>
   {!vendor&&<select aria-label="Washing company" disabled={busy} value={company} onChange={e=>{setCompany(e.target.value);setLink('');}}><option value="">All companies</option>{data.companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}
   <input aria-label="Find a rug" placeholder="Find MPW number or rug…" value={search} onChange={e=>setSearch(e.target.value)}/>
   <select aria-label="View rugs" value={tab} onChange={e=>setTab(e.target.value)}><option value="active">All outstanding rugs</option><option value="week">Due in next 7 days</option><option value="overdue">Overdue returns</option><option value="inspection">Inspection & issues</option><option value="history">Completed returns (up to 100)</option></select>
   <button disabled={busy} onClick={refresh} className={s.secondary}>Refresh</button>
   {!vendor&&canWrite&&<button disabled={busy||!company} onClick={loadCandidates}>+ Weekly handoff</button>}
  </div>
  {!vendor&&canWrite&&<details className={`${s.panel} ${s.noPrint}`}><summary>Companies & private links</summary><p className={s.small}>Create a washing-company workspace, then share its private link. Anyone with that link can view that company’s rugs and submit delivery updates. Replacing or disabling it removes the old link’s access.</p><div className={s.toolbar}><input list="washing-companies" aria-label="Company name" value={newCompany} onChange={e=>setNewCompany(e.target.value)} placeholder="Washing company name"/><datalist id="washing-companies">{vendorNames.map(n=><option value={n} key={n}/>)}</datalist><button disabled={busy||!newCompany.trim()} onClick={async()=>{const d=await mutate({action:'company',name:newCompany});if(d){setNewCompany('');setCompany(d.id);}}}>Add company workspace</button></div>{company&&<div className={s.actions}><button disabled={busy} onClick={()=>openDialog(null,'link')}>Create / replace private link</button><button disabled={busy} className={s.secondary} onClick={()=>openDialog(null,'revoke')}>Disable link</button></div>}{link&&<div className={s.notice}><label>Private company link<input className={s.link} value={link} readOnly onFocus={e=>e.target.select()}/></label><button onClick={async()=>{try{await navigator.clipboard.writeText(link);setNote('Company link copied.');}catch{setNote('Select and copy the link above.');}}}>Copy link</button><p className={s.small}>Keep this link private. It is shown here only when created; replace it if lost.</p></div>}</details>}
  {batchOpen&&<form className={`${s.panel} ${s.noPrint}`} onSubmit={async e=>{e.preventDefault();const result=await mutate({action:'batch',companyId:company,invoiceCollection:getStorePrefix()+'invoices',sentDate:sent,dueDate:due,batch,requestId:requestId.current,rugs:await Promise.all(candidates.filter(c=>selected.includes(c.key)).map(async c=>({invoiceId:c.invoiceId,itemId:c.itemId,photo:await compressPhoto(c.photo)})))});if(result){setBatchOpen(false);setNote('Handoff saved. The company can now see its assigned rugs.');}}}><h2>Prepare your weekly handoff</h2><p>Choose saved wash-invoice rugs. Each MPW number can have only one outstanding washing job.</p><div className={s.formGrid}><label>Handoff name<input required value={batch} maxLength={80} onChange={e=>{setBatch(e.target.value);requestId.current=crypto.randomUUID();}}/></label><label>Date sent<input type="date" required value={sent} onChange={e=>{setSent(e.target.value);requestId.current=crypto.randomUUID();}}/></label><label>Company return deadline<input type="date" required min={sent} value={due} onChange={e=>{setDue(e.target.value);requestId.current=crypto.randomUUID();}}/></label></div><p className={s.small}>Use a return deadline a few days before customer pickup. Customer pickup dates stay private to your staff.</p><div className={s.selection}>{candidates.length?candidates.map(c=><label key={c.key}><input type="checkbox" checked={selected.includes(c.key)} onChange={e=>{setSelected(v=>e.target.checked?[...v,c.key]:v.filter(k=>k!==c.key));requestId.current=crypto.randomUUID();}}/><strong>{c.sku}</strong> · {c.description} · {c.customer}{c.pickup?' · Customer pickup '+display(c.pickup.slice(0,10)):''}</label>):<p>No saved wash rugs found. Create or save a wash invoice with MPW numbers first.</p>}</div><div className={s.actions}><button disabled={busy||!selected.length||selected.length>40}>Save handoff · {selected.length} rugs</button><button type="button" className={s.secondary} onClick={()=>setBatchOpen(false)}>Cancel</button></div></form>}
  {loading?<div className={s.empty}>Loading your washing schedule…</div>:filtered.length?<div className={s.grid}>{filtered.map((j:any)=><article className={s.card} key={j.id}>{j.photo?<img src={j.photo} alt={'Reference rug '+j.sku} loading="lazy" referrerPolicy="no-referrer"/>:<div className={s.placeholder}>Reference photo not available</div>}<div className={s.body}><span className={`${s.badge} ${overdue.includes(j)?s.danger:''}`}>{overdue.includes(j)?'Overdue · ':''}{j.status}</span>{j.timing&&<span className={s.badge}>{j.timing} return</span>}<h3>{j.sku}</h3><p>{j.description}<br/>{j.size}</p><p className={s.small}>{j.batch}{!vendor&&<><br/>{j.companyName} · {j.customerName} · Invoice {j.invoiceNumber}</>}</p><div className={s.dates}><div>Sent<strong>{display(j.sentDate)}</strong></div><div>Return deadline<strong>{display(j.dueDate)}</strong></div>{!vendor&&j.pickupDate&&<div>Customer pickup<strong>{display(j.pickupDate)}</strong></div>}{j.plannedDate&&<div>Planned delivery<strong>{display(j.plannedDate)}</strong></div>}{j.receivedDate&&<div>Received<strong>{display(j.receivedDate)}</strong></div>}</div>{j.issuePhoto&&<img src={j.issuePhoto} alt="Inspection issue" referrerPolicy="no-referrer"/>}{j.conditions&&<p className={s.small}>Recorded condition: {j.conditions}</p>}{j.vendorNote&&<p className={s.notice}>Company update: {j.vendorNote}</p>}{j.inspectionNote&&<p className={s.notice}>Showroom inspection: {j.inspectionNote}</p>}{!j.closed&&canWrite&&<div className={s.actions}>{vendor?atCompany(j)&&<>{!j.acknowledgedAt&&<button disabled={busy} onClick={()=>mutate({action:'acknowledge',id:j.id,version:j.version})}>Confirm rug received</button>}<button disabled={busy} onClick={()=>openDialog(j,'ready')}>Ready to return</button><button disabled={busy} onClick={()=>openDialog(j,'plan')}>Plan delivery</button><button className={s.secondary} onClick={()=>openDialog(j,'delay')}>Report delay</button></>:<>{atCompany(j)?<button onClick={()=>openDialog(j,'receive')}>Check rug on arrival</button>:j.status==='Needs inspection'?<><button onClick={()=>openDialog(j,'accept')}>Pass inspection</button><button className={s.secondary} onClick={()=>openDialog(j,'issue')}>Cleaning / damage issue</button></>:null}{['Needs inspection','Inspection issue'].includes(j.status)&&<button onClick={()=>openDialog(j,'rewash')}>Send for correction</button>}<button className={s.secondary} onClick={()=>openDialog(j,'reschedule')}>Edit dates</button><button className={s.secondary} onClick={()=>openDialog(j,'reference')}>Update rug photo</button></>}</div>}{!vendor&&<div className={s.actions}><button className={s.secondary} onClick={()=>showHistory(j)}>Rug history</button></div>}<p className={s.small}>{j.acknowledgedAt?'Company confirmed receipt':'Company receipt not yet confirmed'}</p></div></article>)}</div>:<div className={s.empty}>No rugs in this view.{!vendor&&' Select a company and prepare your first weekly handoff.'}</div>}
  <section className={s.panel}><h2>Delivery exceptions</h2><p>Record wrong rugs or missing deliveries here. Reporting an exception never marks the expected rug as returned.</p>{canWrite&&<button disabled={!vendor&&!company} className={s.noPrint} onClick={()=>openDialog(null,'exception')}>+ Report delivery problem</button>}{!vendor&&!company&&<p className={s.small}>Select a company to see its delivery exceptions.</p>}{data.exceptions.map((x:any)=><div className={s.notice} key={x.id}><strong>{x.resolved?'Resolved':'Open issue'}</strong><p>{x.note}</p>{x.photo&&<img src={x.photo} alt="Delivery exception" style={{maxWidth:180}} referrerPolicy="no-referrer"/>}{x.resolution&&<p>{x.resolution}</p>}<small>{x.reportedBy} · {display(x.createdAt.slice(0,10))}</small>{!vendor&&canWrite&&!x.resolved&&<button className={s.noPrint} onClick={()=>openDialog({id:x.id},'resolveException')}>Resolve issue</button>}</div>)}</section>
  {dialog&&<div className={s.modal}><form className={s.dialog} onSubmit={async e=>{if(['link','revoke'].includes(dialog.action)){e.preventDefault();const d=await mutate({action:dialog.action,companyId:company});if(d){setLink(d.token?window.location.origin+'/washing-company#'+d.token:'');setDialog(null);setNote(d.token?'New company link created. Any previous link is now disabled.':'Company link disabled.');}}else await submitDialog(e);}}><h2>{({receive:'Match this rug on arrival',accept:'Final cleaning inspection',plan:'Plan your delivery',ready:'Ready to return',delay:'Report a delay',issue:'Record an inspection issue',rewash:'Send for correction',reschedule:'Update return schedule',exception:'Report a delivery problem',resolveException:'Resolve delivery problem',link:'Create or replace company link',revoke:'Disable company link',reference:'Update reference photo',history:'Rug history'} as any)[dialog.action]} {dialog.job?.sku}</h2>
   {dialog.action==='history'?<>{history.map((h:any)=><p key={h.id}><strong>{h.action}</strong> · {new Date(h.at).toLocaleString()}<br/><span className={s.small}>{JSON.stringify(h.changes)}</span></p>)}{!history.length&&<p>No history loaded yet.</p>}</>:<>
   {['link','revoke'].includes(dialog.action)&&<p>{dialog.action==='link'?'This creates a new private link. The company’s previous link will stop working.':'The company will no longer be able to open its current link.'}</p>}
   {dialog.action==='receive'&&<><label>Type the MPW number from the physical tag<input required value={form.confirmSku} onChange={e=>setForm({...form,confirmSku:e.target.value})}/></label><label><input type="checkbox" required checked={form.photoMatched} onChange={e=>setForm({...form,photoMatched:e.target.checked})}/>The rug matches the reference photo or invoice description.</label><label>Actual return date<input type="date" required min={dialog.job.sentDate} max={today} value={form.receivedDate} onChange={e=>setForm({...form,receivedDate:e.target.value})}/></label></>}
   {dialog.action==='accept'&&<><label><input type="checkbox" required checked={form.clean} onChange={e=>setForm({...form,clean:e.target.checked})}/>Cleaning is satisfactory.</label><label><input type="checkbox" required checked={form.conditionChecked} onChange={e=>setForm({...form,conditionChecked:e.target.checked})}/>Condition checked against the original record.</label><p className={s.small}>Completes this washing job. The customer invoice status is managed separately.</p></>}
   {dialog.action==='plan'&&<label>We will bring this rug on<input type="date" min={today} required value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label>}
   {['rewash','reschedule'].includes(dialog.action)&&<><label>Sent date<input type="date" required value={form.sentDate} onChange={e=>setForm({...form,sentDate:e.target.value})}/></label><label>Company return deadline<input type="date" required min={form.sentDate} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Customer pickup date (staff only)<input type="date" value={form.pickupDate} onChange={e=>setForm({...form,pickupDate:e.target.value})}/></label></>}
   {!['link','revoke'].includes(dialog.action)&&<label>Notes<textarea maxLength={500} required={['delay','issue','exception','resolveException'].includes(dialog.action)} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>}
   {['issue','exception','reference'].includes(dialog.action)&&<><label>Add a photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>12000000){setError('Choose a photo smaller than 12 MB.');return;}setBusy(true);try{const source=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Could not open this photo.'));reader.readAsDataURL(file);});const image=await compressPhoto(source);if(!image)throw Error('Could not prepare this photo. Try a smaller image.');setForm((v:any)=>({...v,photo:image}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{form.photo&&<img src={form.photo} alt="Photo preview" style={{maxHeight:160,maxWidth:'100%'}}/>}<label>Or enter a photo URL<input type="url" placeholder="https://…" value={form.photo.startsWith('data:')?'':form.photo} onChange={e=>setForm({...form,photo:e.target.value})}/></label></>}
   </>}{error&&<p role="alert" className={s.error}>{error}</p>}<div className={s.actions}>{dialog.action!=='history'&&<button disabled={busy}>{busy?'Saving…':'Confirm'}</button>}<button type="button" className={s.secondary} disabled={busy} onClick={()=>setDialog(null)}>Close</button></div></form></div>}
 </main>;
}
