import assert from 'node:assert/strict';
export function database(seed={}){
 let values=new Map(Object.entries(structuredClone(seed))),queue=Promise.resolve();
 const snapshot=(path,map=values)=>({id:path.split('/').at(-1),exists:map.has(path),data:()=>structuredClone(map.get(path))});
 const query=(path,filters=[],max=Infinity)=>({path,query:true,filters,max,where:(k,op,v)=>query(path,[...filters,[k,v]],max),limit:n=>query(path,filters,n),orderBy:()=>query(path,filters,max),doc:id=>ref(path+'/'+id),get:async()=>readQuery({path,filters,max},values)});
 const readQuery=(q,map)=>{const docs=[...map.keys()].filter(p=>p.startsWith(q.path+'/')&&!p.slice(q.path.length+1).includes('/')&&q.filters.every(([k,v])=>map.get(p)[k]===v)).slice(0,q.max).map(p=>snapshot(p,map));return {docs,size:docs.length};};
 const ref=path=>({path,id:path.split('/').at(-1),get:async()=>snapshot(path),collection:name=>query(path+'/'+name),set:async v=>{values.set(path,{...values.get(path),...structuredClone(v)});},update:async v=>{assert.ok(values.has(path));values.set(path,{...values.get(path),...structuredClone(v)});}});
 const db={doc:ref,collection:query,read:p=>structuredClone(values.get(p)),keys:()=>[...values.keys()],change:(p,v)=>values.set(p,{...values.get(p),...structuredClone(v)}),runTransaction(fn){const run=queue.then(async()=>{const next=new Map(structuredClone([...values]));let writing=false;const get=async r=>{assert.equal(writing,false,'all reads precede writes');return r.query?readQuery(r,next):snapshot(r.path,next);};const tx={get,getAll:async(...rs)=>Promise.all(rs.map(get)),create(r,v){writing=true;assert.equal(next.has(r.path),false);next.set(r.path,structuredClone(v));},set(r,v,options){writing=true;next.set(r.path,options?.merge?{...next.get(r.path),...structuredClone(v)}:structuredClone(v));},update(r,v){writing=true;assert.ok(next.has(r.path));next.set(r.path,{...next.get(r.path),...structuredClone(v)});}};const result=await fn(tx);values=next;return result;});queue=run.catch(()=>{});return run;}};return db;
}
