'use client';
import React from 'react';
import {useStore} from '@/context/StoreContext';
import {availableRugs,sizeGroup} from '@/lib/rug-discovery.mjs';
import {RugCard} from './ShoppingTools';
import {Rug} from '@/types';
import s from './Shopping.module.css';
export const Hero=({setCurrentTab,onSelectRugId}:{setCurrentTab:(tab:string)=>void;onSelectRugId:(id:string|null)=>void})=>{
 const {publicRugs,heroCoverPhotos,reviews,websiteContent,isEditMode,setWebsiteContent}=useStore();
 const rugs=availableRugs(publicRugs) as Rug[];
 const text=(key:string,fallback:string)=>isEditMode?<input aria-label={`Edit ${key}`} className={s.editable} value={websiteContent[key]??fallback} onChange={e=>setWebsiteContent({...websiteContent,[key]:e.target.value})}/>:websiteContent[key]||fallback;
 const featured=rugs.filter(r=>r.images?.length).slice(0,6);
 const feedback=reviews.filter(r=>r.isApproved===true&&r.reviewText).slice(0,3);
 let customerRooms:{url:string;caption:string;permissionConfirmed?:boolean}[]=[];try{const raw=JSON.parse(websiteContent.customer_room_photos||'[]');if(Array.isArray(raw))customerRooms=raw.filter(x=>x&&x.permissionConfirmed===true&&/^https:\/\//.test(x.url)).slice(0,3);}catch{}
 return <main className={s.shell}><section className={s.hero}><div className={s.heroCopy}><span className={s.eyebrow}>Alexandria, Virginia · Since 1988</span><h1>{text('home_headline_v2','Find a rug that feels at home.')}</h1><p>{text('home_intro_v2','Explore our rug collection with personal help choosing the right size, color and style. A piece for your room, and your everyday life.')}</p><div className={s.row}><button className={s.btn} onClick={()=>setCurrentTab('shop')}>Explore the rugs</button><button className={s.secondary} onClick={()=>setCurrentTab('book')}>Visit our showroom</button></div></div><img className={s.heroPhoto} src={websiteContent.home_image_v2||heroCoverPhotos[0]||featured[0]?.images[0]||'/icon.png'} alt="Marco Polo Rugs collection" fetchPriority="high"/></section><div className={s.trust}><span>Since 1988</span><span>Free padding with every rug</span><span>Personal showroom assistance</span></div><div className={s.wrap}>
 <section className={s.section}><div className={s.between}><div><span className={s.eyebrow}>Start with your space</span><h2>A size for every room.</h2></div><a href="/?view=shop&guide=1" className={s.secondary}>Explore the size guide</a></div><div className={s.sizeTiles}>{['Small','Medium','Large','Oversized','Runners'].map((size,i)=><a className={s.sizeTile} key={size} href={`/?view=shop&f_size=${size}`}><svg width="60" height="55" viewBox="0 0 60 55" style={{margin:'auto'}} aria-hidden="true"><rect x={i===4?22:10} y="5" width={i===4?16:40} height={i===0?30:45} fill="#d2bd9d" stroke="#90734f"/><rect x={i===4?25:14} y="9" width={i===4?10:32} height={i===0?22:37} fill="none" stroke="#90734f"/></svg><strong>{size}</strong><span className={s.muted}>{rugs.filter(r=>sizeGroup(r)===size).length} available</span></a>)}</div></section>
 <section className={s.section}><div className={s.between}><div><span className={s.eyebrow}>Take a closer look</span><h2>From our collection.</h2></div><button className={s.secondary} onClick={()=>setCurrentTab('shop')}>Shop all rugs</button></div>{featured.length?<div className={s.grid}>{featured.map(r=><RugCard key={r.id} rug={r} onSelect={onSelectRugId}/>)}</div>:<p className={s.notice}>Our collection is loading. You can also call (703) 461-0207 for help finding a rug.</p>}</section>
 <section className={`${s.section} ${s.split}`}><div><span className={s.eyebrow}>Your room. Your style.</span><h2>A little help finding the one.</h2><p>Start with a size, a color or a budget. Save your favorites, compare them side by side and bring your shortlist to the showroom.</p><a className={s.btn} href="/?view=shop&finder=1">Find my rug</a></div><div className={s.panel}><span className={s.eyebrow}>Visit Marco Polo Rugs</span><h3>See the colors. Feel the texture.</h3><p>3260 Duke St<br/>Alexandria, VA 22314</p><p>Every day, 10:00 AM–6:00 PM<br/>Appointment break: 1:30–2:00 PM</p><div className={s.row}><button className={s.btn} onClick={()=>setCurrentTab('book')}>Book a visit</button><a className={s.secondary} href="tel:+17034610207">(703) 461-0207</a></div></div></section>
 {feedback.length>0&&<section className={s.section}><span className={s.eyebrow}>From our customers</span><h2>Stories worth sharing.</h2><div className={s.grid}>{feedback.map(r=><blockquote className={s.review} key={r.id}><p>“{r.reviewText}”</p><footer>{r.reviewerName}</footer></blockquote>)}</div></section>}
 {customerRooms.length>0&&<section className={s.section}><h2>At home with Marco Polo.</h2><div className={s.grid}>{customerRooms.map(x=><figure key={x.url}><img style={{width:'100%',aspectRatio:'4/3',objectFit:'cover',borderRadius:6}} src={x.url} alt={x.caption} loading="lazy"/><figcaption>{x.caption}</figcaption></figure>)}</div></section>}
 {isEditMode&&<section className={s.panel}><h2>Homepage photos</h2><label className={s.field}>Cover photo URL<input type="url" value={websiteContent.home_image_v2||''} onChange={e=>setWebsiteContent({...websiteContent,home_image_v2:e.target.value})}/></label><p>Add customer room photos only with permission. Use Publish Changes above to save.</p>{[0,1,2].map(i=>{let entries:any[]=[];try{entries=JSON.parse(websiteContent.customer_room_photos||'[]');if(!Array.isArray(entries))entries=[];}catch{}const item=entries[i]||{};const update=(field:string,value:string|boolean)=>{const next=[...entries];next[i]={...item,[field]:value};setWebsiteContent({...websiteContent,customer_room_photos:JSON.stringify(next)});};return <fieldset key={i} className={s.panel}><legend>Room photo {i+1}</legend><label className={s.field}>Photo URL<input type="url" value={item.url||''} onChange={e=>update('url',e.target.value)}/></label><label className={s.field}>Caption<input value={item.caption||''} onChange={e=>update('caption',e.target.value)}/></label><label><input type="checkbox" checked={item.permissionConfirmed===true} onChange={e=>update('permissionConfirmed',e.target.checked)}/> I have permission to publish this customer photo.</label></fieldset>;})}</section>}
 <section className={s.section}><span className={s.eyebrow}>Care for the rugs you love</span><h2>Beautiful today. Cared for tomorrow.</h2><div className={s.grid}>{[['Cleaning','A cleaning plan suited to your rug’s material and condition.','/services/rug-cleaning-alexandria-va'],['Repair & restoration','Get advice on worn edges, fringe and damaged areas.','/services/rug-repair-restoration-alexandria-va'],['Service estimate','Tell us about your rug and the care it needs.','/services/estimate']].map(([name,desc,href])=><div className={s.panel} key={name}><h3>{name}</h3><p>{desc}</p><a className={s.secondary} href={href}>Learn more</a></div>)}</div></section></div></main>;
};
