'use client';
import React,{useEffect,useRef} from 'react';
import {X,Heart} from 'lucide-react';
import {Rug} from '@/types';
import {useStore} from '@/context/StoreContext';
import {money} from '@/lib/rug-discovery.mjs';
import s from './Shopping.module.css';

export function ShoppingDialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {
 const ref=useRef<HTMLDivElement>(null), close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();
 const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();close.current();}if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea,summary,[tabindex="0"]')||[]).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(!first){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}};
 ref.current?.addEventListener('keydown',key);const el=ref.current;return()=>{el?.removeEventListener('keydown',key);document.body.style.overflow=old;previous?.focus();};},[]);
 return <div className={`${s.shell} ${s.shade}`} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className={s.dialog} ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><button className={`${s.icon} ${s.close}`} onClick={onClose} aria-label={`Close ${title}`}><X size={20}/></button>{children}</div></div>;
}
export function RugCard({rug,onSelect,compare,onCompare}:{rug:Rug;onSelect:(id:string)=>void;compare?:boolean;onCompare?:(id:string)=>void}) {
 const {favoritedRugIds,toggleRugFavorite}=useStore();const saved=favoritedRugIds.includes(rug.id);
 return <article className={s.card}><div style={{position:'relative'}}><a className={s.photo} href={`/shop/${rug.id}`} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();onSelect(rug.id);}}>{rug.images?.[0]?<img src={rug.images[0]} alt={`${rug.name}, ${rug.dimensions}`} loading="lazy" decoding="async"/>:<span>Photo coming soon</span>}</a><button className={`${s.icon} ${s.favorite}`} aria-label={`${saved?'Unsave':'Save'} ${rug.name}`} aria-pressed={saved} onClick={()=>toggleRugFavorite(rug.id)}><Heart size={19} fill={saved?'#183f35':'none'}/></button></div><a className={s.cardTitle} href={`/shop/${rug.id}`} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();onSelect(rug.id);}}>{rug.name}</a><div className={s.muted}>{rug.dimensions} · {rug.material || 'Ask about material'}</div><div className={s.between} style={{marginTop:10}}><span className={s.price}>{money(rug.price)}</span><span className={s.tag}>Free padding</span></div><div className={s.between} style={{marginTop:12}}><button className={s.secondary} onClick={()=>onSelect(rug.id)}>View rug</button>{onCompare&&<label className={s.muted}><input type="checkbox" checked={!!compare} onChange={()=>onCompare(rug.id)}/> Compare</label>}</div></article>;
}
export function SizeGuide({onClose}:{onClose:()=>void}) {return <ShoppingDialog title="Rug size guide" onClose={onClose}><span className={s.eyebrow}>Make room for the right rug</span><h2>Find your fit</h2><p>Measure your furniture and floor first. These diagrams show placement ideas, not exact scale.</p><div className={s.guideGrid}>{['Living room','Dining room','Bedroom'].map((room,i)=><div key={room}><svg viewBox="0 0 260 180" role="img" aria-label={`${room} rug placement diagram`}><rect x="30" y="30" width="200" height="120" rx="3" fill="#d4b58b" stroke="#90734f" strokeDasharray="5 4"/>{i===0?<><rect x="55" y="15" width="150" height="40" rx="6" fill="#355b4a"/><rect x="25" y="70" width="40" height="60" rx="6" fill="#355b4a"/><rect x="100" y="80" width="70" height="35" rx="5" fill="#faf9f6"/></>:i===1?<><rect x="80" y="60" width="100" height="60" rx="8" fill="#355b4a"/>{[65,180].map(x=>[55,105].map(y=><rect key={`${x}-${y}`} x={x} y={y} width="16" height="22" rx="3" fill="#faf9f6"/>))}</>:<><rect x="80" y="15" width="100" height="110" rx="5" fill="#355b4a"/><rect x="90" y="25" width="35" height="20" fill="#faf9f6"/><rect x="135" y="25" width="35" height="20" fill="#faf9f6"/></>}</svg><h3>{room}</h3><p className={s.muted}>{['Place at least the front legs of your seating on the rug. Tape the outline on the floor to check the fit.','Allow roughly 24 inches of rug beyond each side of the table so chairs stay on the rug when pulled out.','Leave a comfortable border beside and at the foot of the bed. Check door clearance and nightstand placement.'][i]}</p></div>)}</div><p className={s.notice}>Handmade sizes vary. Always use the exact measurements on the rug page, rather than its approximate size category.</p><a href="tel:+17034610207" className={s.btn}>Call for sizing help</a></ShoppingDialog>;}
export function shortlistUrl(ids:string[]) {return `${window.location.origin}/?view=shop&shortlist=${ids.map(encodeURIComponent).join(',')}`;}
export async function copyLink(url:string) {try{await navigator.clipboard.writeText(url);return true;}catch{return false;}}
