'use client';
import React,{useEffect,useMemo,useState} from 'react';
import {useStore} from '@/context/StoreContext';
import {Rug} from '@/types';
import {availableRugs,filterRugs,money,construction,relatedRugs,SHOP_SIZE_OPTIONS} from '@/lib/rug-discovery.mjs';
import {RugCard,ShoppingDialog,SizeGuide,shortlistUrl,copyLink} from './ShoppingTools';
import s from './Shopping.module.css';
const defaults={q:'',size:'',color:'',material:'',origin:'',construction:'',budget:'',sort:'featured'};
type Filters=typeof defaults;
export const ShopView=({onSelectRugId}:{onSelectRugId:(id:string)=>void})=>{
 const {publicRugs,favoritedRugIds}=useStore();
 const [filters,setFilters]=useState<Filters>(defaults),[ready,setReady]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[limit,setLimit]=useState(24),[savedOnly,setSavedOnly]=useState(false),[sharedIds,setSharedIds]=useState<string[]>([]),[compare,setCompare]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[guide,setGuide]=useState(false),[finder,setFinder]=useState(false),[room,setRoom]=useState(''),[notice,setNotice]=useState(''),[shareUrl,setShareUrl]=useState(''),[matchId,setMatchId]=useState('');
 useEffect(()=>{const p=new URLSearchParams(location.search);let stored:any={};try{if(!p.has('shortlist')&&!p.has('saved')&&!p.has('match')&&!Array.from(p.keys()).some(k=>k.startsWith('f_')))stored=JSON.parse(sessionStorage.getItem('mp_shop_filters_v2')||'{}');}catch{}const next={...defaults};for(const key of Object.keys(defaults) as (keyof Filters)[])next[key]=p.get('f_'+key)??(typeof stored[key]==='string'?stored[key]:'');next.sort=next.sort||'featured';setFilters(next);setSavedOnly(p.get('saved')==='1');setSharedIds((p.get('shortlist')||'').split(',').filter(id=>/^[a-zA-Z0-9_-]{1,100}$/.test(id)).slice(0,3));setMatchId(p.get('match')||'');setFinder(p.get('finder')==='1');setGuide(p.get('guide')==='1');setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{sessionStorage.setItem('mp_shop_filters_v2',JSON.stringify(filters));}catch{}setLimit(24);},[filters,savedOnly,sharedIds,ready]);
 const rugs=useMemo(()=>availableRugs(publicRugs) as Rug[],[publicRugs]);
 const results=useMemo(()=>{let list=filterRugs(rugs,filters) as Rug[];if(savedOnly)list=list.filter(r=>favoritedRugIds.includes(r.id));if(sharedIds.length)list=list.filter(r=>sharedIds.includes(r.id));if(matchId){const seed=publicRugs.find(r=>r.id===matchId);if(seed){const ranked=(relatedRugs(list,seed,{runnersOnly:true}) as Rug[]);list=ranked;}}if(filters.sort==='low')list.sort((a,b)=>a.price-b.price);if(filters.sort==='high')list.sort((a,b)=>b.price-a.price);return list;},[rugs,filters,savedOnly,sharedIds,favoritedRugIds,matchId,publicRugs]);
 const change=(key:keyof Filters,value:string)=>setFilters(f=>({...f,[key]:value}));
 const selected=compare.map(id=>rugs.find(r=>r.id===id)).filter(Boolean) as Rug[];
 const toggleCompare=(id:string)=>{if(!compare.includes(id)&&compare.length>=3){setNotice('You can compare up to three rugs. Remove one to add another.');return;}setNotice('');setCompare(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);};
 const share=async()=>{const url=shortlistUrl(selected.map(r=>r.id));setShareUrl(url);setNotice(await copyLink(url)?'Shortlist link copied.':'Copy the shortlist link below.');};
 const clear=()=>{setFilters(defaults);setSavedOnly(false);setSharedIds([]);setMatchId('');setNotice('');};
 const selectField=(label:string,key:keyof Filters,values:string[])=> <label className={s.field}>{label}<select value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">All {label.toLowerCase()}</option>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
 return <main className={s.shell}><div className={s.wrap}><div className={s.between}><div><span className={s.eyebrow}>Marco Polo Rugs · Since 1988</span><h1>Find your rug.</h1><p>Beautiful rugs, exact measurements and personal help from our Alexandria showroom.</p></div><div className={s.row}><button className={s.secondary} onClick={()=>setGuide(true)}>Size guide</button><button className={s.btn} onClick={()=>setFinder(true)}>Help me choose</button></div></div>
 <input type="search" className={s.search} aria-label="Search rugs" placeholder="Try 8x10, blue wool runner, a rug name or SKU…" value={filters.q} onChange={e=>change('q',e.target.value)}/>
 <div className={s.between} style={{marginTop:18}}><div className={s.row}><button className={s.secondary} onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen}>Filters {filtersOpen?'−':'+'}</button><button className={s.secondary} onClick={()=>setSavedOnly(v=>!v)} aria-pressed={savedOnly}>{savedOnly?'Showing saved rugs':'Saved rugs'}</button></div><label className={s.field}>Sort by<select value={filters.sort} onChange={e=>change('sort',e.target.value)}><option value="featured">Collection order</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>
 {filtersOpen&&<div className={s.filters}>{selectField('Sizes','size',SHOP_SIZE_OPTIONS)}<p className={s.muted}>Sizes are in feet. Size searches include rugs within 6 inches of each dimension. Check the exact measurements before choosing.</p>{selectField('Colors','color',['Red','Blue','Cream','Green','Gold','Navy','Ivory','Brown','Black'])}{selectField('Materials','material',['Wool','Silk','Cotton','Bamboo'])}{selectField('Origins','origin',Array.from(new Set(rugs.map((r:Rug)=>r.origin).filter(Boolean))).sort() as string[])}{selectField('Construction','construction',Array.from(new Set(rugs.map((r:Rug)=>construction(r)).filter(Boolean))).sort() as string[])}<label className={s.field}>Maximum price ($)<input type="number" min="0" step="50" placeholder="Any budget" value={filters.budget} onChange={e=>change('budget',e.target.value)}/></label><button className={s.secondary} onClick={clear}>Clear filters</button></div>}
 <div className={s.chips}>{(Object.keys(filters) as (keyof Filters)[]).filter(k=>k!=='sort'&&filters[k]).map(k=><button className={s.chip} key={k} onClick={()=>change(k,'')} aria-label={`Remove ${k} filter: ${filters[k]}`}>{k==='budget'?'Up to $':''}{filters[k]} ×</button>)}{sharedIds.length>0&&<button className={s.chip} onClick={()=>setSharedIds([])}>Shared shortlist ×</button>}{matchId&&<button className={s.chip} onClick={()=>setMatchId('')}>Coordinating runners ×</button>}</div>
 <div className={s.between}><p className={s.muted} role="status">{results.length} {results.length===1?'rug':'rugs'} available{savedOnly?' in your saved collection':''}</p><p className={s.muted}>Free padding with every rug</p></div>{notice&&<p role="status" className={s.notice}>{notice}</p>}
 {!results.length?<div className={s.empty}><h2>No rugs match just yet.</h2><p>{savedOnly?'Save a rug using its heart button to find it here.':'Try a different size, color or budget, or ask us for help.'}</p><button className={s.btn} onClick={clear}>Show all rugs</button> <a href="tel:+17034610207" className={s.secondary}>Call the showroom</a></div>:<div className={s.grid}>{results.slice(0,limit).map((r:Rug)=><RugCard key={r.id} rug={r} onSelect={onSelectRugId} compare={compare.includes(r.id)} onCompare={toggleCompare}/>)}</div>}
 {results.length>limit&&<div className={s.loadMore}><p className={s.muted}>Showing {Math.min(limit,results.length)} of {results.length}</p><button className={s.secondary} onClick={()=>setLimit(v=>v+24)}>Show 24 more rugs</button></div>}
 {selected.length>0&&<div className={`${s.toolbar} ${s.between}`}><span>{selected.length} of 3 rugs selected</span><div className={s.row}><button className={s.secondary} onClick={()=>setCompareOpen(true)}>Compare rugs</button><button className={s.secondary} onClick={()=>setCompare([])}>Clear</button></div></div>}
 {guide&&<SizeGuide onClose={()=>setGuide(false)}/>}
 {finder&&<ShoppingDialog title="Rug finder" onClose={()=>setFinder(false)}><span className={s.eyebrow}>A little guidance</span><h2>Let’s narrow it down.</h2><p>Tell us what you know. Leave anything undecided blank.</p><div className={s.filters}><label className={s.field}>Room<select value={room} onChange={e=>{setRoom(e.target.value);if(e.target.value==='Hallway')change('size','Runners');}}><option value="">Choose a room</option>{['Living room','Dining room','Bedroom','Hallway'].map(x=><option key={x}>{x}</option>)}</select></label>{selectField('Sizes','size',SHOP_SIZE_OPTIONS)}<p className={s.muted}>Sizes are in feet. Size searches include rugs within 6 inches of each dimension. Check the exact measurements before choosing.</p>{selectField('Colors','color',['Red','Blue','Cream','Green','Gold','Navy','Ivory','Brown'])}<label className={s.field}>Maximum budget ($)<input type="number" min="0" value={filters.budget} onChange={e=>change('budget',e.target.value)} placeholder="Any budget"/></label></div><p className={s.muted}>{room==='Dining room'?'Allow room for chairs to stay on the rug when pulled out.':room==='Bedroom'?'Measure the area beside and at the foot of your bed.':'Use exact rug dimensions to check your fit.'}</p><button className={s.btn} onClick={()=>{setFinder(false);setSavedOnly(false);setSharedIds([]);setMatchId('');}}>Show matching rugs</button></ShoppingDialog>}
 {compareOpen&&<ShoppingDialog title="Compare rugs" onClose={()=>setCompareOpen(false)}><span className={s.eyebrow}>Your shortlist</span><h2>Side by side.</h2><div className={s.scroll}><table className={s.compare}><caption className={s.muted}>Compare exact size, material and price before choosing.</caption><thead><tr>{selected.map(r=><th key={r.id}><img src={r.images?.[0]} alt={r.name}/><h3>{r.name}</h3><button className={s.secondary} onClick={()=>toggleCompare(r.id)}>Remove</button></th>)}</tr></thead><tbody>{[['Price',(r:Rug)=>money(r.price)],['Exact size',(r:Rug)=>r.dimensions],['Material',(r:Rug)=>r.material],['Origin',(r:Rug)=>r.origin],['Construction',(r:Rug)=>r.manufacturingType||r.construction],['Condition',(r:Rug)=>r.condition]].map(([label,read])=><tr key={String(label)}>{selected.map(r=><td key={r.id}><strong>{String(label)}</strong><br/>{(read as (r:Rug)=>string)(r)||'Ask our showroom'}</td>)}</tr>)}<tr>{selected.map(r=><td key={r.id}><button className={s.btn} onClick={()=>{setCompareOpen(false);onSelectRugId(r.id);}}>View rug</button></td>)}</tr></tbody></table></div><div className={s.row} style={{marginTop:24}}><button className={s.secondary} onClick={share}>Copy shortlist link</button><a className={s.btn} href={`/?view=book&rugs=${selected.map(r=>encodeURIComponent(r.id)).join(',')}`}>See these in the showroom</a></div>{shareUrl&&<label className={s.field}>Share this link<input readOnly value={shareUrl} onFocus={e=>e.target.select()}/></label>}{notice&&<p role="status">{notice}</p>}</ShoppingDialog>}
 </div></main>;
};
