import 'server-only';
import Stripe from 'stripe';
import {OWNER_UID} from '@/lib/access-policy';
import {NextResponse} from 'next/server';
import {caller,serverAuth,serverDb} from './firebase-admin';
import {check} from '@/lib/auction/engine.mjs';
import {auctionVisibility} from '@/lib/auction/visibility';
export const LIVE_CONFIG='auction_launch/current';
export function auctionStripe(){const key=process.env.STRIPE_AUCTION_LIVE_SECRET_KEY||'';check(key.startsWith('sk_live_'),'Auction live payment key is not configured.');return new Stripe(key,{maxNetworkRetries:0,timeout:5000});}
export function liveConfiguration(){return {publicKey:!!process.env.NEXT_PUBLIC_STRIPE_AUCTION_LIVE_PUBLISHABLE_KEY?.startsWith('pk_live_'),email:!!process.env.EMAILJS_PRIVATE_KEY&&!!process.env.EMAILJS_TEMPLATE_AUCTION_NOTICE,liveKey:!!process.env.STRIPE_AUCTION_LIVE_SECRET_KEY?.startsWith('sk_live_'),webhook:!!process.env.STRIPE_AUCTION_LIVE_WEBHOOK_SECRET?.startsWith('whsec_'),worker:(process.env.CRON_SECRET||process.env.AUCTION_CRON_SECRET||'').length>=32,enabled:process.env.MARCO_POLO_AUCTION_LIVE_ENABLED==='true'};}
export async function auctionLaunch(){const db=serverDb(),[d,v,w]=await Promise.all([db.doc(LIVE_CONFIG).get(),auctionVisibility(),db.doc('auction_worker_status/current').get()]);const config=d.data()||{},env=liveConfiguration();return {...config,pilotOnly:config.pilotOnly===true,pilotBuyerIds:Array.isArray(config.pilotBuyerIds)?config.pilotBuyerIds:[],env,open:v.mode==='open',biddingEnabled:w.data()?.lastSuccessAt>Date.now()-180000&&w.data()?.degraded!==true&&v.mode==='open'&&config.biddingEnabled===true&&Object.values(env).every(Boolean)&&config.legalReviewed===true&&config.providerApproved===true&&(config.endToEndTested===true||config.pilotOnly===true&&Array.isArray(config.pilotBuyerIds)&&config.pilotBuyerIds.length>0)&&config.workerVerified===true};}
export async function liveBuyer(req:Request){const claims=await caller(req);check(claims.email&&claims.firebase?.sign_in_provider!=='anonymous','SIGN_IN_REQUIRED');const u=await serverAuth().getUser(claims.uid);check(u.emailVerified,'Verify your email.');const role=await serverDb().doc('showroom_roles/'+u.uid).get();return {...u,staff:u.uid===OWNER_UID||role.data()?.active===true};}
export function auctionLiveError(e:any){const m=e instanceof Error?e.message:'';if(m==='SIGN_IN_REQUIRED'||/^auth\//.test(e?.code||''))return NextResponse.json({error:'Please sign in.'},{status:401});if(e?.type&&e.type.startsWith('Stripe'))return NextResponse.json({error:'Payment provider could not complete the request. No new payment should be attempted until its status is checked.'},{status:503});return NextResponse.json({error:m||'Auction request failed.'},{status:m==='FORBIDDEN'?403:400});}
export async function liveRequest(req:Request,max=18000){if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw Error('Use the auction website.');const raw=await req.text();check(raw.length<=max,'Request is too large.');return JSON.parse(raw);}
