import 'server-only';
import {serverDb} from './firebase-admin';
import {auctionStripe} from './auction-live';
import {check} from '@/lib/auction/engine.mjs';
import {LIVE_INVOICES} from '@/lib/auction/live-ledger.mjs';
export async function reconcileAuctionPayment(intent:any){
 check(intent?.livemode===true&&intent.metadata?.purpose==='marcopolo_auction_live'&&/^MPA-[a-f0-9]{24}$/.test(intent.metadata.invoiceId||''),'Invalid auction payment.');const db=serverDb(),ref=db.doc(LIVE_INVOICES+'/'+intent.metadata.invoiceId);
 await db.runTransaction(async tx=>{const d=await tx.get(ref),i=d.data()||{};check(d.exists&&i.mode==='live'&&i.paymentIntentId===intent.id&&i.total===intent.amount&&intent.currency==='usd'&&i.buyerId===intent.metadata.buyerId&&i.stripeCustomerId===intent.customer,'Payment does not match the invoice.');if(['paid','paid_review'].includes(i.paymentStatus))return;
 let status=intent.status==='succeeded'&&intent.amount_received===i.total?'paid':(intent.status==='requires_action'||intent.status==='requires_payment_method'&&intent.last_payment_error?.code==='authentication_required')?'requires_action':intent.status==='processing'?'processing':'declined';const rugRefs=i.items.map((item:any)=>db.doc('showroom_rugs/'+item.rugId)),rugs=status==='paid'?await tx.getAll(...rugRefs):[];const review=status==='paid'&&rugs.some((r:any,n:number)=>!r.exists||r.data()?.auctionLotId!==i.items[n].lotId||r.data()?.availability!=='Reserved');if(review)status='paid_review';const notice=db.doc('auction_notification_outbox/'+i.id+'-'+status),oldNotice=await tx.get(notice);
 tx.update(ref,{paymentStatus:status,paymentFailure:status==='declined'?'Your card was declined. Please update your card and contact the showroom.':status==='requires_action'?'Your bank requires payment verification.':review?'Payment received; inventory requires staff review before release.':'',updatedAt:Date.now(),version:i.version+1});
 if(status==='paid')rugRefs.forEach((r:any)=>tx.update(r,{availability:'Sold'}));if(!oldNotice.exists)tx.create(notice,{kind:status==='paid'?'receipt':'payment_issue',buyerId:i.buyerId,invoiceId:i.id,status:'pending',createdAt:Date.now()});});
}
export async function chargeAuctionInvoice(id:string){
 check(/^MPA-[a-f0-9]{24}$/.test(id),'Invalid invoice.');const db=serverDb(),ref=db.doc(LIVE_INVOICES+'/'+id),operation=db.doc('auction_live_charge_operations/'+id),stripe=auctionStripe();const invoice=(await ref.get()).data()||{};check(invoice?.mode==='live','Unknown live invoice.');if(invoice.paymentStatus==='paid'||invoice.paymentStatus==='paid_review')return {status:invoice.paymentStatus};
 if(invoice.paymentIntentId){const pi=await stripe.paymentIntents.retrieve(invoice.paymentIntentId);await reconcileAuctionPayment(pi);return {status:pi.status};}
 const card=(await db.doc('auction_live_cards/'+invoice.buyerId).get()).data()||{};check(card?.mode==='live'&&card.verified===true&&card.consent===true,'Buyer payment card needs verification.');
 const [pm,setup]=await Promise.all([stripe.paymentMethods.retrieve(card.paymentMethodId),stripe.setupIntents.retrieve(card.setupIntentId)]);check(pm.livemode&&pm.customer===card.customerId&&setup.livemode&&setup.status==='succeeded'&&setup.customer===card.customerId&&setup.payment_method===pm.id,'Card verification does not match.');
 await db.runTransaction(async tx=>{const [o,i,...rugs]=await tx.getAll(operation,ref,...invoice.items.map((item:any)=>db.doc('showroom_rugs/'+item.rugId)));check(!o.exists,'A charge is already being processed or requires review.');check(i.data()?.paymentStatus==='unpaid'&&!i.data()?.paymentIntentId,'Payment state changed.');rugs.forEach((r:any,n:number)=>check(r.data()?.availability==='Reserved'&&r.data()?.auctionLotId===invoice.items[n].lotId,'Inventory requires review before charging.'));tx.create(operation,{phase:'started',at:Date.now(),buyerId:invoice.buyerId,total:invoice.total,customerId:card.customerId});});
 try{const pi=await stripe.paymentIntents.create({amount:invoice.total,currency:'usd',customer:card.customerId,payment_method:card.paymentMethodId,metadata:{purpose:'marcopolo_auction_live',invoiceId:id,buyerId:invoice.buyerId},receipt_email:invoice.buyerEmail||undefined},{idempotencyKey:'auction-live-create-'+id});check(pi.livemode&&pi.amount===invoice.total&&pi.customer===card.customerId,'Invalid provider response.');
 await db.runTransaction(async tx=>{const [o,i]=await tx.getAll(operation,ref);check(o.data()?.phase==='started'&&!i.data()?.paymentIntentId,'Charge binding requires review.');tx.update(ref,{paymentIntentId:pi.id,stripeCustomerId:card.customerId,paymentStatus:'processing'});tx.update(operation,{phase:'bound',paymentIntentId:pi.id});});
 try{const confirmed=await stripe.paymentIntents.confirm(pi.id,{off_session:true},{idempotencyKey:'auction-live-confirm-'+id});await reconcileAuctionPayment(confirmed);}catch{await reconcileAuctionPayment(await stripe.paymentIntents.retrieve(pi.id));}return {paymentIntentId:pi.id,status:(await ref.get()).data()?.paymentStatus};
 }catch(e){await operation.set({phase:'needs_review',updatedAt:Date.now()},{merge:true});await ref.update({paymentStatus:'needs_review',paymentFailure:'Payment outcome requires staff review. No second payment will be created automatically.'});throw e;}
}
// Reuse the original intent; an uncertain attempt always requires reconciliation.
export async function retryAuctionInvoice(id:string){
 check(/^MPA-[a-f0-9]{24}$/.test(id),'Invalid invoice.');const db=serverDb(),ref=db.doc(LIVE_INVOICES+'/'+id),i=(await ref.get()).data()||{},stripe=auctionStripe();check(i.mode==='live'&&i.paymentIntentId&&i.paymentStatus==='declined','Only a declined invoice with a known payment can be retried.');
 const prior=await stripe.paymentIntents.retrieve(i.paymentIntentId);await reconcileAuctionPayment(prior);check(prior.status==='requires_payment_method','Check the existing payment before retrying.');const card=(await db.doc('auction_live_cards/'+i.buyerId).get()).data()||{};check(card.verified&&card.consent&&card.customerId===i.stripeCustomerId,'Update and verify your saved card.');const [pm,setup]=await Promise.all([stripe.paymentMethods.retrieve(card.paymentMethodId),stripe.setupIntents.retrieve(card.setupIntentId)]);check(pm.livemode&&pm.customer===i.stripeCustomerId&&setup.livemode&&setup.status==='succeeded'&&setup.payment_method===pm.id&&setup.customer===i.stripeCustomerId,'Card verification does not match.');
 let attempt=0;await db.runTransaction(async tx=>{const d=await tx.get(ref),v=d.data()||{};check(v.paymentStatus==='declined'&&v.paymentIntentId===prior.id&&!v.retryPending,'Payment retry is already pending; reconcile it first.');attempt=(v.retryAttempts||0)+1;check(attempt<=5,'Maximum retries reached; contact the showroom.');tx.update(ref,{retryPending:true,retryAttempts:attempt,updatedAt:Date.now()});});
 try{const pi=await stripe.paymentIntents.confirm(prior.id,{payment_method:pm.id,off_session:true},{idempotencyKey:'auction-live-retry-'+id+'-'+attempt});await reconcileAuctionPayment(pi);await ref.update({retryPending:false});return {status:pi.status};}catch(e){try{const pi=await stripe.paymentIntents.retrieve(prior.id);await reconcileAuctionPayment(pi);await ref.update({retryPending:false});return {status:pi.status};}catch{throw Error('Payment status is uncertain. Staff must reconcile the original payment before retrying.');}}
}
export async function recoverAuctionIntent(id:string,paymentIntentId:string){
 check(/^MPA-[a-f0-9]{24}$/.test(id)&&/^pi_[\w]+$/.test(paymentIntentId),'Invalid payment reference.');const db=serverDb(),ref=db.doc(LIVE_INVOICES+'/'+id),op=db.doc('auction_live_charge_operations/'+id),stripe=auctionStripe(),pi=await stripe.paymentIntents.retrieve(paymentIntentId);
 await db.runTransaction(async tx=>{const [d,o]=await tx.getAll(ref,op),i=d.data()||{},attempt=o.data()||{};check(i.mode==='live'&&!i.paymentIntentId&&['started','needs_review'].includes(attempt.phase),'This invoice does not need recovery.');check(pi.livemode&&pi.currency==='usd'&&pi.amount===i.total&&pi.customer===attempt.customerId&&pi.metadata.purpose==='marcopolo_auction_live'&&pi.metadata.invoiceId===id&&pi.metadata.buyerId===i.buyerId,'The provider payment does not match this invoice.');tx.update(ref,{paymentIntentId:pi.id,stripeCustomerId:pi.customer,paymentStatus:'processing'});tx.update(op,{phase:'bound',paymentIntentId:pi.id,recoveredAt:Date.now()});});
 // An unconfirmed intent is reconciled as declined; staff can retry that same intent.
 await reconcileAuctionPayment(pi);return {status:pi.status};
}
