import {createHash} from 'node:crypto';
import {withCompany,leftBehind,returnBy,workQueue,priorityInfo} from '../washing-priority.mjs';
import {intakeSettings,intakeItem,eligibleInvoice} from './washing-intake.mjs';
import {washingSummary} from '../washing-invoice.mjs';
export class WashError extends Error { constructor(message,status=400){super(message);this.status=status;this.existingId='';} }
export function text(value,max=500){if(typeof value!=='string'||value.length>max)throw new WashError('Please shorten the text and try again.');return value.trim();}
export function date(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new WashError('Choose a valid calendar date.');return value;}
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function tokenHash(token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))throw new WashError('This company link is invalid or disabled.',401);return createHash('sha256').update(token).digest('hex');}
export function schedule(input){const sentDate=date(input.sentDate),dueDate=date(input.dueDate),pickupDate=input.pickupDate?date(input.pickupDate):'';if(dueDate<sentDate)throw new WashError('Return date must be on or after the handoff date.');if(pickupDate&&dueDate>pickupDate)throw new WashError('Return date must be before the customer pickup date.');return {sentDate,dueDate,pickupDate};}
export function skuKey(sku){return sku.toUpperCase().replace(/^MPW0+(?=\d)/,'MPW');}
export function photo(value){return typeof value==='string'&&value.length<=250000&&(/^(https:\/\/)/.test(value)||/^data:image\/(jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(value))?value:'';}
export function invoiceRug(record,itemId){const data=record.data||record;if(data.documentType!=='WASH'&&data.mode!=='wash')throw new WashError('Select a wash invoice.');const item=data.items?.find(i=>i.id===itemId);if(!item||!/^MPW\d+$/i.test(item.sku||''))throw new WashError('This rug needs an MPW number on its saved wash invoice.');if(data.status==='picked_up')throw new WashError('This rug has already been collected by the customer.');return {sku:item.sku.toUpperCase(),description:text(item.description||'Rug',300),size:`${item.widthFeet||0}′ ${item.widthInches||0}″ × ${item.lengthFeet||0}′ ${item.lengthInches||0}″`,photo:photo(item.images?.[0]||item.image||''),customerName:text(data.soldTo?.name||'',120),invoiceNumber:text(data.invoiceNumber||'',100),conditions:item.conditions?Object.entries(item.conditions).filter(([,v])=>v).map(([k,v])=>k==='other'?String(v):k).join(', ').slice(0,500):'',pickupDate:data.pickupDate?date(data.pickupDate.slice(0,10)):''};}
export function vendorJob(job){const keys=['id','version','companyId','batch','batchId','createdAt','pickupBatchDate','startedAt','finishedAt','queueSkipped','returnBy','priority','alert','pickupRisk','missingPickup','manifestId','dispatchedAt','leftBehind','sku','description','size','photo','conditions','sentDate','dueDate','status','closed','acknowledgedAt','plannedDate','vendorNote','receivedDate','inspectionNote','issuePhoto','timing','updatedAt'];const shown=Object.fromEntries(keys.filter(k=>job[k]!==undefined).map(k=>[k,job[k]]));if(!withCompany(job))shown.pickupRisk=false;return shown;}
export function transition(job,action,input={},vendor=false,now=new Date().toISOString()){
 if(job.closed)throw new WashError('This rug is already checked and completed.',409);
 const note=text(input.note||'',500);
 if(vendor){
  if(!['acknowledge','start','ready','plan','delay'].includes(action))throw new WashError('Only showroom staff can receive or inspect rugs.',403);
  if(!['At company','Washing','Ready','Delivery planned','On the way'].includes(job.status))throw new WashError('This rug is currently at the showroom for inspection.',409);
  if(action==='acknowledge')return {acknowledgedAt:job.acknowledgedAt||now};
  if(action==='start'){if(!['At company','Washing'].includes(job.status))throw new WashError('This rug is already finished.',409);return {status:'Washing',startedAt:job.startedAt||now,vendorNote:note};}
  if(action==='ready'){if(!['At company','Washing','Ready'].includes(job.status))throw new WashError('Keep the saved delivery plan for this finished rug.',409);return {status:'Ready',finishedAt:job.finishedAt||now,vendorNote:note};}
  if(action==='plan'){const plannedDate=date(input.plannedDate);if(plannedDate<today())throw new WashError('Choose today or a future delivery date.');return {status:'Delivery planned',plannedDate,vendorNote:note};}
  if(!note)throw new WashError('Tell the showroom why the rug is delayed.');return {vendorNote:note};
 }
 if(action==='reference'){const reference=photo(input.photo);if(!reference)throw new WashError('Choose a valid rug photo.');return {photo:reference};}
 if(action==='reschedule')return {...schedule({...job,...input}),scheduleReason:note||'Schedule updated by showroom'};
 if(action==='receive'){
  if(!['At company','Washing','Ready','Delivery planned','On the way'].includes(job.status))throw new WashError('This rug has already been received.',409);
  if(String(input.confirmSku||'').trim().toUpperCase()!==job.sku)throw new WashError('The tag must match this MPW number. Report a wrong rug separately.');
  if(input.photoMatched!==true)throw new WashError('Confirm that the rug matches its photo or invoice description.');
  const receivedDate=date(input.receivedDate||today());if(receivedDate<job.sentDate||receivedDate>today())throw new WashError('Choose a return date between the handoff date and today.');
  return {status:'Needs inspection',receivedDate,timing:receivedDate<job.dueDate?'Early':receivedDate>job.dueDate?'Late':'On time',inspectionNote:note};
 }
 if(action==='accept'){if(job.status!=='Needs inspection'||input.clean!==true||input.conditionChecked!==true)throw new WashError('Check the cleaning and condition after receiving the correct rug.');return {status:'Checked & ready',closed:true,completedAt:now,inspectionNote:note};}
 if(action==='issue'){if(job.status!=='Needs inspection'||!note)throw new WashError('Receive the rug, then describe the cleaning or condition problem.');return {status:'Inspection issue',inspectionNote:note,issuePhoto:photo(input.photo||'')};}
 if(action==='rewash'){if(!['Inspection issue','Needs inspection'].includes(job.status))throw new WashError('Only an inspected return can be sent for correction.');return {...schedule(input),status:'At company',startedAt:'',finishedAt:'',queueSkipped:[],acknowledgedAt:'',plannedDate:'',vendorNote:'',inspectionNote:note,receivedDate:'',timing:'',correctionCount:(job.correctionCount||0)+1};}
 throw new WashError('Unknown action.');
}
export async function resolveCompanyLink(db,token){const hash=tokenHash(token),link=(await db.doc('wash_tracking_links/'+hash).get()).data();if(!link)throw new WashError('This company link is invalid or disabled.',401);const company=(await db.doc('wash_tracking_companies/'+link.companyId).get()).data();if(!company?.linkEnabled||company.linkHash!==hash)throw new WashError('This company link is invalid or disabled.',401);return link.companyId;}
export async function createHandoff(db,{companyId,dates,batch,prepared,requestId,fingerprint,uid,now}){
 const receipt=db.doc('wash_tracking_requests/'+createHash('sha256').update(uid+':'+requestId).digest('hex'));
 return db.runTransaction(async tx=>{const prior=await tx.get(receipt);if(prior.exists){if(prior.data()?.fingerprint!==fingerprint)throw new WashError('This handoff changed. Refresh and try again.',409);return prior.data()?.ids;}
  const company=await tx.get(db.doc('wash_tracking_companies/'+companyId));if(!company.exists||company.data().archived)throw new WashError('Company not found.',404);
  if(new Set(prepared.map(r=>skuKey(r.sku))).size!==prepared.length)throw new WashError('Duplicate MPW number in this handoff.');
  const locks=await Promise.all(prepared.map(r=>tx.get(db.doc('wash_tracking_active/'+skuKey(r.sku)))));locks.forEach((s,i)=>{if(s.exists)throw new WashError(prepared[i].sku+' is already being tracked. Finish its return before another handoff.',409);});
  const settingsByCollection=new Map();for(const r of prepared){if(r.invoiceCollection&&!settingsByCollection.has(r.invoiceCollection)){const settings=await tx.get(db.doc(intakeSettings(r.invoiceCollection)));settingsByCollection.set(r.invoiceCollection,settings.data());}}
  const itemReceipts=await Promise.all(prepared.map(r=>r.invoiceId?tx.get(db.doc(intakeItem(r.invoiceCollection,r.invoiceId,r.itemId))):Promise.resolve(null)));itemReceipts.forEach((sent,i)=>{if(sent?.exists)throw new WashError(prepared[i].sku+' has already been handed off. Use its existing service record.',409);});
  const batchId=receipt.id,refs=prepared.map(()=>db.collection('wash_tracking_jobs').doc()),invoices=new Map();
  for(const r of prepared){if(!r.invoiceId)continue;const path=r.invoiceCollection+'/'+r.invoiceId;if(!invoices.has(path)){const snapshot=await tx.get(db.doc(path));if(!snapshot.exists)throw new WashError('The source invoice is missing.',409);invoices.set(path,{ref:db.doc(path),record:snapshot.data(),data:snapshot.data().data||snapshot.data()});}const source=invoices.get(path),settings=settingsByCollection.get(r.invoiceCollection);if(source.data.washingProgress?.[r.itemId])throw new WashError(r.sku+' has already been handed off. Use its existing service record.',409);if(settings&&!eligibleInvoice(source.record,settings.cutoff))throw new WashError('Only new service rugs can be handed off. Older returned rugs remain in history.',409);const rug=invoiceRug(source.record,r.itemId);if(skuKey(rug.sku)!==skuKey(r.sku))throw new WashError('The invoice rug changed. Refresh this handoff.',409);}
  prepared.forEach((r,i)=>{if(!r.invoiceId)return;const source=invoices.get(r.invoiceCollection+'/'+r.invoiceId),item=source.data.items.find(item=>item.id===r.itemId);source.data={...source.data,washingProgress:{...(source.data.washingProgress||{}),[r.itemId]:{sku:item.sku.toUpperCase(),jobId:refs[i].id,status:'At company',updatedAt:now}}};});
  for(const source of invoices.values()){source.data.status=washingSummary(source.data).status;tx.update(source.ref,source.record.data?{data:source.data,updatedAt:new Date(now)}:{...source.data,updatedAt:new Date(now)});}
  const ids=[];prepared.forEach((r,i)=>{const ref=refs[i];ids.push(ref.id);const job={...r,...dates,pickupDate:r.pickupDate||dates.pickupDate,companyId,companyName:company.data()?.name,batch,batchId,pickupBatchDate:dates.sentDate,status:'At company',closed:false,version:1,createdAt:now,updatedAt:now,createdBy:uid};tx.create(ref,job);if(r.invoiceId)tx.create(db.doc(intakeItem(r.invoiceCollection,r.invoiceId,r.itemId)),{jobId:ref.id,companyId,sku:r.sku,handedOffAt:now});tx.create(db.doc('wash_tracking_active/'+skuKey(r.sku)),{jobId:ref.id});tx.create(ref.collection('history').doc(),{action:'Sent to company',by:uid,at:now,changes:{sentDate:job.sentDate,dueDate:job.dueDate}});});tx.create(receipt,{fingerprint,ids,at:now});return ids;
 });
}
export async function updateJob(db,{id,companyId='',vendor=false,uid,action,input,now}){const result=await updateJobs(db,{rugs:[{id,version:input.version}],companyId,vendor,uid,action,input,now});return result.updates[0];}
export async function updateJobs(db,{rugs,companyId='',vendor=false,uid,action,input={},now,operationId=''}){
 if(!Array.isArray(rugs)||!rugs.length||rugs.length>100||new Set(rugs.map(r=>r.id)).size!==rugs.length)throw new WashError('Choose between 1 and 100 different rugs.');
 if(rugs.some(r=>typeof r.id!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(r.id)))throw new WashError('Invalid rug record.');
 const receipt=operationId?db.doc('wash_tracking_bulk_requests/'+createHash('sha256').update(uid+':'+operationId).digest('hex')):null;
 const fingerprint=createHash('sha256').update(JSON.stringify({rugs,companyId,vendor,action,input})).digest('hex');
 return db.runTransaction(async tx=>{
  if(receipt){const prior=await tx.get(receipt);if(prior.exists){if(prior.data().fingerprint!==fingerprint)throw new WashError('This bulk request changed. Open a new action.',409);return {ids:prior.data().ids,updates:[],replayed:true};}}
  const snapshots=await Promise.all(rugs.map(r=>tx.get(db.doc('wash_tracking_jobs/'+r.id))));
  const records=snapshots.map((snapshot,i)=>{if(!snapshot.exists)throw new WashError('Rug not found.',404);const job=snapshot.data(),r=rugs[i];if(vendor&&job.companyId!==companyId)throw new WashError('Rug not found.',404);if(r.version!==job.version)throw new WashError(job.sku+' was updated. Refresh before continuing.',409);const fields={...input,...(input.checks?.[r.id]||{}),version:r.version};if(operationId&&action==='rewash')fields.pickupDate=job.pickupDate||'';const delegated=['acknowledge','start','ready','delay'].includes(action);let update;try{update=transition(job,action,fields,vendor||delegated,now);}catch(error){if(error instanceof WashError)error.message=job.sku+': '+error.message;throw error;}return {id:r.id,ref:db.doc('wash_tracking_jobs/'+r.id),job,update};});
  if(['start','ready'].includes(action)){
   const companyIds=[...new Set(records.map(r=>r.job.companyId))],chosen=new Set(records.map(r=>r.id));
   for(const owner of companyIds){const all=await tx.get(db.collection('wash_tracking_jobs').where('companyId','==',owner).where('closed','==',false).limit(501));if(all.size>500)throw new WashError('Too many active rugs.',409);const queue=workQueue(all.docs.map(d=>({...d.data(),id:d.id,...priorityInfo(d.data(),today())})));for(const r of records.filter(r=>r.job.companyId===owner)){const rank=queue.findIndex(j=>j.id===r.id),skipped=rank>0?queue.slice(0,rank).filter(j=>!chosen.has(j.id)):[];if(skipped.length){if(input.priorityAcknowledged!==true||!text(input.note||'',500))throw new WashError('Earlier rugs need work first: '+skipped.map(j=>j.sku).slice(0,10).join(', ')+'. Acknowledge the warning and explain the change.',409);}r.update.queueSkipped=skipped.map(j=>j.sku);}}
  }
  const invoices=new Map(),sourceItems=new Set();
  if(!vendor&&['receive','accept','issue','rewash'].includes(action))for(const r of records){const job=r.job;if(!job.invoiceId)continue;
   if(!/^([a-zA-Z0-9_-]+_)?invoices$/.test(job.invoiceCollection||'')||!/^[a-zA-Z0-9_-]{1,100}$/.test(job.invoiceId))throw new WashError('Invalid saved invoice reference.',409);
   const path=job.invoiceCollection+'/'+job.invoiceId,itemKey=path+':'+job.itemId;if(sourceItems.has(itemKey))throw new WashError('Two selected jobs refer to the same invoice rug.',409);sourceItems.add(itemKey);
   if(!invoices.has(path)){const ref=db.doc(path),saved=await tx.get(ref);if(!saved.exists)throw new WashError('The source invoice is missing. Restore it before completing this rug.',409);const record=saved.data();invoices.set(path,{ref,record,data:record.data||record});}
   const invoice=invoices.get(path),data=invoice.data;invoiceRug(invoice.record,job.itemId);const item=data.items.find(i=>i.id===job.itemId);if(skuKey(item.sku)!==skuKey(job.sku))throw new WashError('The invoice MPW number changed. Check it before receiving this rug.',409);
   invoice.data={...data,washingProgress:{...(data.washingProgress||{}),[job.itemId]:{sku:item.sku.toUpperCase(),jobId:r.id,status:r.update.status,updatedAt:now,...(r.update.closed?{checkedAt:now}:{})}}};r.invoicePath=path;
  }
  for(const invoice of invoices.values()){invoice.summary=washingSummary(invoice.data);invoice.data.status=invoice.summary.status;}
  for(const r of records){if(r.invoicePath){const summary=invoices.get(r.invoicePath).summary;Object.assign(r.update,{invoiceReadyCount:summary.readyCount,invoiceRugCount:summary.total,invoiceStatus:summary.status});}tx.update(r.ref,{...r.update,version:r.job.version+1,updatedAt:now});if(r.update.closed)tx.delete(db.doc('wash_tracking_active/'+skuKey(r.job.sku)));tx.create(r.ref.collection('history').doc(),{action,by:uid,at:now,changes:r.update,...(operationId?{bulkRequestId:operationId}:{})});}
  for(const invoice of invoices.values())tx.update(invoice.ref,invoice.record.data?{data:invoice.data,updatedAt:new Date(now)}:{...invoice.data,updatedAt:new Date(now)});
  const ids=records.map(r=>r.id);if(receipt)tx.create(receipt,{fingerprint,ids,by:uid,at:now});return {ids,updates:records.map(r=>r.update),replayed:false};
 });
}
export function companyKey(name){return text(name,120).normalize('NFKC').toLocaleLowerCase('en-US').replace(/\s+/g,' ').trim();}
export async function addCompany(db,name,uid,now){const key=companyKey(name);if(!key)throw new WashError('Enter the washing company name.');const registry=db.doc('wash_tracking_company_names/'+createHash('sha256').update(key).digest('hex')),ref=db.collection('wash_tracking_companies').doc();return db.runTransaction(async tx=>{await tx.get(registry);const all=await tx.get(db.collection('wash_tracking_companies').limit(501));if(all.size>500)throw new WashError('Company limit reached.',409);const found=all.docs.find(s=>!s.data().archived&&companyKey(s.data().name)===key);if(found){const e=new WashError('Company already added.',409);e.existingId=found.id;throw e;}tx.create(ref,{name:text(name,120),nameKey:key,linkEnabled:false,createdAt:now,createdBy:uid});tx.set(registry,{companyId:ref.id});return ref.id;});}
export async function mergeCompanies(db,targetId,duplicateIds,uid,now){return db.runTransaction(async tx=>{
 const target=await tx.get(db.doc('wash_tracking_companies/'+targetId)),duplicates=await Promise.all(duplicateIds.map(id=>tx.get(db.doc('wash_tracking_companies/'+id))));if(!target.exists||target.data().archived)throw new WashError('Company not found.',404);
 const same=duplicates.filter(d=>d.exists&&!d.data().archived);if(same.some(d=>companyKey(d.data().name)!==companyKey(target.data().name)))throw new WashError('Only identical company names can be merged.');
 const snapshots=[];for(const dup of same){const [jobs,reports,deliveries]=await Promise.all([tx.get(db.collection('wash_tracking_jobs').where('companyId','==',dup.id).limit(401)),tx.get(db.collection('wash_tracking_exceptions').where('companyId','==',dup.id).limit(401)),tx.get(db.collection('wash_tracking_deliveries').where('companyId','==',dup.id).limit(401))]);snapshots.push({dup,jobs,reports,deliveries});}
 if(snapshots.reduce((n,x)=>n+x.jobs.size+x.reports.size+x.deliveries.size+3,0)>450)throw new WashError('Too many records for an automatic merge. No records were removed.',409);
 for(const {dup,jobs,reports,deliveries} of snapshots){for(const j of jobs.docs)tx.update(db.doc('wash_tracking_jobs/'+j.id),{companyId:targetId,companyName:target.data().name,version:(j.data().version||0)+1,updatedAt:now});for(const r of reports.docs)tx.update(db.doc('wash_tracking_exceptions/'+r.id),{companyId:targetId,companyName:target.data().name});for(const delivery of deliveries.docs)tx.update(db.doc('wash_tracking_deliveries/'+delivery.id),{companyId:targetId});tx.delete(db.doc('wash_tracking_link_secrets/'+dup.id));if(dup.data().linkHash)tx.delete(db.doc('wash_tracking_links/'+dup.data().linkHash));tx.update(db.doc('wash_tracking_companies/'+dup.id),{archived:true,mergedInto:targetId,linkEnabled:false,linkHash:'',updatedAt:now});tx.create(db.doc('wash_tracking_companies/'+targetId).collection('history').doc(),{action:'Duplicate company merged',duplicateId:dup.id,by:uid,at:now});}
 tx.set(db.doc('wash_tracking_company_names/'+createHash('sha256').update(companyKey(target.data().name)).digest('hex')),{companyId:targetId});return same.map(d=>d.id);
 });}
export async function cleanupCompanies(db,uid,now){const all=await db.collection('wash_tracking_companies').limit(501).get();if(all.size>500)throw new WashError('Company limit reached.',409);const groups=new Map();for(const s of all.docs){const d=s.data();if(d.archived)continue;const key=companyKey(d.name);if(!groups.has(key))groups.set(key,[]);groups.get(key).push({id:s.id,...d});}const mapping={};for(const group of groups.values()){if(group.length<2)continue;group.sort((a,b)=>Number(b.linkEnabled===true)-Number(a.linkEnabled===true)||String(a.createdAt||'').localeCompare(String(b.createdAt||''))||a.id.localeCompare(b.id));const ids=await mergeCompanies(db,group[0].id,group.slice(1).map(d=>d.id),uid,now);for(const id of ids)mapping[id]=group[0].id;}return mapping;}
export async function archiveCompany(db,id,uid,now){return db.runTransaction(async tx=>{const ref=db.doc('wash_tracking_companies/'+id),s=await tx.get(ref),active=await tx.get(db.collection('wash_tracking_jobs').where('companyId','==',id).where('closed','==',false).limit(1));if(!s.exists)throw new WashError('Company not found.',404);if(active.size)throw new WashError('Receive or transfer all outstanding rugs before removing this company.',409);tx.delete(db.doc('wash_tracking_link_secrets/'+id));if(s.data().linkHash)tx.delete(db.doc('wash_tracking_links/'+s.data().linkHash));tx.update(ref,{archived:true,linkEnabled:false,linkHash:'',updatedAt:now});tx.create(ref.collection('history').doc(),{action:'Company removed from active list',by:uid,at:now});});}
export async function planReturns(db,{companyId,rugs,plannedDate,acknowledged=false,note='',dispatch=false,loadedChecked=false,uid,now,operationId=''}){
 if(dispatch&&!loadedChecked)throw new WashError('Confirm the MPW tags of the rugs loaded for departure.');const deliveryDate=dispatch?today():date(plannedDate);if(deliveryDate<today())throw new WashError('Choose today or a future delivery date.');if(!Array.isArray(rugs)||!rugs.length||rugs.length>100||new Set(rugs.map(r=>r.id)).size!==rugs.length)throw new WashError('Choose between 1 and 100 different rugs.');
 const receipt=operationId?db.doc('wash_tracking_bulk_requests/'+createHash('sha256').update(uid+':'+operationId).digest('hex')):null,fingerprint=createHash('sha256').update(JSON.stringify({companyId,rugs,deliveryDate,acknowledged,note,dispatch,loadedChecked})).digest('hex');
 return db.runTransaction(async tx=>{if(receipt){const prior=await tx.get(receipt);if(prior.exists){if(prior.data().fingerprint!==fingerprint)throw new WashError('This bulk delivery request changed. Open a new action.',409);return prior.data().result;}}const all=await tx.get(db.collection('wash_tracking_jobs').where('companyId','==',companyId).where('closed','==',false).limit(501));if(all.size>500)throw new WashError('Too many active rugs.',409);const records=all.docs.map(s=>({...s.data(),id:s.id})),selected=rugs.map(r=>{const j=records.find(j=>j.id===r.id);if(!j)throw new WashError('Rug not found.',404);if(j.version!==r.version)throw new WashError('This rug was updated. Refresh before continuing.',409);if(deliveryDate<j.sentDate)throw new WashError('Delivery cannot be before the handoff date.');if(!withCompany(j))throw new WashError('This rug is at the showroom.',409);if(dispatch&&!j.plannedDate)throw new WashError('Mark the rugs and save a delivery plan before departure.');return j;});
 const behind=leftBehind(records,selected,deliveryDate,today()),late=selected.filter(j=>returnBy(j)<deliveryDate),explanation=text(note,500);if((behind.length||late.length)&&(!acknowledged||!explanation))throw new WashError((behind.length?'Earlier rugs left behind: '+behind.map(j=>j.sku).slice(0,8).join(', ')+'. ':'')+(late.length?'Return deadline missed for: '+late.map(j=>j.sku).join(', ')+'. ':'')+'Acknowledge the priority warning and explain the delay.',409);
 const manifest=db.collection('wash_tracking_deliveries').doc();const changes={status:dispatch?'On the way':'Delivery planned',plannedDate:deliveryDate,manifestId:manifest.id,vendorNote:explanation,priorityAcknowledged:behind.length>0||late.length>0,leftBehind:behind.map(j=>j.sku),...(dispatch?{dispatchedAt:now}:{})};
 for(const j of selected){const ref=db.doc('wash_tracking_jobs/'+j.id);tx.update(ref,{...changes,version:j.version+1,updatedAt:now});tx.create(ref.collection('history').doc(),{action:dispatch?'Company departure confirmed':'Company delivery planned',by:uid,at:now,changes});}
 tx.create(manifest,{companyId,plannedDate:deliveryDate,dispatched:dispatch,rugs:selected.map(j=>({id:j.id,sku:j.sku})),leftBehind:behind.map(j=>j.sku),note:explanation,createdAt:now,createdBy:uid});const result={manifestId:manifest.id,leftBehind:behind.map(j=>j.sku)};if(receipt)tx.create(receipt,{fingerprint,result,by:uid,at:now});return result;
 });
}
