import {createHash} from 'node:crypto';
import {WashError,invoiceRug,skuKey,tokenHash} from './washing.mjs';
// Nazif confirmed that all unassigned older rugs have already returned.
export const INTAKE_START='2026-10-01T16:30:47.000Z';
export const intakeSettings=col=>'wash_tracking_settings/intake_'+createHash('sha256').update(col).digest('hex');
export const intakeItem=(col,invoiceId,itemId)=>'wash_tracking_intake_items/'+createHash('sha256').update([col,invoiceId,itemId].join(':')).digest('hex');
export function createdTime(value){if(value?.toDate)return value.toDate().toISOString();if(value instanceof Date)return value.toISOString();if(typeof value==='string'&&Number.isFinite(Date.parse(value)))return new Date(value).toISOString();if(typeof value?.seconds==='number')return new Date(value.seconds*1000).toISOString();return '';}
export function eligibleInvoice(record,cutoff){const data=record.data||record;return (data.documentType==='WASH'||data.mode==='wash')&&!data.isDraft&&!['ready','picked_up'].includes(data.status)&&createdTime(record.createdAt)>cutoff;}
export async function initializeIntake(db,col,uid,now){const ref=db.doc(intakeSettings(col));return db.runTransaction(async tx=>{const s=await tx.get(ref);if(s.exists)return s.data();const settings={cutoff:INTAKE_START,createdAt:now,createdBy:uid,reason:'Existing unassigned rugs already returned; new service intake begins here.'};tx.create(ref,settings);return settings;});}
export async function handoffCandidates(db,col){const settings=(await db.doc(intakeSettings(col)).get()).data();if(!settings)throw new WashError('Open Washing Tracker with a manager account to initialize new service intake.',409);const candidates=[];let cursor;
 for(;;){let query=db.collection(col).limit(200);if(cursor)query=query.startAfter(cursor);const page=await query.get();for(const snapshot of page.docs){const record=snapshot.data(),data=record.data||record;if(!eligibleInvoice(record,settings.cutoff))continue;for(const item of data.items||[]){if(!/^MPW\d+$/i.test(item.sku||'')||data.washingProgress?.[item.id])continue;const [active,sent]=await Promise.all([db.doc('wash_tracking_active/'+skuKey(item.sku)).get(),db.doc(intakeItem(col,snapshot.id,item.id)).get()]);if(active.exists||sent.exists)continue;const rug=invoiceRug(record,item.id);candidates.push({key:snapshot.id+':'+item.id,invoiceId:snapshot.id,itemId:item.id,sku:rug.sku,description:rug.description,customer:rug.customerName,pickup:rug.pickupDate,photo:rug.photo});}}if(page.size<200)break;cursor=page.docs.at(-1);}
 return {candidates,cutoff:settings.cutoff};
}
export async function rememberLink(db,companyId,token){const hash=tokenHash(token);return db.runTransaction(async tx=>{const company=await tx.get(db.doc('wash_tracking_companies/'+companyId));if(!company.exists||company.data().archived||!company.data().linkEnabled||company.data().linkHash!==hash)throw new WashError('This link is not the active link for this company.',409);tx.set(db.doc('wash_tracking_link_secrets/'+companyId),{token,hash});});}
export async function savedLink(db,companyId){const [company,secret]=await Promise.all([db.doc('wash_tracking_companies/'+companyId).get(),db.doc('wash_tracking_link_secrets/'+companyId).get()]);const c=company.data(),s=secret.data();if(!c||c.archived||!c.linkEnabled)return '';return s?.hash===c.linkHash&&tokenHash(s.token)===c.linkHash?s.token:'';}
