'use client';
import {useMemo,useState} from 'react';
import {stockRows,unsoldRow,stockPrint,stockExcelRows} from '@/lib/stock-check.mjs';
import styles from './StockCheck.module.css';
export default function StockCheck({items,source,loading=false}:{items:any[];source:string;loading?:boolean}){
 const [open,setOpen]=useState(false),[scope,setScope]=useState('unsold'),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const all=useMemo(()=>stockRows(items,source),[items,source]);
 const rows=all.filter((r:any)=>(scope==='all'||unsoldRow(r))&&[r.sku,r.name,r.size,r.location,r.material].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
 const skus=rows.map((r:any)=>r.sku.trim().toLowerCase()).filter(Boolean),duplicates=skus.length-new Set(skus).size;
 function print(){setError('');const win=window.open('','_blank');if(!win){setError('Allow pop-ups to open the printable checklist.');return;}win.opener=null;win.document.open();win.document.write(stockPrint(rows,source,new Date().toLocaleString('en-US')));win.document.close();const button=win.document.getElementById('print');if(button)button.onclick=()=>win.print();}
 async function excel(){setBusy(true);setError('');try{const x=await import('xlsx'),wb=x.utils.book_new(),sheet=x.utils.json_to_sheet(stockExcelRows(rows));sheet['!cols']=[{wch:6},{wch:16},{wch:36},{wch:22},{wch:18},{wch:16},{wch:23},...Array.from({length:6},()=>({wch:18})),{wch:45},{wch:30},{wch:26}];x.utils.book_append_sheet(wb,sheet,'Stock checklist');x.utils.book_append_sheet(wb,x.utils.aoa_to_sheet([['Marco Polo Rugs — stock check'],['Inventory',source],['Snapshot',new Date().toISOString()],['Rows',rows.length],['Instructions','Mark Found, Missing or Sold in person, add invoice and initials, then update the existing inventory record after verification.'],['Scope',scope==='all'?'All statuses':'Unsold rugs'],['Search',search]]),'Instructions');x.writeFile(wb,'Marco-Polo-stock-check-'+new Date().toISOString().slice(0,10)+'.xlsx');}catch{setError('Download failed. Please retry.');}finally{setBusy(false);}}
 return <div className={styles.wrap}><button type="button" className={styles.launch} onClick={()=>setOpen(!open)} aria-expanded={open}>Stock check: Print / Excel</button>{open&&<section className={styles.panel}><h3>Physical inventory checklist</h3><p>Walk through the store and check each SKU. This list includes all matching records, across every page. Keep the completed sheet and update verified sold rugs in inventory. For rugs listed online, also set the website listing to Sold.</p><div className={styles.controls}><label>Include<select value={scope} onChange={e=>setScope(e.target.value)}><option value="unsold">Unsold rugs — includes holds and service</option><option value="all">All rugs, including sold</option></select></label><label>Find SKU, name or location<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Leave blank for the complete list"/></label></div><p><strong>{rows.length} rugs</strong> · {source}</p>{duplicates>0&&<p role="status">{duplicates} duplicate SKU entries: use the photo and record ID to identify each rug.</p>}<div className={styles.actions}><button type="button" disabled={loading||!rows.length} onClick={print}>Print / Save PDF</button><button type="button" disabled={loading||busy||!rows.length} onClick={()=>void excel()}>{busy?'Preparing…':'Download Excel checklist'}</button></div>{loading&&<p>Loading inventory…</p>}{error&&<p role="alert">{error}</p>}</section>}</div>;
}
