import {chromium} from '@playwright/test';
import {initializeApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {randomBytes} from 'node:crypto';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const projectId='demo-marcopolo-access';
if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST)throw Error('Test emulators are required');
initializeApp({projectId});
const auth=getAuth(),db=getFirestore();
const password=randomBytes(24).toString('base64url');
const owner=await auth.createUser({uid:'msQJKLOsWceWK5A75V6ZBLQRvsl2',email:'marcopolo783152@gmail.com',password,emailVerified:true,displayName:'Nazif'});
const customer=await auth.createUser({uid:'test-customer',email:'customer@example.com',password,emailVerified:true,displayName:'Ava'});
const manager=await auth.createUser({uid:'test-manager',email:'manager@example.com',password,emailVerified:true,displayName:'Test Manager'});
await db.doc('showroom_roles/'+owner.uid).set({email:owner.email,role:'admin',active:true,name:'Nazif',permissions:{}});
await db.doc('showroom_roles/'+manager.uid).set({email:manager.email,role:'general_manager',active:true,name:'Test Manager',permissions:{}});
await db.doc('showroom_customers/'+customer.uid).set({name:'Ava',email:customer.email,phone:'',address:''});
await db.doc('showroom_orders/test-order').set({id:'test-order',customerId:customer.uid,customerInfo:{name:'Ava',email:customer.email},status:'Pending Confirmation',createdAt:new Date().toISOString(),cartItems:[],total:250});
await mkdir('screenshots',{recursive:true});
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-p','3000'],{cwd:'../..',env:{...process.env,FIREBASE_PROJECT_ID:projectId},stdio:['ignore','pipe','pipe']});
server.stdout.on('data',()=>{});server.stderr.on('data',chunk=>{const str=chunk.toString();if(/Error/.test(str))console.error(str.slice(0,1000));});
let browser;
try{
 for(let i=0;i<60;i++){try{if((await fetch('http://127.0.0.1:3000/sign-in')).ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}
 browser=await chromium.launch({headless:true});
 const staffContext=await browser.newContext({viewport:{width:1440,height:960}});
 const staffPage=await staffContext.newPage();
 await staffPage.goto('http://127.0.0.1:3000/staff-login');
 await staffPage.getByLabel('Email',{exact:true}).fill(owner.email);
 await staffPage.getByLabel('Password',{exact:true}).fill(password);
 await staffPage.getByRole('button',{name:'Sign in',exact:true}).click();
 await staffPage.getByRole('heading',{name:'Showroom overview',exact:true}).waitFor({timeout:30000});
 const top=await staffPage.locator('main').first().boundingBox();
 assert.ok(top && top.y<180,'Admin content begins next to the sidebar, near the top');
 await staffPage.screenshot({path:'screenshots/admin-desktop.png',fullPage:true});
 await staffPage.setViewportSize({width:390,height:844});
 await staffPage.getByRole('button',{name:'Dashboard menu'}).click();
 assert.ok(await staffPage.getByRole('button',{name:'Inventory',exact:true}).isVisible());
 assert.ok(await staffPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Admin mobile has no horizontal page overflow');
 await staffPage.screenshot({path:'screenshots/admin-mobile.png',fullPage:true});
 await staffPage.setViewportSize({width:1440,height:960});
 const context=await browser.newContext({viewport:{width:1440,height:960}});
 const page=await context.newPage();
 await page.goto('http://127.0.0.1:3000/sign-in');
 await page.getByRole('link',{name:'Forgot password?',exact:true}).click();
 await page.getByRole('heading',{name:'Reset your password.'}).waitFor();
 await page.getByLabel('Account email / username').fill(customer.email);
 await page.getByRole('button',{name:'Send reset link'}).click();
 await page.getByRole('status').filter({hasText:'If an account uses this email'}).waitFor();
 await page.screenshot({path:'screenshots/password-reset.png',fullPage:true});
 await page.goto('http://127.0.0.1:3000/sign-in');
 await page.getByRole('button',{name:'New customer? Create an account'}).click();
 const newEmail='verify-'+Date.now()+'@example.com';
 await page.getByLabel('Full name',{exact:true}).fill('New Customer');
 await page.getByLabel('Email address',{exact:true}).fill(newEmail);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Create customer account',exact:true}).click();
 await page.getByRole('heading',{name:'Check your inbox.'}).waitFor({timeout:20000});
 await page.goto('http://127.0.0.1:3000/account');
 await page.getByRole('heading',{name:'Check your inbox.'}).waitFor();
 const codes=await (await fetch('http://127.0.0.1:9099/emulator/v1/projects/'+projectId+'/oobCodes')).json();
 const code=codes.oobCodes.find(c=>c.email===newEmail&&c.requestType==='VERIFY_EMAIL');
 assert.ok(code,'Registration requested a verification email');
 const verified=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:update?key=test-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({oobCode:code.oobCode})});
 assert.equal(verified.status,200);
 await page.getByRole('button',{name:'I’ve verified my email'}).click();
 await page.getByRole('heading',{name:'Your collection, your space.'}).waitFor({timeout:20000});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByLabel('Email address',{exact:true}).fill(customer.email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('heading',{name:'Your collection, your space.'}).waitFor({timeout:20000});
 await page.getByText('test-order',{exact:true}).waitFor();
 await page.screenshot({path:'screenshots/customer-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Customer mobile has no horizontal overflow');
 await page.screenshot({path:'screenshots/customer-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Chat with us',exact:true}).click();
 const chat=page.getByRole('dialog',{name:'Marco Polo customer support'});
 await chat.getByLabel('Your message').fill('Hi');
 await chat.getByRole('button',{name:'Send',exact:true}).click();
 await chat.getByText(/I’m Cyrus, your AI showroom assistant/).waitFor({timeout:30000});
 await chat.getByRole('button',{name:'Talk to our team'}).click();
 await chat.getByLabel('Full name',{exact:true}).fill('Ava Customer');
 await chat.getByLabel('Email',{exact:true}).fill(customer.email);
 await chat.getByLabel('Phone',{exact:true}).fill('7035550100');
 await chat.getByRole('button',{name:'Send request to team'}).click();
 await chat.getByText(/Your request is in the team’s inbox/).waitFor({timeout:20000});
 await staffPage.goto('http://127.0.0.1:3000/?view=admin&adminTab=messages');
 await staffPage.locator('main').getByRole('button',{name:/(Ava|Customer).*Open/}).click({timeout:30000});
 const staffChat=staffPage.locator('main').getByLabel('Customer conversation');
 await staffChat.getByLabel('Your name for this customer').fill('Nazif');
 await staffChat.getByRole('button',{name:'Accept conversation'}).click();
 await chat.getByText(/Nazif from our showroom team has joined/).waitFor({timeout:20000});
 await staffChat.getByLabel('Reply to customer').fill('Hello Ava, I’m happy to help with your rug.');
 await staffChat.getByRole('button',{name:'Send',exact:true}).click();
 await chat.getByText('Hello Ava, I’m happy to help with your rug.',{exact:true}).waitFor();
 await page.screenshot({path:'screenshots/customer-live-chat.png',fullPage:true});
 const tokenFor=async email=>{
  const response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=test-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});
  return (await response.json()).idToken;
 };
 const post=async(token,body)=>fetch('http://127.0.0.1:3000/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});
 const managerToken=await tokenFor(manager.email),customerToken=await tokenFor(customer.email);
 assert.equal((await post(managerToken,{action:'claim',sessionId:'user-'+customer.uid,name:'Other Manager'})).status,403,'Second employee cannot take an accepted chat');
 assert.equal((await post(customerToken,{action:'reply',sessionId:'user-'+customer.uid,text:'Pretend staff'})).status,403,'Customer cannot impersonate staff');
 assert.equal((await post(managerToken,{action:'message',sessionId:'user-'+customer.uid,text:'Read another chat'})).status,403,'Customer operation cannot access another owner’s session');
 console.log('BROWSER_CHECKS_PASSED: admin desktop/mobile layout; reset page/email; verification gate; customer dashboard desktop/mobile; greeting fallback; contact handoff; named staff acceptance/reply; second-claim and impersonation protection.');
}finally{await browser?.close();server.kill('SIGTERM');}
