import test from 'node:test';import assert from 'node:assert/strict';import {customerInvoice,tokenHash} from '../../lib/server/invoice-share.mjs';
test('invoice links require unguessable tokens, not invoice IDs',()=>{assert.throws(()=>tokenHash('invoice123'));assert.throws(()=>tokenHash(null));assert.equal(tokenHash('a'.repeat(64)).length,64);assert.notEqual(tokenHash('a'.repeat(64)),tokenHash('b'.repeat(64)));});
test('customer invoice projection excludes costs, warehouse and internal payment metadata',()=>{
 const view=customerInvoice({invoiceNumber:'123',items:[{sku:'A',fixedPrice:100,importCost:10,totalCost:20,zone:'vault',secret:'hidden'}],soldTo:{name:'Test',internalFlag:true},payments:[{amount:50,date:'2026-09-29',reference:'private',note:'staff-only'}],internalNotes:'private'});
 assert.equal(view.items[0].fixedPrice,100);for(const k of ['importCost','totalCost','zone','secret'])assert.equal(view.items[0][k],undefined);assert.equal(view.payments[0].reference,undefined);assert.equal(view.soldTo.internalFlag,undefined);assert.equal(view.internalNotes,undefined);
});

import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import * as sharing from '../../lib/server/invoice-share.mjs';
import {washingSummary} from '../../lib/washing-invoice.mjs';
const require=createRequire(import.meta.url),token='a'.repeat(64),invoice={invoiceNumber:'W55',documentType:'WASH',items:[{id:'r1',sku:'MPW1234',fixedPrice:50,importCost:2},{id:'r2',sku:'MPW2000',fixedPrice:60}],soldTo:{name:'Customer',email:'customer@example.test'},payments:[{amount:20,date:'2026-10-01',reference:'private'}],status:'washing',washingProgress:{r1:{sku:'MPW1234',status:'Checked & ready',jobId:'private-job'}},internalNotes:'private'};
function route(path,seed){const values=new Map(Object.entries(structuredClone(seed))),doc=p=>({get:async()=>({data:()=>values.get(p)}),create:async value=>{if(values.has(p))throw Error('Already exists');values.set(p,value);}}),db={collection:name=>({doc:id=>doc(name+'/'+id)})},exports={},code=require('typescript').transpileModule(readFileSync(new URL('../../'+path,import.meta.url),'utf8'),{compilerOptions:{module:require('typescript').ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{exports,URL,Date,Error,require(name){if(name==='node:crypto')return require(name);if(name==='@/lib/server/firebase-admin')return {serverDb:()=>db};if(name==='@/lib/server/invoice-share.mjs')return sharing;if(name==='@/lib/washing-invoice.mjs')return {washingSummary};if(name==='@/lib/server/live-payment')return {respond:(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}})};if(name==='@/lib/server/staff-permission')return {requireStaff:async req=>{if(req.headers.get('authorization')!=='Bearer staff')throw Error('FORBIDDEN');return {uid:'staff'};}};throw Error(name);}});return {api:exports,values};}
const publicSeed=()=>({['invoice_customer_links/'+tokenHash(token)]:{invoiceId:'private-doc-id',expiresAt:Date.now()+100000},'invoices/private-doc-id':{data:structuredClone(invoice)}});
test('anonymous customer opens secure wash tracker without Firestore access and sees only safe live progress',async()=>{const {api}=route('app/api/public/invoice/route.ts',publicSeed()),r=await api.GET(new Request('https://example.com/api/public/invoice?token='+token));assert.equal(r.status,200);const x=await r.json();assert.equal(x.invoice.data.mode,'wash');assert.equal(x.invoice.data.invoiceNumber,'W55');assert.deepEqual(x.serviceProgress,{readyCount:1,total:2});assert.equal(x.invoice.data.washingProgress,undefined);assert.equal(x.invoice.data.internalNotes,undefined);assert.equal(x.invoice.data.items[0].importCost,undefined);assert.equal(x.invoice.data.payments[0].reference,undefined);assert.equal(r.headers.get('Referrer-Policy'),'no-referrer');assert.match(r.headers.get('X-Robots-Tag'),/noindex/);});
test('raw IDs, revoked links, expired links and drafts never expose customer invoices',async()=>{for(const change of [{token:'private-doc-id'},{revoked:true},{expiresAt:Date.now()-1},{draft:true}]){const seed=publicSeed();if(change.revoked)seed['invoice_customer_links/'+tokenHash(token)].revoked=true;if(change.expiresAt)seed['invoice_customer_links/'+tokenHash(token)].expiresAt=change.expiresAt;if(change.draft)seed['invoices/private-doc-id'].data.isDraft=true;const {api}=route('app/api/public/invoice/route.ts',seed),r=await api.GET(new Request('https://example.com/api/public/invoice?token='+(change.token||token)));assert.equal(r.status,404);assert.equal((await r.json()).invoice,undefined);}});
test('staff tracking link issuance uses a fresh random capability and exact private invoice mapping',async()=>{const {api,values}=route('app/api/invoices/share/route.ts',{'invoices/private-doc-id':{data:invoice}}),r=await api.POST(new Request('https://example.com/api/invoices/share',{method:'POST',headers:{authorization:'Bearer staff'},body:JSON.stringify({id:'private-doc-id',view:'tracking'})}));assert.equal(r.status,200);const {url}=await r.json();assert.match(url,/\/tracking\/[a-f0-9]{64}$/);assert.equal(url.includes('private-doc-id'),false);const capability=url.split('/').at(-1);assert.equal(values.get('invoice_customer_links/'+tokenHash(capability)).invoiceId,'private-doc-id');assert.equal((await api.POST(new Request('https://example.com/api/invoices/share',{method:'POST',body:JSON.stringify({id:'private-doc-id',view:'tracking'})}))).status,403);});
test('invoice email and copied tracking actions no longer distribute raw document-ID URLs',()=>{const s=readFileSync(new URL('../../app/(admin)/admin/invoices/invoices/view/page.tsx',import.meta.url),'utf8'),tracker=readFileSync(new URL('../../components/public/InvoiceTracking.tsx',import.meta.url),'utf8');assert.equal(s.includes('/tracking/${invoice.id}'),false);assert.ok(s.includes("createCustomerInvoiceLink(invoice.id, 'tracking')"));assert.equal(tracker.includes('getInvoiceByIdAsync'),false);assert.ok(tracker.includes('/api/public/invoice?token='));});
