import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeUpsTracking,getUpsTracking} from '../../lib/server/ups-tracking.mjs';
import {safeTracking} from '../../lib/shipment-tracking.mjs';
const number='1Z123456';
const fixture=()=>({trackResponse:{shipment:[{package:[{trackingNumber:number,deliveryDate:[{type:'SDD',date:'20261012'}],deliveryTime:{type:'EDW',startTime:'091500',endTime:'131500'},packageAddress:[{address:{addressLine1:'private'}}],activity:[{date:'20261006',time:'180700',gmtDate:'20261006',gmtTime:'220700',status:{type:'P',description:'RFID Confirmed Pickup'},location:{address:{city:'Alexandria',stateProvince:'VA',countryCode:'US',postalCode:'private'}}},{date:'20261006',time:'171300',gmtOffset:'-04:00',status:{type:'M',description:'Label created'}}]}]}]}});
test('UPS pickup scan, history, delivery date and window are retained without private data',()=>{const result=normalizeUpsTracking(fixture(),number);assert.equal(result.source,'ups_direct');assert.equal(result.tracking_status.status,'TRANSIT');assert.equal(result.tracking_status.status_details,'RFID Confirmed Pickup');assert.equal(result.tracking_status.status_date,'2026-10-06T22:07:00Z');assert.equal(result.tracking_history[1].status_date,'2026-10-06T17:13:00-04:00');assert.equal(result.eta,'2026-10-12');assert.deepEqual(result.delivery_window,{start:'09:15:00',end:'13:15:00'});assert.equal(JSON.stringify(result).includes('private'),false);});
test('mismatched and suppressed UPS details are rejected',()=>{assert.throws(()=>normalizeUpsTracking(fixture(),'OTHER'));const raw=fixture();raw.trackResponse.shipment[0].package[0].suppressionIndicators=['DETAIL'];assert.throws(()=>normalizeUpsTracking(raw,number));});
test('newer history scan takes precedence over an outdated shipping summary',()=>{const r=safeTracking({tracking_status:{status:'PRE_TRANSIT',status_date:'2026-10-06T21:13:00Z'},tracking_history:[{status:'TRANSIT',status_date:'2026-10-06T22:07:00Z',status_details:'Picked up'}]});assert.equal(r.tracking_status.status,'TRANSIT');});
test('production UPS uses server OAuth, skips proof of delivery, and reuses an unexpired token',async()=>{const calls=[];const fetcher=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('/oauth/')?{access_token:'test-token',expires_in:3600}:fixture()};};for(let i=0;i<2;i++)await getUpsTracking(number,{clientId:'test-id',clientSecret:'test-secret',fetcher});assert.equal(calls.length,3);assert.equal(calls[0].options.body,'grant_type=client_credentials');assert.ok(calls[1].url.startsWith('https://onlinetools.ups.com/api/track/v1/details/'));assert.ok(calls[1].url.includes('returnPOD=false'));assert.equal(calls[1].options.headers.Authorization,'Bearer test-token');assert.equal(calls[1].options.cache,'no-store');});
