import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import * as helpers from '../../lib/server/washing-invoices.mjs';
import * as washing from '../../lib/server/washing.mjs';
const require=createRequire(import.meta.url);
const expected={key:'batch',companyName:'Good Wash',date:'2026-10-01',rugs:[{sku:'MPW0001234'},{sku:'MPW2000'}]};
const row=(sku,amount=10,quantity=1)=>({sku,description:'Rug',amount,quantity,uncertain:false});
const invoice=(rows=[row('MPW1234'),row('MPW2000')])=>({invoiceNumber:'V1',company:'Good Wash',invoiceDate:'2026-10-01',rows,total:rows.reduce((sum,r)=>sum+r.amount,0),tax:0,other:0,notes:''});
test('canonical customer identifiers match independently of leading zero aliases',()=>{const c=helpers.compareInvoice(expected,invoice());assert.equal(c.customerCount,2);assert.deepEqual(c.missing,[]);assert.deepEqual(c.extras,[]);assert.equal(c.amountMismatch,false);assert.equal(c.dateWarning,false);});
test('missing and duplicate rugs never cancel out just because quantity totals match',()=>{const e=invoice([row('MPW1234',20,2)]),c=helpers.compareInvoice(expected,e);assert.equal(c.customerCount,2);assert.deepEqual(c.missing,['MPW2000']);assert.deepEqual(c.duplicates,['MPW0001234']);assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:true}),/Resolve/);});
test('extra customer MPWs are not classified as store rugs, including malformed MPW tags',()=>{for(const sku of ['MPW3000','MPW20OO','MPW1234/2000']){const e=invoice([...invoice().rows,row(sku)]),c=helpers.compareInvoice(expected,e);assert.equal(c.wrongCustomer.length,1);assert.equal(c.extras.length,0);assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:true,storeRows:{2:true}}),/Resolve/);}});
test('each extra store rug line needs explicit staff confirmation',()=>{const e=invoice([...invoice().rows,row('MP100',20,2),row('',30)]),c=helpers.compareInvoice(expected,e);assert.equal(c.storeCount,3);assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:true,storeRows:{2:true}}),/each extra/);const checked=helpers.checkConfirmation(expected,e,{checked:true,storeRows:{2:true,3:true}});assert.deepEqual(checked.storeRows,{2:true,3:true});assert.equal(checked.comparison.customerCount,2);});
test('uncertain rows and invalid numbers cannot become checked',()=>{const e=invoice();e.rows[0].uncertain=true;assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:true}),/Resolve/);for(const quantity of [0,1.5,-1,201])assert.throws(()=>helpers.extraction(invoice([row('MPW1234',10,quantity)])),/quantity/);assert.throws(()=>helpers.extraction({...invoice(),total:-1}),/amounts/);assert.throws(()=>helpers.extraction({...invoice(),invoiceDate:'2026-02-30'}),/date/);});
test('invoice arithmetic uses line totals plus tax and other charges with cent tolerance',()=>{const e={...invoice(),total:23,tax:1,other:2};assert.equal(helpers.compareInvoice(expected,e).calculatedTotal,23);assert.equal(helpers.compareInvoice(expected,e).amountMismatch,false);assert.throws(()=>helpers.checkConfirmation(expected,{...e,total:30},{checked:true}),/Resolve/);});
test('date/company/incomplete amount warnings require explanation and original check',()=>{const e={...invoice(),company:'Different',invoiceDate:'',total:null};assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:true}),/Explain/);assert.throws(()=>helpers.checkConfirmation(expected,e,{checked:false,note:'Checked difference'}),/original/);assert.equal(helpers.checkConfirmation(expected,e,{checked:true,note:'Trading name; invoice date absent; prices checked on original.'}).confirmationNote.startsWith('Trading'),true);});
test('original file accepts bounded PDFs and images but rejects disguised files',()=>{const pdf=Buffer.from('%PDF-1.7 test');assert.equal(helpers.validateFile(pdf,'application/pdf'),'application/pdf');assert.throws(()=>helpers.validateFile(pdf,'image/png'),/valid/);assert.throws(()=>helpers.validateFile(Buffer.from('<script>'),'application/pdf'),/valid/);assert.throws(()=>helpers.validateFile(Buffer.alloc(3000001),'application/pdf'),/3 MB/);assert.throws(()=>helpers.validateFile(Buffer.alloc(0),'application/pdf'),/3 MB/);});
function db(seed={}){let values=new Map(Object.entries(structuredClone(seed))),counter=0,queue=Promise.resolve();const snap=p=>({id:p.split('/').at(-1),exists:values.has(p),data:()=>structuredClone(values.get(p))});const doc=p=>({path:p,id:p.split('/').at(-1),get:async()=>snap(p),collection:n=>col(p+'/'+n)});const col=(p,filters=[],limit=Infinity,after='')=>({query:true,path:p,filters,maximum:limit,after,doc:id=>doc(p+'/'+(id||'auto'+(++counter))),where:(k,op,v)=>col(p,[...filters,[k,v]],limit,after),limit:n=>col(p,filters,n,after),startAfter:s=>col(p,filters,limit,s.id),get:async()=>query({path:p,filters,maximum:limit,after})});const query=q=>{const docs=[...values.keys()].sort().filter(p=>p.startsWith(q.path+'/')&&!p.slice(q.path.length+1).includes('/')&&q.filters.every(([k,v])=>values.get(p)[k]===v)&&(!q.after||p.split('/').at(-1)>q.after)).slice(0,q.maximum).map(snap);return {docs,size:docs.length};};return {doc,collection:col,read:p=>structuredClone(values.get(p)),change:(p,v)=>values.set(p,{...values.get(p),...v}),all:()=>[...values.entries()],runTransaction(fn){const result=queue.then(async()=>{const before=structuredClone(values);let writing=false;const tx={get:async r=>{assert.equal(writing,false);return r.query?query(r):snap(r.path);},create:(r,v)=>{writing=true;assert.equal(values.has(r.path),false);values.set(r.path,structuredClone(v));},update:(r,v)=>{writing=true;assert.equal(values.has(r.path),true);values.set(r.path,{...values.get(r.path),...structuredClone(v)});}};try{return await fn(tx);}catch(e){values=before;throw e;}});queue=result.catch(()=>{});return result;}};}
const jobs={'wash_tracking_jobs/a':{companyId:'c',companyName:'Good Wash',batchId:'b1',batch:'Week one',sentDate:'2026-10-01',pickupBatchDate:'2026-10-01',sku:'MPW1234',closed:false},'wash_tracking_jobs/b':{companyId:'c',companyName:'Good Wash',batchId:'b1',batch:'Week one',sentDate:'2026-10-08',pickupBatchDate:'2026-10-01',sku:'MPW2000',closed:true},'wash_tracking_jobs/c':{companyId:'c',companyName:'Good Wash',batchId:'b2',sentDate:'2026-10-01',sku:'MPW3000'}};
test('entire immutable pickup includes returned/corrected rugs and excludes another same-day pickup',async()=>{const p=await helpers.pickup(db(jobs),'a');assert.deepEqual(p.rugs.map(r=>r.sku),['MPW1234','MPW2000']);assert.equal(p.date,'2026-10-01');assert.notEqual(p.key,(await helpers.pickup(db(jobs),'c')).key);});
test('legacy pickups are distinct by company/date/name/creation time',async()=>{const d=db({'wash_tracking_jobs/a':{...jobs['wash_tracking_jobs/a'],batchId:'',createdAt:'one'},'wash_tracking_jobs/b':{...jobs['wash_tracking_jobs/a'],batchId:'',createdAt:'two',sku:'MPW2000'}});assert.equal((await helpers.pickup(d,'a')).rugs.length,1);});
test('AI PDF/image payloads use structured extraction, no stored responses or customer record hints',async()=>{for(const type of ['application/pdf','image/jpeg']){let payload;const result=await helpers.readInvoice(Buffer.from('file'),type,'invoice',{key:'mock-key',fetcher:async(url,options)=>{payload=JSON.parse(options.body);assert.equal(url,'https://api.openai.com/v1/responses');return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(invoice())}]}]})};}});assert.equal(payload.store,false);assert.equal(payload.text.format.strict,true);assert.equal(payload.input[0].content[1].type,type==='application/pdf'?'input_file':'input_image');assert.equal(result.extracted.rows.length,2);assert.equal(JSON.stringify(payload).includes('Private customer'),false);}});
test('AI failures, missing key, truncation and refusal never return a successful review',async()=>{await assert.rejects(helpers.readInvoice(Buffer.from('x'),'image/jpeg','x',{key:''}),/OPENAI_API_KEY/);for(const result of [{ok:false},{ok:true,json:async()=>({status:'incomplete'})},{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'refusal',refusal:'No'}]}]})}])await assert.rejects(helpers.readInvoice(Buffer.from('x'),'image/jpeg','x',{key:'mock',fetcher:async()=>result}));});
function api(database,{canWrite=true,reader=helpers.readInvoice}={}){const exports={},source=readFileSync(new URL('../../app/api/washing/invoices/route.ts',import.meta.url),'utf8'),code=require('typescript').transpileModule(source,{compilerOptions:{module:require('typescript').ModuleKind.CommonJS}}).outputText;const files=new Map();const bucket={file:path=>({download:async()=>[files.get(path)||Buffer.from('%PDF-1.7')],save:async bytes=>{if(files.has(path))throw Object.assign(Error('exists'),{code:412});files.set(path,bytes);}})};vm.runInNewContext(code,{exports,URL,Request,Response,File,Buffer,Error,Date,JSON,process:{env:{NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:'mock-bucket'}},require(name){if(name==='next/server')return {NextResponse:{json:(v,o)=>Response.json(v,o)}};if(name==='node:crypto')return require(name);if(name==='firebase-admin/storage')return {getStorage:()=>({bucket:()=>bucket})};if(name==='@/lib/server/firebase-admin')return {serverDb:()=>database,adminApp:()=>({})};if(name==='@/lib/server/staff-permission')return {requireStaff:async(r,section,action)=>{if(r.headers.get('authorization')!=='Bearer staff'||action==='write'&&!canWrite)throw Error('FORBIDDEN');return {uid:'staff'};}};if(name==='@/lib/server/washing.mjs')return washing;if(name==='@/lib/server/washing-invoices.mjs')return {...helpers,readInvoice:reader};throw Error(name);}});return exports;}
const req=b=>new Request('https://example.com/api/washing/invoices',{method:'POST',headers:{authorization:'Bearer staff','Content-Type':'application/json'},body:JSON.stringify(b)});
async function upload(route,anchor='a'){const f=new FormData();f.append('anchor',anchor);f.append('file',new File(['%PDF-1.7 original'],'wash.pdf',{type:'application/pdf'}));return route.POST(new Request('https://example.com/api/washing/invoices',{method:'POST',headers:{authorization:'Bearer staff'},body:f}));}
test('uploads are private, duplicate retries retain one original per exact pickup and do not change rug status',async()=>{const d=db(jobs),route=api(d),first=await (await upload(route)).json(),second=await (await upload(route)).json();assert.equal(first.invoice.id,second.invoice.id);assert.equal(second.duplicate,true);assert.equal(first.invoice.storagePath,undefined);assert.equal(d.all().filter(([p])=>p.startsWith('wash_tracking_pickup_invoices/')&&!p.slice('wash_tracking_pickup_invoices/'.length).includes('/')).length,1);assert.equal(d.read('wash_tracking_jobs/a').closed,false);const other=await (await upload(route,'c')).json();assert.notEqual(other.invoice.id,first.invoice.id);});
test('company links and read-only staff cannot upload or mutate invoices, anonymous downloads are blocked',async()=>{const route=api(db(jobs),{canWrite:false});assert.equal((await upload(route)).status,403);assert.equal((await route.POST(new Request('https://example.com/api/washing/invoices',{method:'POST',headers:{'x-wash-link':'company'},body:'{}'}))).status,403);assert.equal((await route.GET(new Request('https://example.com/api/washing/invoices?download=id'))).status,403);});
test('AI failure preserves original and allows manual review with strict version guards',async()=>{const d=db(jobs),route=api(d,{reader:async()=>{throw new washing.WashError('AI unavailable',503);}}),saved=(await (await upload(route)).json()).invoice;assert.equal((await route.POST(req({action:'review',id:saved.id}))).status,503);let x=d.read('wash_tracking_pickup_invoices/'+saved.id);assert.equal(x.status,'Needs review');assert.ok(x.storagePath);assert.equal(x.leaseUntil,0);assert.equal((await route.POST(req({action:'confirm',id:saved.id,version:saved.version,extracted:invoice(),checked:true}))).status,409);assert.equal((await route.POST(req({action:'confirm',id:saved.id,version:x.version,extracted:invoice([row('MPW1234')]),checked:true}))).status,409);assert.equal((await route.POST(req({action:'confirm',id:saved.id,version:x.version,extracted:invoice(),checked:true}))).status,200);x=d.read('wash_tracking_pickup_invoices/'+saved.id);assert.equal(x.status,'Checked');assert.equal(d.read('wash_tracking_jobs/a').closed,false);assert.equal((await route.POST(req({action:'save',id:saved.id,version:x.version,extracted:invoice()}))).status,409);});
test('concurrent AI requests acquire one review lease and use one AI call; checked review retries do not call AI',async()=>{let count=0;const d=db(jobs),route=api(d,{reader:async()=>{count++;await new Promise(resolve=>setTimeout(resolve,20));return {extracted:invoice(),model:'mock'};}}),x=(await (await upload(route)).json()).invoice;const responses=await Promise.all([route.POST(req({action:'review',id:x.id})),route.POST(req({action:'review',id:x.id}))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(count,1);assert.equal((await route.POST(req({action:'review',id:x.id}))).status,200);assert.equal(count,1);});
test('confirmed invoice requires original batch identity and keeps history of corrections',async()=>{const d=db(jobs),route=api(d),x=(await (await upload(route)).json()).invoice;const saved=await route.POST(req({action:'save',id:x.id,version:x.version,extracted:invoice()}));assert.equal(saved.status,200);const y=(await saved.json()).invoice;d.change('wash_tracking_jobs/b',{sku:'MPW9999'});assert.equal((await route.POST(req({action:'confirm',id:y.id,version:y.version,extracted:invoice(),checked:true}))).status,409);assert.equal(d.read('wash_tracking_pickup_invoices/'+x.id).status,'Review ready');assert.equal(d.all().filter(([p])=>p.includes(x.id+'/history/')).length,2);});

test('staff download serves the private original as an attachment without public token URLs',async()=>{const d=db(jobs),route=api(d),x=(await (await upload(route)).json()).invoice,r=await route.GET(new Request('https://example.com/api/washing/invoices?download='+x.id,{headers:{authorization:'Bearer staff'}}));assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'application/pdf');assert.match(r.headers.get('Content-Disposition'),/^attachment/);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(await r.text(),'%PDF-1.7 original');});
test('foreign origins cannot upload or start paid AI reviews',async()=>{const r=new Request('https://example.com/api/washing/invoices',{method:'POST',headers:{authorization:'Bearer staff',origin:'https://wrong.example'},body:'{}'});assert.equal((await api(db(jobs)).POST(r)).status,403);});
test('archive includes closed pickup paperwork and paginates without losing files',async()=>{const seed={...jobs};for(let n=0;n<55;n++)seed['wash_tracking_pickup_invoices/f'+String(n).padStart(2,'0')]={companyId:'c',storagePath:'secret',createdAt:'2026-10-01',status:'Checked'};seed['wash_tracking_pickup_invoices/other']={companyId:'different',storagePath:'secret'};const route=api(db(seed)),get=q=>route.GET(new Request('https://example.com/api/washing/invoices'+q,{headers:{authorization:'Bearer staff'}}));const a=await (await get('?company=c')).json(),b=await (await get('?company=c&cursor='+a.nextCursor)).json();assert.equal(a.invoices.length,50);assert.equal(b.invoices.length,5);assert.equal(b.nextCursor,null);assert.equal(new Set([...a.invoices,...b.invoices].map(x=>x.id)).size,55);assert.equal(a.invoices.some(x=>x.storagePath),false);assert.equal((await get('?company=c&cursor=other')).status,400);});
