import test from 'node:test';
import assert from 'node:assert/strict';
import {date,schedule,tokenHash,today,invoiceRug,vendorJob,transition,resolveCompanyLink,createHandoff,updateJob} from '../../lib/server/washing.mjs';
function database(seed={}){
 let data=new Map(Object.entries(structuredClone(seed))),queue=Promise.resolve(),sequence=0;
 const snap=(path,map=data)=>({exists:map.has(path),data:()=>structuredClone(map.get(path))});
 const doc=path=>({path,id:path.split('/').at(-1),collection:name=>collection(path+'/'+name),get:async()=>snap(path),create:async value=>{assert.ok(!data.has(path));data.set(path,structuredClone(value));},update:async value=>{assert.ok(data.has(path));data.set(path,{...data.get(path),...value});}});
 const collection=(path,filters=[],maximum=Infinity)=>({doc:id=>doc(path+'/'+(id||'auto'+(++sequence))),where:(key,op,value)=>collection(path,[...filters,[key,value]],maximum),limit:n=>collection(path,filters,n),orderBy:()=>collection(path,filters,maximum),get:async()=>{const docs=[...data.entries()].filter(([p,v])=>p.startsWith(path+'/')&&!p.slice(path.length+1).includes('/')&&filters.every(([k,value])=>v[k]===value)).slice(0,maximum).map(([p])=>({...snap(p),id:p.split('/').at(-1)}));return {docs,size:docs.length};}});
 return {doc,collection,read:path=>structuredClone(data.get(path)),change:(path,value)=>data.set(path,{...data.get(path),...value}),
  runTransaction(fn){const run=queue.then(async()=>{const next=new Map(structuredClone([...data]));let writing=false;const tx={get:async r=>{assert.equal(writing,false,'reads precede writes');return snap(r.path,next);},create(r,value){writing=true;assert.equal(next.has(r.path),false);next.set(r.path,structuredClone(value));},update(r,value){writing=true;assert.ok(next.has(r.path));next.set(r.path,{...next.get(r.path),...structuredClone(value)});},delete(r){writing=true;next.delete(r.path);}};const result=await fn(tx);data=next;return result;});queue=run.catch(()=>{});return run;}}
}
const dates={sentDate:'2026-09-20',dueDate:'2026-09-28',pickupDate:'2026-10-02'};
const job={sku:'MPW1234',companyId:'company1',status:'At company',closed:false,version:1,...dates};
const input={companyId:'company1',dates,batch:'Weekly handoff',prepared:[{sku:'MPW1234',customerName:'Private customer',pickupDate:'2026-10-02'}],requestId:'retry1',fingerprint:'same',uid:'staff',now:'2026-09-20T12:00:00Z'};
const seed=()=>({'wash_tracking_companies/company1':{name:'Wash company'}});
test('calendar validation and customer deadline prevent impossible schedules',()=>{for(const d of ['2026-02-30','2026-13-01','not a date',null])assert.throws(()=>date(d));assert.throws(()=>schedule({...dates,dueDate:'2026-09-19'}),/handoff/);assert.throws(()=>schedule({...dates,dueDate:'2026-10-03'}),/customer/);assert.equal(date('2024-02-29'),'2024-02-29');assert.match(today(),/^\d{4}-\d{2}-\d{2}$/);});
test('saved wash invoice is authoritative for MPW identity and private customer data',()=>{const r=invoiceRug({data:{documentType:'WASH',invoiceNumber:'W12',soldTo:{name:'Customer'},items:[{id:'item1',sku:'mpw1234',description:'Blue runner',conditions:{stains:true},widthFeet:2,lengthFeet:6}]}},'item1');assert.equal(r.sku,'MPW1234');assert.equal(r.conditions,'stains');assert.throws(()=>invoiceRug({items:[]},'item1'),/wash invoice/);assert.throws(()=>invoiceRug({documentType:'WASH',items:[{id:'item1',sku:'OTHER'}]},'item1'),/MPW/);});
test('company projection hides customer, invoice, pickup date and internal staff details',()=>{const shown=vendorJob({...job,id:'j1',customerName:'Private',invoiceId:'i',invoiceNumber:'W1',createdBy:'staff',createdAt:'x',issuePhoto:'https://example.com/issue.jpg'});for(const key of ['customerName','invoiceId','invoiceNumber','createdBy','pickupDate'])assert.equal(key in shown,false);assert.equal(shown.version,1);assert.equal(shown.sku,job.sku);assert.ok(shown.issuePhoto);});
test('private link is a high entropy hashed capability and rotation/revocation invalidate old access',async()=>{const token='a'.repeat(64),hash=tokenHash(token),d=database({['wash_tracking_links/'+hash]:{companyId:'company1'},'wash_tracking_companies/company1':{linkEnabled:true,linkHash:hash}});assert.notEqual(hash,token);assert.equal(await resolveCompanyLink(d,token),'company1');d.change('wash_tracking_companies/company1',{linkHash:tokenHash('b'.repeat(64))});await assert.rejects(resolveCompanyLink(d,token),/disabled/);d.change('wash_tracking_companies/company1',{linkHash:hash,linkEnabled:false});await assert.rejects(resolveCompanyLink(d,token),/disabled/);assert.throws(()=>tokenHash('guess'));});
test('simultaneous retry creates one weekly handoff and never duplicates rug custody',async()=>{const d=database(seed()),[a,b]=await Promise.all([createHandoff(d,input),createHandoff(d,input)]);assert.deepEqual(a,b);assert.equal(d.read('wash_tracking_active/MPW1234').jobId,a[0]);await assert.rejects(createHandoff(d,{...input,requestId:'other'}),/already being tracked/);await assert.rejects(createHandoff(d,{...input,fingerprint:'changed'}),/handoff changed/);});
test('conflicting rug rolls back the entire batch',async()=>{const d=database({...seed(),'wash_tracking_active/MPW1234':{jobId:'old'}});await assert.rejects(createHandoff(d,{...input,prepared:[{sku:'MPW2000'},{sku:'MPW1234'}]}),/already being tracked/);assert.equal(d.read('wash_tracking_active/MPW2000'),undefined);});
test('vendor can update delivery but cannot receive, inspect, reassign or change deadlines',()=>{assert.equal(transition(job,'ready',{},true).status,'Ready');for(const action of ['receive','accept','reschedule','reference','rewash','issue'])assert.throws(()=>transition(job,action,{},true),/staff/);assert.throws(()=>transition(job,'delay',{},true),/why/);assert.equal(transition(job,'delay',{note:'Drying needs another day'},true).vendorNote,'Drying needs another day');});
test('wrong tag or missing visual check never marks expected rug returned',()=>{assert.throws(()=>transition(job,'receive',{confirmSku:'MPW0000',photoMatched:true,receivedDate:'2026-09-27'}),/tag/);assert.throws(()=>transition(job,'receive',{confirmSku:job.sku,photoMatched:false}),/matches/);assert.equal(job.status,'At company');});
test('early/on-time/late arrivals are recorded before inspection',()=>{for(const [receivedDate,timing] of [['2026-09-27','Early'],['2026-09-28','On time'],['2026-09-29','Late']]){const update=transition(job,'receive',{confirmSku:job.sku,photoMatched:true,receivedDate});assert.equal(update.status,'Needs inspection');assert.equal(update.timing,timing);assert.equal(update.closed,undefined);}});
test('inspection completion requires both checks and releases only this rug',async()=>{const d=database(seed()),[id]=await createHandoff(d,input);await updateJob(d,{id,uid:'staff',action:'receive',input:{version:1,confirmSku:job.sku,photoMatched:true,receivedDate:'2026-09-28'},now:'2026-09-28T12:00:00Z'});await assert.rejects(updateJob(d,{id,uid:'staff',action:'accept',input:{version:2,clean:true},now:'now'}),/condition/);await updateJob(d,{id,uid:'staff',action:'accept',input:{version:2,clean:true,conditionChecked:true},now:'2026-09-28T13:00:00Z'});assert.equal(d.read('wash_tracking_active/MPW1234'),undefined);assert.equal(d.read('wash_tracking_jobs/'+id).closed,true);await assert.rejects(updateJob(d,{id,uid:'staff',action:'accept',input:{version:3,clean:true,conditionChecked:true},now:'now'}),/completed/);});
test('company scope and stale versions fail before writes',async()=>{const d=database(seed()),[id]=await createHandoff(d,input);await assert.rejects(updateJob(d,{id,companyId:'company2',vendor:true,uid:'company2',action:'ready',input:{version:1},now:'now'}),/not found/);await updateJob(d,{id,companyId:'company1',vendor:true,uid:'company1',action:'ready',input:{version:1},now:'now'});await assert.rejects(updateJob(d,{id,companyId:'company1',vendor:true,uid:'company1',action:'plan',input:{version:1,plannedDate:today()},now:'now'}),/Refresh/);assert.equal(d.read('wash_tracking_jobs/'+id).version,2);});
test('inspection issue and rewash preserve custody and reset previous delivery state',()=>{const received={...job,status:'Needs inspection',receivedDate:'2026-09-28',timing:'On time'};assert.throws(()=>transition(received,'issue',{}),/describe/);const issue=transition(received,'issue',{note:'Stain remains'});const update=transition({...received,...issue},'rewash',{sentDate:'2026-09-29',dueDate:'2026-10-01',pickupDate:'2026-10-02',note:'Remove stain'});assert.equal(update.status,'At company');assert.equal(update.correctionCount,1);assert.equal(update.receivedDate,'');assert.equal(update.closed,undefined);});

// Exercise the actual Next.js route with isolated database and permission adapters.
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import * as washing from '../../lib/server/washing.mjs';
const require=createRequire(import.meta.url);
function api(db){const exports={},source=readFileSync(new URL('../../app/api/washing/route.ts',import.meta.url),'utf8'),code=require('typescript').transpileModule(source,{compilerOptions:{module:require('typescript').ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{exports,URL,Request,Response,Error,require(name){if(name==='next/server')return {NextResponse:{json:(value,options)=>Response.json(value,options)}};if(name==='node:crypto')return require(name);if(name==='@/lib/server/firebase-admin')return {serverDb:()=>db};if(name==='@/lib/server/staff-permission')return {requireStaff:async request=>{if(request.headers.get('authorization')!=='Bearer staff')throw Error('FORBIDDEN');return {uid:'staff'};}};if(name==='@/lib/server/washing.mjs')return washing;throw Error(name);}});return exports;}
const companyToken='a'.repeat(64),companyHash=tokenHash(companyToken);
const apiSeed=()=>({...seed(),'wash_tracking_companies/company1':{name:'Wash company',linkEnabled:true,linkHash:companyHash},['wash_tracking_links/'+companyHash]:{companyId:'company1'},'wash_tracking_jobs/j1':{...job,id:'j1',customerName:'Secret customer',invoiceNumber:'Invoice secret',createdBy:'staff'},'wash_tracking_jobs/j2':{...job,id:'j2',companyId:'company2'}});
const req=(body,token=companyToken)=>new Request('https://example.com/api/washing',{method:body?'POST':'GET',headers:{'x-wash-link':token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
test('company GET ignores guessed company filters and returns only safe own-company fields',async()=>{const route=api(database(apiSeed())),r=await route.GET(new Request('https://example.com/api/washing?company=company2',{headers:{'x-wash-link':companyToken}}));assert.equal(r.status,200);const d=await r.json();assert.deepEqual(d.jobs.map(j=>j.id),['j1']);assert.equal(d.jobs[0].customerName,undefined);assert.equal(d.jobs[0].pickupDate,undefined);assert.equal(r.headers.get('cache-control'),'no-store');});
test('API denies unauthorized staff, malformed links and vendor access to admin actions',async()=>{const route=api(database(apiSeed()));assert.equal((await route.GET(new Request('https://example.com/api/washing'))).status,403);assert.equal((await route.GET(req(null,'bad'))).status,401);for(const action of ['company','link','revoke','batch','resolveException'])assert.equal((await route.POST(req({action,companyId:'company2',id:'j2'}))).status,403);});
test('API forbids cross-company mutations and records exceptions without closing expected rugs',async()=>{const d=database(apiSeed()),route=api(d);assert.equal((await route.POST(req({action:'ready',id:'j2',version:1}))).status,404);const r=await route.POST(req({action:'exception',companyId:'company2',note:'Wrong blue rug delivered'}));assert.equal(r.status,200);assert.equal(d.read('wash_tracking_jobs/j1').status,'At company');const all=await d.collection('wash_tracking_exceptions').get();assert.equal(all.docs[0].data().companyId,'company1');});
test('API link replacement immediately disables the previous capability',async()=>{const d=database(apiSeed()),route=api(d),r=await route.POST(new Request('https://example.com/api/washing',{method:'POST',headers:{authorization:'Bearer staff','Content-Type':'application/json'},body:JSON.stringify({action:'link',companyId:'company1'})}));assert.equal(r.status,200);const token=(await r.json()).token;assert.match(token,/^[a-f0-9]{64}$/);assert.equal((await route.GET(req(null,companyToken))).status,401);assert.equal((await route.GET(req(null,token))).status,200);});

test('padded MPW tags cannot create a second custody record for the same number',async()=>{const d=database(seed());await createHandoff(d,input);await assert.rejects(createHandoff(d,{...input,requestId:'padded',prepared:[{sku:'MPW0001234'}]}),/already being tracked/);});
