import test from 'node:test';
import assert from 'node:assert/strict';
import {date,schedule,tokenHash,today,invoiceRug,vendorJob,transition,resolveCompanyLink,createHandoff,updateJob} from '../../lib/server/washing.mjs';
function database(seed={}){
 let data=new Map(Object.entries(structuredClone(seed))),queue=Promise.resolve(),sequence=0;
 const snap=(path,map=data)=>({id:path.split('/').at(-1),exists:map.has(path),data:()=>structuredClone(map.get(path))});
 const doc=path=>({path,id:path.split('/').at(-1),collection:name=>collection(path+'/'+name),get:async()=>snap(path),create:async value=>{assert.ok(!data.has(path));data.set(path,structuredClone(value));},update:async value=>{assert.ok(data.has(path));data.set(path,{...data.get(path),...value});}});
 const collection=(path,filters=[],maximum=Infinity,after='')=>({path,filters,maximum,after,query:true,select:()=>collection(path,filters,maximum,after),doc:id=>doc(path+'/'+(id||'auto'+(++sequence))),where:(key,op,value)=>collection(path,[...filters,[key,value]],maximum,after),limit:n=>collection(path,filters,n,after),startAfter:s=>collection(path,filters,maximum,s.id),orderBy:()=>collection(path,filters,maximum,after),get:async()=>{const docs=[...data.entries()].filter(([p,v])=>p.startsWith(path+'/')&&!p.slice(path.length+1).includes('/')&&filters.every(([k,value])=>v[k]===value)).sort(([a],[b])=>a.localeCompare(b)).filter(([p])=>!after||p.split('/').at(-1)>after).slice(0,maximum).map(([p])=>({...snap(p),id:p.split('/').at(-1)}));return {docs,size:docs.length};}});
 return {doc,collection,read:path=>structuredClone(data.get(path)),change:(path,value)=>data.set(path,{...data.get(path),...value}),
  runTransaction(fn){const run=queue.then(async()=>{const next=new Map(structuredClone([...data]));let writing=false;const tx={get:async r=>{assert.equal(writing,false,'reads precede writes');if(r.query){const docs=[...next.entries()].filter(([p,v])=>p.startsWith(r.path+'/')&&!p.slice(r.path.length+1).includes('/')&&r.filters.every(([k,value])=>v[k]===value)).slice(0,r.maximum).map(([p])=>snap(p,next));return {docs,size:docs.length};}return snap(r.path,next);},create(r,value){writing=true;assert.equal(next.has(r.path),false);next.set(r.path,structuredClone(value));},update(r,value){writing=true;assert.ok(next.has(r.path));next.set(r.path,{...next.get(r.path),...structuredClone(value)});},set(r,value){writing=true;next.set(r.path,structuredClone(value));},delete(r){writing=true;next.delete(r.path);}};const result=await fn(tx);data=next;return result;});queue=run.catch(()=>{});return run;}}
}
const dates={sentDate:'2026-09-20',dueDate:'2026-09-28',pickupDate:'2026-10-02'};
const job={sku:'MPW1234',companyId:'company1',status:'At company',closed:false,version:1,...dates};
const input={companyId:'company1',dates,batch:'Weekly handoff',prepared:[{sku:'MPW1234',customerName:'Private customer',pickupDate:'2026-10-02'}],requestId:'retry1',fingerprint:'same',uid:'staff',now:'2026-09-20T12:00:00Z'};
const seed=()=>({'wash_tracking_companies/company1':{name:'Wash company'}});
test('calendar validation and customer deadline prevent impossible schedules',()=>{for(const d of ['2026-02-30','2026-13-01','not a date',null])assert.throws(()=>date(d));assert.throws(()=>schedule({...dates,dueDate:'2026-09-19'}),/handoff/);assert.throws(()=>schedule({...dates,dueDate:'2026-10-03'}),/customer/);assert.equal(date('2024-02-29'),'2024-02-29');assert.match(today(),/^\d{4}-\d{2}-\d{2}$/);});
test('saved wash invoice is authoritative for MPW identity and private customer data',()=>{const r=invoiceRug({data:{documentType:'WASH',invoiceNumber:'W12',soldTo:{name:'Customer'},items:[{id:'item1',sku:'mpw1234',description:'Blue runner',conditions:{stains:true},widthFeet:2,lengthFeet:6}]}},'item1');assert.equal(r.sku,'MPW1234');assert.equal(r.conditions,'stains');assert.throws(()=>invoiceRug({items:[]},'item1'),/wash invoice/);assert.throws(()=>invoiceRug({documentType:'WASH',items:[{id:'item1',sku:'OTHER'}]},'item1'),/MPW/);});
test('company projection hides customer, invoice, pickup date and internal staff details',()=>{const shown=vendorJob({...job,id:'j1',customerName:'Private',invoiceId:'i',invoiceNumber:'W1',createdBy:'staff',createdAt:'x',issuePhoto:'https://example.com/issue.jpg'});for(const key of ['customerName','invoiceId','invoiceNumber','createdBy','pickupDate'])assert.equal(key in shown,false);assert.equal(shown.version,1);assert.equal(shown.sku,job.sku);assert.ok(shown.issuePhoto);});
test('private link is a high entropy hashed capability and rotation/revocation invalidate old access',async()=>{const token='a'.repeat(64),hash=tokenHash(token),d=database({['wash_tracking_links/'+hash]:{companyId:'company1'},'wash_tracking_companies/company1':{linkEnabled:true,linkHash:hash}});assert.notEqual(hash,token);assert.equal(await resolveCompanyLink(d,token),'company1');d.change('wash_tracking_companies/company1',{linkHash:tokenHash('b'.repeat(64))});await assert.rejects(resolveCompanyLink(d,token),/disabled/);d.change('wash_tracking_companies/company1',{linkHash:hash,linkEnabled:false});await assert.rejects(resolveCompanyLink(d,token),/disabled/);assert.throws(()=>tokenHash('guess'));});
test('simultaneous retry creates one weekly handoff and never duplicates rug custody',async()=>{const d=database(seed()),[a,b]=await Promise.all([createHandoff(d,input),createHandoff(d,input)]);assert.deepEqual(a,b);assert.equal(d.read('wash_tracking_active/MPW1234').jobId,a[0]);await assert.rejects(createHandoff(d,{...input,requestId:'other'}),/already being tracked/);await assert.rejects(createHandoff(d,{...input,fingerprint:'changed'}),/handoff changed/);});
test('conflicting rug rolls back the entire batch',async()=>{const d=database({...seed(),'wash_tracking_active/MPW1234':{jobId:'old'}});await assert.rejects(createHandoff(d,{...input,prepared:[{sku:'MPW2000'},{sku:'MPW1234'}]}),/already being tracked/);assert.equal(d.read('wash_tracking_active/MPW2000'),undefined);});
test('vendor can update delivery but cannot receive, inspect, reassign or change deadlines',()=>{assert.equal(transition(job,'ready',{},true).status,'Ready');for(const action of ['receive','accept','reschedule','reference','rewash','issue'])assert.throws(()=>transition(job,action,{},true),/staff/);assert.throws(()=>transition(job,'delay',{},true),/why/);assert.equal(transition(job,'delay',{note:'Drying needs another day'},true).vendorNote,'Drying needs another day');});
test('wrong tag or missing visual check never marks expected rug returned',()=>{assert.throws(()=>transition(job,'receive',{confirmSku:'MPW0000',photoMatched:true,receivedDate:'2026-09-27'}),/tag/);assert.throws(()=>transition(job,'receive',{confirmSku:job.sku,photoMatched:false}),/matches/);assert.equal(job.status,'At company');});
test('early/on-time/late arrivals are recorded before inspection',()=>{for(const [receivedDate,timing] of [['2026-09-27','Early'],['2026-09-28','On time'],['2026-09-29','Late']]){const update=transition(job,'receive',{confirmSku:job.sku,photoMatched:true,receivedDate});assert.equal(update.status,'Needs inspection');assert.equal(update.timing,timing);assert.equal(update.closed,undefined);}});
test('inspection completion requires both checks and releases only this rug',async()=>{const d=database(seed()),[id]=await createHandoff(d,input);await updateJob(d,{id,uid:'staff',action:'receive',input:{version:1,confirmSku:job.sku,photoMatched:true,receivedDate:'2026-09-28'},now:'2026-09-28T12:00:00Z'});await assert.rejects(updateJob(d,{id,uid:'staff',action:'accept',input:{version:2,clean:true},now:'now'}),/condition/);await updateJob(d,{id,uid:'staff',action:'accept',input:{version:2,clean:true,conditionChecked:true},now:'2026-09-28T13:00:00Z'});assert.equal(d.read('wash_tracking_active/MPW1234'),undefined);assert.equal(d.read('wash_tracking_jobs/'+id).closed,true);await assert.rejects(updateJob(d,{id,uid:'staff',action:'accept',input:{version:3,clean:true,conditionChecked:true},now:'now'}),/completed/);});
test('company scope and stale versions fail before writes',async()=>{const d=database(seed()),[id]=await createHandoff(d,input);await assert.rejects(updateJob(d,{id,companyId:'company2',vendor:true,uid:'company2',action:'ready',input:{version:1},now:'now'}),/not found/);await updateJob(d,{id,companyId:'company1',vendor:true,uid:'company1',action:'ready',input:{version:1},now:'now'});await assert.rejects(updateJob(d,{id,companyId:'company1',vendor:true,uid:'company1',action:'plan',input:{version:1,plannedDate:today()},now:'now'}),/Refresh/);assert.equal(d.read('wash_tracking_jobs/'+id).version,2);});
test('inspection issue and rewash preserve custody and reset previous delivery state',()=>{const received={...job,status:'Needs inspection',receivedDate:'2026-09-28',timing:'On time'};assert.throws(()=>transition(received,'issue',{}),/describe/);const issue=transition(received,'issue',{note:'Stain remains'});const update=transition({...received,...issue},'rewash',{sentDate:'2026-09-29',dueDate:'2026-10-01',pickupDate:'2026-10-02',note:'Remove stain'});assert.equal(update.status,'At company');assert.equal(update.correctionCount,1);assert.equal(update.receivedDate,'');assert.equal(update.closed,undefined);});

// Exercise the actual Next.js route with isolated database and permission adapters.
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import * as priority from '../../lib/washing-priority.mjs';
import * as invoiceProgress from '../../lib/washing-invoice.mjs';
import * as washing from '../../lib/server/washing.mjs';
const require=createRequire(import.meta.url);
function api(db){const exports={},source=readFileSync(new URL('../../app/api/washing/route.ts',import.meta.url),'utf8'),code=require('typescript').transpileModule(source,{compilerOptions:{module:require('typescript').ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{exports,URL,Request,Response,Error,require(name){if(name==='next/server')return {NextResponse:{json:(value,options)=>Response.json(value,options)}};if(name==='node:crypto')return require(name);if(name==='@/lib/server/firebase-admin')return {serverDb:()=>db};if(name==='@/lib/server/staff-permission')return {requireStaff:async request=>{if(request.headers.get('authorization')!=='Bearer staff')throw Error('FORBIDDEN');return {uid:'staff'};}};if(name==='@/lib/washing-invoice.mjs')return invoiceProgress;if(name==='@/lib/washing-priority.mjs')return priority;if(name==='@/lib/server/washing.mjs')return washing;throw Error(name);}});return exports;}
const companyToken='a'.repeat(64),companyHash=tokenHash(companyToken);
const apiSeed=()=>({...seed(),'wash_tracking_companies/company1':{name:'Wash company',linkEnabled:true,linkHash:companyHash},['wash_tracking_links/'+companyHash]:{companyId:'company1'},'wash_tracking_jobs/j1':{...job,id:'j1',customerName:'Secret customer',invoiceNumber:'Invoice secret',createdBy:'staff'},'wash_tracking_jobs/j2':{...job,id:'j2',companyId:'company2'}});
const req=(body,token=companyToken)=>new Request('https://example.com/api/washing',{method:body?'POST':'GET',headers:{'x-wash-link':token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
test('company GET ignores guessed company filters and returns only safe own-company fields',async()=>{const route=api(database(apiSeed())),r=await route.GET(new Request('https://example.com/api/washing?company=company2',{headers:{'x-wash-link':companyToken}}));assert.equal(r.status,200);const d=await r.json();assert.deepEqual(d.jobs.map(j=>j.id),['j1']);assert.equal(d.jobs[0].customerName,undefined);assert.equal(d.jobs[0].pickupDate,undefined);assert.equal(r.headers.get('cache-control'),'no-store');});
test('API denies unauthorized staff, malformed links and vendor access to admin actions',async()=>{const route=api(database(apiSeed()));assert.equal((await route.GET(new Request('https://example.com/api/washing'))).status,403);assert.equal((await route.GET(req(null,'bad'))).status,401);for(const action of ['company','link','revoke','batch','resolveException'])assert.equal((await route.POST(req({action,companyId:'company2',id:'j2'}))).status,403);});
test('API forbids cross-company mutations and records exceptions without closing expected rugs',async()=>{const d=database(apiSeed()),route=api(d);assert.equal((await route.POST(req({action:'ready',id:'j2',version:1}))).status,404);const r=await route.POST(req({action:'exception',companyId:'company2',note:'Wrong blue rug delivered'}));assert.equal(r.status,200);assert.equal(d.read('wash_tracking_jobs/j1').status,'At company');const all=await d.collection('wash_tracking_exceptions').get();assert.equal(all.docs[0].data().companyId,'company1');});
test('API link replacement immediately disables the previous capability',async()=>{const d=database(apiSeed()),route=api(d),r=await route.POST(new Request('https://example.com/api/washing',{method:'POST',headers:{authorization:'Bearer staff','Content-Type':'application/json'},body:JSON.stringify({action:'link',companyId:'company1'})}));assert.equal(r.status,200);const token=(await r.json()).token;assert.match(token,/^[a-f0-9]{64}$/);assert.equal((await route.GET(req(null,companyToken))).status,401);assert.equal((await route.GET(req(null,token))).status,200);});

test('padded MPW tags cannot create a second custody record for the same number',async()=>{const d=database(seed());await createHandoff(d,input);await assert.rejects(createHandoff(d,{...input,requestId:'padded',prepared:[{sku:'MPW0001234'}]}),/already being tracked/);});
test('duplicate company names ignore case and extra spaces, including simultaneous adds',async()=>{const d=database();const results=await Promise.allSettled([washing.addCompany(d,'  Blue   Wash  ','staff','now'),washing.addCompany(d,'blue wash','staff','now')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const rejected=results.find(r=>r.status==='rejected');assert.match(rejected.reason.message,/Company already added/);assert.ok(rejected.reason.existingId);});
test('existing duplicate companies merge jobs and reports without deleting them',async()=>{const hash=tokenHash('c'.repeat(64)),d=database({'wash_tracking_companies/old':{name:'Blue Wash',createdAt:'2026-01-01',linkEnabled:true},'wash_tracking_companies/duplicate':{name:' blue  wash ',createdAt:'2026-02-01',linkHash:hash,linkEnabled:false},['wash_tracking_links/'+hash]:{companyId:'duplicate'},'wash_tracking_jobs/kept':{...job,companyId:'duplicate'},'wash_tracking_exceptions/report':{companyId:'duplicate',note:'Keep this report',resolved:true}});const mapping=await washing.cleanupCompanies(d,'staff','now');assert.equal(mapping.duplicate,'old');assert.equal(d.read('wash_tracking_jobs/kept').companyId,'old');assert.equal(d.read('wash_tracking_exceptions/report').note,'Keep this report');assert.equal(d.read('wash_tracking_exceptions/report').companyId,'old');assert.equal(d.read('wash_tracking_companies/duplicate').archived,true);assert.equal(d.read('wash_tracking_links/'+hash),undefined);assert.equal(d.read('wash_tracking_jobs/kept').version,2);});
test('company removal cannot orphan outstanding rugs, but preserves completed history',async()=>{const d=database({...seed(),'wash_tracking_jobs/j1':job});await assert.rejects(washing.archiveCompany(d,'company1','staff','now'),/outstanding/);d.change('wash_tracking_jobs/j1',{closed:true});await washing.archiveCompany(d,'company1','staff','now');assert.equal(d.read('wash_tracking_companies/company1').archived,true);assert.ok(d.read('wash_tracking_jobs/j1'));});
test('effective return deadline is three calendar days before customer pickup, including month boundaries',()=>{const j={...job,dueDate:'2026-10-02',pickupDate:'2026-10-01'};assert.equal(priority.returnBy(j),'2026-09-28');assert.equal(priority.priorityInfo(j,'2026-09-28').pickupRisk,true);assert.equal(priority.priorityInfo({...j,closed:true},'2026-09-28').pickupRisk,false);assert.equal(priority.returnBy({...job,dueDate:'2026-09-25'}),'2026-09-25');});
test('company-safe priority order retains earliest deadline without disclosing customer pickup date',()=>{const a=vendorJob({...job,id:'a',...priority.priorityInfo({...job,pickupDate:'2026-10-01',dueDate:'2026-10-05'},'2026-09-28')}),b=vendorJob({...job,id:'b',...priority.priorityInfo({...job,pickupDate:'2026-10-04',dueDate:'2026-10-02'},'2026-09-28')});assert.ok(priority.priorityOrder(a,b)<0);assert.equal(a.pickupDate,undefined);});
test('later deliveries require acknowledgement and an explanation for earlier rugs left behind',async()=>{const early={...job,dueDate:today(),pickupDate:'',id:'early'},later={...job,sku:'MPW2000',dueDate:priority.shiftDate(today(),3),pickupDate:'',id:'later'},d=database({...seed(),'wash_tracking_jobs/early':early,'wash_tracking_jobs/later':later});const args={companyId:'company1',rugs:[{id:'later',version:1}],plannedDate:today(),uid:'company',now:'now'};await assert.rejects(washing.planReturns(d,args),/Earlier rugs left behind/);assert.equal(d.read('wash_tracking_jobs/later').status,'At company');const result=await washing.planReturns(d,{...args,acknowledged:true,note:'Earlier rug is still drying; it will follow tomorrow.'});assert.deepEqual(result.leftBehind,['MPW1234']);assert.equal(d.read('wash_tracking_jobs/later').status,'Delivery planned');});
test('bulk delivery plan preserves company isolation and rolls back stale versions',async()=>{const d=database({...seed(),'wash_tracking_jobs/j1':{...job,dueDate:priority.shiftDate(today(),3),pickupDate:''},'wash_tracking_jobs/j2':{...job,companyId:'company2',sku:'MPW9999'}});const args={companyId:'company1',rugs:[{id:'j1',version:1},{id:'j2',version:1}],plannedDate:today(),uid:'company',now:'now'};await assert.rejects(washing.planReturns(d,args),/not found/);assert.equal(d.read('wash_tracking_jobs/j1').status,'At company');await assert.rejects(washing.planReturns(d,{...args,rugs:[{id:'j1',version:0}]}),/Refresh/);});
test('departure requires a saved delivery plan and matching physical tag confirmation',async()=>{const d=database({...seed(),'wash_tracking_jobs/j1':{...job,dueDate:priority.shiftDate(today(),3),pickupDate:''}}),args={companyId:'company1',rugs:[{id:'j1',version:1}],dispatch:true,uid:'company',now:'now'};await assert.rejects(washing.planReturns(d,args),/MPW tags/);await assert.rejects(washing.planReturns(d,{...args,loadedChecked:true}),/save a delivery plan/);await washing.planReturns(d,{...args,dispatch:false,plannedDate:today()});await washing.planReturns(d,{...args,rugs:[{id:'j1',version:2}],loadedChecked:true});assert.equal(d.read('wash_tracking_jobs/j1').status,'On the way');const received=transition(d.read('wash_tracking_jobs/j1'),'receive',{confirmSku:job.sku,photoMatched:true,receivedDate:today()});assert.equal(received.status,'Needs inspection');});
test('solved reports are paginated separately and never appear in the open folder',async()=>{const d=database({...apiSeed(),'wash_tracking_exceptions/a':{companyId:'company1',resolved:false,note:'Open',createdAt:'now'},'wash_tracking_exceptions/b':{companyId:'company1',resolved:true,note:'Solved',createdAt:'now',resolution:'Fixed'},'wash_tracking_exceptions/c':{companyId:'company2',resolved:true,note:'Private',createdAt:'now'}}),route=api(d);const open=await (await route.GET(new Request('https://example.com/api/washing?reports=open',{headers:{'x-wash-link':companyToken}}))).json(),solved=await (await route.GET(new Request('https://example.com/api/washing?reports=solved',{headers:{'x-wash-link':companyToken}}))).json();assert.deepEqual(open.reports.map(r=>r.id),['a']);assert.deepEqual(solved.reports.map(r=>r.id),['b']);assert.equal(solved.reports[0].resolution,'Fixed');});
test('new administrative repair and removal routes remain forbidden to company links',async()=>{const route=api(database(apiSeed()));for(const action of ['cleanupCompanies','archiveCompany'])assert.equal((await route.POST(req({action,companyId:'company1'}))).status,403);assert.equal((await route.GET(new Request('https://example.com/api/washing?alerts=1',{headers:{'x-wash-link':companyToken}}))).status,403);});

test('admin alert summary contains deadlines and planned rugs without photo or customer data',async()=>{const d=database({...apiSeed(),'wash_tracking_jobs/j1':{...job,sku:'MPW1234',pickupDate:priority.shiftDate(today(),3),dueDate:priority.shiftDate(today(),4),photo:'sensitive-photo',customerName:'Private'}}),route=api(d),r=await route.GET(new Request('https://example.com/api/washing?alerts=1',{headers:{authorization:'Bearer staff'}}));assert.equal(r.status,200);const result=await r.json();assert.ok(result.alerts.some(j=>j.sku==='MPW1234'));for(const j of result.alerts){assert.equal(j.customerName,undefined);assert.equal(j.photo,undefined);}});
test('report pagination makes older solved reports accessible without mixing companies',async()=>{const seed=apiSeed();for(let i=0;i<55;i++)seed['wash_tracking_exceptions/r'+String(i).padStart(2,'0')]={companyId:'company1',resolved:true,note:'Solved '+i,createdAt:'2026-09-01'};const route=api(database(seed)),first=await (await route.GET(new Request('https://example.com/api/washing?reports=solved',{headers:{'x-wash-link':companyToken}}))).json();assert.equal(first.reports.length,50);assert.ok(first.nextCursor);const second=await (await route.GET(new Request('https://example.com/api/washing?reports=solved&cursor='+first.nextCursor,{headers:{'x-wash-link':companyToken}}))).json();assert.equal(second.reports.length,5);assert.equal(second.nextCursor,null);assert.equal(new Set([...first.reports,...second.reports].map(r=>r.id)).size,55);});
test('selected overdue rugs require their own delay explanation even if no earlier rug exists',async()=>{const d=database({...seed(),'wash_tracking_jobs/j1':{...job,dueDate:priority.shiftDate(today(),-1),pickupDate:''}}),args={companyId:'company1',rugs:[{id:'j1',version:1}],plannedDate:today(),uid:'company',now:'now'};await assert.rejects(washing.planReturns(d,args),/Return deadline missed/);await washing.planReturns(d,{...args,acknowledged:true,note:'Delay explained to showroom.'});assert.equal(d.read('wash_tracking_jobs/j1').priorityAcknowledged,true);});

test('a missed earlier delivery plan does not hide a rug left behind',async()=>{const d=database({...seed(),'wash_tracking_jobs/early':{...job,sku:'MPW1000',dueDate:priority.shiftDate(today(),-2),pickupDate:'',status:'Delivery planned',plannedDate:priority.shiftDate(today(),-1)},'wash_tracking_jobs/later':{...job,sku:'MPW2000',dueDate:priority.shiftDate(today(),3),pickupDate:''}});await assert.rejects(washing.planReturns(d,{companyId:'company1',rugs:[{id:'later',version:1}],plannedDate:today(),uid:'company',now:'now'}),/Earlier rugs left behind/);});

const washInvoice=(items)=>({data:{documentType:'WASH',mode:'wash',invoiceNumber:'W10',status:'washing',soldTo:{name:'Customer'},payments:[{id:'p',amount:90}],items}});
const washItem=(id,sku,repair=false)=>({id,sku,description:'Rug',fixedPrice:100,serviceType:{wash:true,repair}});
function linkedJob(itemId,sku){return {...job,itemId,sku,invoiceId:'invoice1',invoiceCollection:'invoices',status:'Needs inspection'};}
const acceptArgs=(id,version=1)=>({id,uid:'staff',action:'accept',input:{version,clean:true,conditionChecked:true},now:'2026-10-01T15:00:00Z'});
test('same-day pickups stay separate and retries preserve their batch identity',async()=>{const d=database(seed()),[one]=await createHandoff(d,input),[two]=await createHandoff(d,{...input,prepared:[{sku:'MPW2000'}],requestId:'second',fingerprint:'second'});assert.notEqual(d.read('wash_tracking_jobs/'+one).batchId,d.read('wash_tracking_jobs/'+two).batchId);assert.equal(d.read('wash_tracking_jobs/'+one).pickupBatchDate,dates.sentDate);assert.deepEqual(await createHandoff(d,input),[one]);assert.equal(priority.pickupGroups([{...d.read('wash_tracking_jobs/'+one),id:one},{...d.read('wash_tracking_jobs/'+two),id:two}]).length,2);});
test('work queue puts older batches first but urgent rugs first and advances after finishing',()=>{const a={...job,id:'a',sentDate:'2026-09-01'},b={...job,id:'b',sentDate:'2026-09-10',dueDate:'2026-09-15'},urgent={...job,id:'u',sentDate:'2026-09-20',alert:true};assert.deepEqual(priority.workQueue([b,a]).map(j=>j.id),['a','b']);assert.deepEqual(priority.workQueue([b,a,urgent]).map(j=>j.id),['u','a','b']);assert.deepEqual(priority.workQueue([{...a,status:'Ready'},b]).map(j=>j.id),['b']);});
test('company must explain skipping earlier work; status changes never update invoices',async()=>{const d=database({...seed(),'wash_tracking_jobs/older':{...job,sentDate:'2026-09-01'},'wash_tracking_jobs/newer':{...job,sentDate:'2026-09-20',sku:'MPW2000'}}),args={id:'newer',companyId:'company1',vendor:true,uid:'company',action:'start',input:{version:1},now:'2026-10-01T15:00:00Z'};await assert.rejects(updateJob(d,args),/Earlier rugs/);assert.equal(d.read('wash_tracking_jobs/newer').version,1);await updateJob(d,{...args,input:{version:1,priorityAcknowledged:true,note:'Earlier rug needs stain treatment first.'}});assert.equal(d.read('wash_tracking_jobs/newer').status,'Washing');assert.deepEqual(d.read('wash_tracking_jobs/newer').queueSkipped,['MPW1234']);});
test('partial receipt updates one invoice rug and last inspected rug makes invoice ready atomically',async()=>{const items=[washItem('i1','MPW1234'),washItem('i2','MPW2000')],d=database({'invoices/invoice1':washInvoice(items),'wash_tracking_jobs/j1':linkedJob('i1','MPW1234'),'wash_tracking_jobs/j2':linkedJob('i2','MPW2000')});await updateJob(d,acceptArgs('j1'));let inv=d.read('invoices/invoice1').data;assert.equal(inv.status,'washing');assert.equal(invoiceProgress.washingSummary(inv).readyCount,1);assert.deepEqual(inv.payments,[{id:'p',amount:90}]);await updateJob(d,acceptArgs('j2'));inv=d.read('invoices/invoice1').data;assert.equal(inv.status,'ready');assert.equal(invoiceProgress.washingSummary(inv).readyCount,2);assert.equal(inv.items[0].fixedPrice,100);});
test('repairs block full readiness until staff records repair completion',async()=>{const d=database({'invoices/invoice1':washInvoice([washItem('i1','MPW1234',true)]),'wash_tracking_jobs/j1':linkedJob('i1','MPW1234')});await updateJob(d,acceptArgs('j1'));const inv=d.read('invoices/invoice1').data;assert.equal(inv.status,'repairing');assert.equal(invoiceProgress.washingSummary(inv).readyCount,0);const edited={...inv,items:inv.items.map(i=>({...i,repairCompletedAt:'2026-10-01T15:00:00Z'}))};assert.equal(invoiceProgress.mergeWashingProgress(inv,edited).status,'ready');});
test('arrival alone cannot make invoice ready and mismatched or missing invoice rolls back completion',async()=>{const d=database({'invoices/invoice1':washInvoice([washItem('i1','MPW1234')]),'wash_tracking_jobs/j1':{...linkedJob('i1','MPW1234'),status:'At company'}});await updateJob(d,{...acceptArgs('j1'),action:'receive',input:{version:1,confirmSku:'MPW1234',photoMatched:true,receivedDate:today()}});assert.equal(d.read('invoices/invoice1').data.status,'washing');assert.equal(d.read('invoices/invoice1').data.washingProgress.i1.status,'Needs inspection');d.change('invoices/invoice1',{data: {...d.read('invoices/invoice1').data,items:[washItem('i1','MPW9999')]}});await assert.rejects(updateJob(d,acceptArgs('j1',2)),/MPW number changed/);assert.equal(d.read('wash_tracking_jobs/j1').closed,false);const missing=database({'wash_tracking_jobs/j1':linkedJob('i1','MPW1234')});await assert.rejects(updateJob(missing,acceptArgs('j1')),/missing/);assert.equal(missing.read('wash_tracking_jobs/j1').closed,false);});
test('concurrent inspection updates preserve both rugs and stale invoice edits preserve tracker progress',async()=>{const d=database({'invoices/invoice1':washInvoice([washItem('i1','MPW1234'),washItem('i2','MPW2000')]),'wash_tracking_jobs/j1':linkedJob('i1','MPW1234'),'wash_tracking_jobs/j2':linkedJob('i2','MPW2000')});const stale=d.read('invoices/invoice1').data;await Promise.all([updateJob(d,acceptArgs('j1')),updateJob(d,acceptArgs('j2'))]);const current=d.read('invoices/invoice1').data,merged=invoiceProgress.mergeWashingProgress(current,{...stale,notes:'New note'});assert.equal(merged.status,'ready');assert.equal(Object.keys(merged.washingProgress).length,2);assert.equal(merged.notes,'New note');});
test('new handoff clears previous readiness and keeps original pickup group intact on correction',async()=>{const inv=washInvoice([washItem('i1','MPW1234')]);inv.data.status='ready';inv.data.washingProgress={i1:{sku:'MPW1234',status:'Checked & ready',jobId:'old'}};const d=database({...seed(),'invoices/invoice1':inv}),[id]=await createHandoff(d,{...input,prepared:[{sku:'MPW1234',invoiceId:'invoice1',invoiceCollection:'invoices',itemId:'i1'}]});assert.equal(d.read('invoices/invoice1').data.status,'washing');assert.equal(d.read('invoices/invoice1').data.washingProgress.i1.jobId,id);const original=d.read('wash_tracking_jobs/'+id);d.change('wash_tracking_jobs/'+id,{status:'Inspection issue'});await updateJob(d,{id,uid:'staff',action:'rewash',input:{version:1,...dates},now:'2026-10-01T15:00:00Z'});assert.equal(d.read('wash_tracking_jobs/'+id).pickupBatchDate,original.pickupBatchDate);assert.equal(d.read('wash_tracking_jobs/'+id).batchId,original.batchId);});
test('already collected invoices cannot be changed through inspection',async()=>{const inv=washInvoice([washItem('i1','MPW1234')]);inv.data.status='picked_up';const d=database({'invoices/invoice1':inv,'wash_tracking_jobs/j1':linkedJob('i1','MPW1234')});await assert.rejects(updateJob(d,acceptArgs('j1')),/collected/);assert.equal(d.read('invoices/invoice1').data.status,'picked_up');});

test('every invoice rug counts, including missing tags and repair-only rugs',()=>{const data={items:[washItem('a','MPW1234'),{...washItem('b',''),serviceType:{wash:false,repair:true},repairCompletedAt:'done'},washItem('c','')],washingProgress:{a:{sku:'MPW1234',status:'Checked & ready'}}};const summary=invoiceProgress.washingSummary(data);assert.equal(summary.total,3);assert.equal(summary.readyCount,2);assert.equal(summary.status,'washing');});
test('API staff inspection updates the invoice while company completion keeps it pending',async()=>{const inv=washInvoice([washItem('i1','MPW1234')]),d=database({...apiSeed(),'invoices/invoice1':inv,'wash_tracking_jobs/j1':{...linkedJob('i1','MPW1234'),status:'At company'}}),route=api(d);assert.equal((await route.POST(req({action:'ready',id:'j1',version:1}))).status,200);assert.equal(d.read('invoices/invoice1').data.status,'washing');const post=body=>route.POST(new Request('https://example.com/api/washing',{method:'POST',headers:{authorization:'Bearer staff','Content-Type':'application/json'},body:JSON.stringify(body)}));assert.equal((await post({action:'receive',id:'j1',version:2,confirmSku:'MPW1234',photoMatched:true,receivedDate:today()})).status,200);assert.equal((await post({action:'accept',id:'j1',version:3,clean:true,conditionChecked:true})).status,200);assert.equal(d.read('invoices/invoice1').data.status,'ready');const result=await (await route.GET(new Request('https://example.com/api/washing',{headers:{authorization:'Bearer staff'}}))).json();assert.equal(result.jobs.find(j=>j.id==='j1').invoiceReadyCount,1);});
