import {NextResponse} from 'next/server';
import {timingSafeEqual} from 'crypto';
import {serverDb} from '@/lib/server/firebase-admin';
import {closeLiveLot,consolidateLiveAuction} from '@/lib/auction/live-ledger.mjs';
import {AUCTION_SETTINGS,DEFAULT_SETTINGS} from '@/lib/auction/settlement.mjs';
import {sendAuctionNotices} from '@/lib/server/auction-notifications';
import {chargeAuctionInvoice} from '@/lib/server/auction-charge';
export const dynamic='force-dynamic';export const maxDuration=60;
export async function GET(req:Request){const expected=process.env.CRON_SECRET||process.env.AUCTION_CRON_SECRET||'',actual=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(expected.length<32||actual.length!==expected.length||!timingSafeEqual(Buffer.from(actual),Buffer.from(expected)))return NextResponse.json({error:'Unauthorized.'},{status:401});const db=serverDb(),results:any[]=[],start=Date.now();try{const due=await db.collection('auction_lots').where('status','==','scheduled').limit(101).get();if(due.size>100)throw Error('Worker capacity exceeded; reduce simultaneous lots.');for(const d of due.docs){if(Date.now()-start>15000)break;if(d.data().mode==='live'&&d.data().endAt<=Date.now())try{results.push({lotId:d.id,...await closeLiveLot(db,d.id)});}catch(e){results.push({lotId:d.id,error:(e as Error).message});}}
 const settings=(await db.doc(AUCTION_SETTINGS+'/current').get()).data()||DEFAULT_SETTINGS,events=await db.collection('auction_live_events').where('status','==','scheduled').limit(101).get();if(events.size>100)throw Error('Worker auction capacity exceeded.');for(const e of events.docs){if(Date.now()-start>20000)break;try{const lots=await Promise.all(e.data().lotIds.map((id:string)=>db.doc('auction_lots/'+id).get()));if(lots.every((l:any)=>['sold','unsold','cancelled'].includes(l.data()?.status)))results.push({auctionId:e.id,...await consolidateLiveAuction(db,e.id,settings)});}catch(error){results.push({auctionId:e.id,error:(error as Error).message});}
 }const unpaid=await db.collection('auction_buyer_invoices_v2').where('paymentStatus','==','unpaid').limit(10).get();for(const i of unpaid.docs){if(Date.now()-start>20000)break;if(i.data().mode==='live')try{results.push({invoiceId:i.id,...await chargeAuctionInvoice(i.id)});}catch(e){results.push({invoiceId:i.id,error:(e as Error).message});}}
 const processing=await db.collection('auction_buyer_invoices_v2').where('paymentStatus','==','processing').limit(10).get();for(const i of processing.docs){if(Date.now()-start>40000)break;if(i.data().mode==='live')try{results.push({invoiceId:i.id,...await chargeAuctionInvoice(i.id)});}catch(e){results.push({invoiceId:i.id,error:(e as Error).message});}}if(Date.now()-start<45000)results.push(...await sendAuctionNotices(start+55000));const degraded=results.some(r=>r.error);await db.doc('auction_worker_status/current').set({...(degraded?{lastFailureAt:Date.now()}:{lastSuccessAt:Date.now()}),degraded,results},{merge:true});return NextResponse.json({results});}catch(e){await db.doc('auction_worker_status/current').set({lastFailureAt:Date.now(),error:(e as Error).message},{merge:true});return NextResponse.json({error:'Auction worker needs staff review.'},{status:503});}}
