import {NextResponse} from 'next/server';
import Stripe from 'stripe';
import {requireStaff} from '@/lib/server/staff-permission';
import {serverDb} from '@/lib/server/firebase-admin';
import {check} from '@/lib/auction/engine.mjs';
import {AUCTION_SETTINGS,DEFAULT_SETTINGS} from '@/lib/auction/settlement.mjs';
import {TEST_PAYMENT_PROFILES,chargeTestInvoice,retryTestInvoice,syncTestIntent} from '@/lib/auction/payment.mjs';
export const maxDuration=60;export const dynamic='force-dynamic';export const runtime='nodejs';
function provider(){check(process.env.MARCO_POLO_AUCTION_STRIPE_TEST_ENABLED==='true','Stripe auction test mode is not configured. Live charges remain disabled.');const key=process.env.STRIPE_AUCTION_TEST_SECRET_KEY?.trim();check(key?.startsWith('sk_test_'),'Only a dedicated Stripe test key is accepted.');return new Stripe(key!);}
export async function POST(req:Request){let user;try{user=await requireStaff(req,'settings','write');}catch{return NextResponse.json({error:'Staff payment testing permission required.'},{status:403});}try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return NextResponse.json({error:'Use the management website.'},{status:403});const raw=await req.text();check(raw.length<=3000,'Request too large.');const b=JSON.parse(raw),db=serverDb(),stripe=provider();
 if(b.action==='setup'){
  check(['test-a','test-b','test-c'].includes(b.buyerId)&&b.accepted===true,'Choose a fictional buyer and accept test charge consent.');const settings=(await db.doc(AUCTION_SETTINGS+'/current').get()).data()||DEFAULT_SETTINGS,ref=db.doc(TEST_PAYMENT_PROFILES+'/'+b.buyerId);const prior=(await ref.get()).data();let customerId=prior?.customerId;if(!customerId){const c=await stripe.customers.create({name:'FICTIONAL Marco Polo '+b.buyerId,metadata:{purpose:'marcopolo_auction_test',buyerId:b.buyerId}},{idempotencyKey:'mp-auction-test-customer-'+b.buyerId});customerId=c.id;await ref.set({buyerId:b.buyerId,customerId,mode:'test',verified:false},{merge:true});}
  const origin=new URL(req.url).origin;check(origin==='https://www.marcopolorugs.com'||origin==='https://marcopolorugs.com'||new URL(origin).hostname==='localhost'||new URL(origin).hostname.endsWith('.vercel.app'),'Unknown return website.');
  const session=await stripe.checkout.sessions.create({mode:'setup',customer:customerId,payment_method_types:['card'],setup_intent_data:{metadata:{purpose:'marcopolo_auction_test',buyerId:b.buyerId,policyVersion:settings.policyVersion}},metadata:{purpose:'marcopolo_auction_test',buyerId:b.buyerId,policyVersion:settings.policyVersion},success_url:origin+'/admin/auctions?testSetup={CHECKOUT_SESSION_ID}',cancel_url:origin+'/admin/auctions'});await ref.set({sessionId:session.id,pendingPolicyVersion:settings.policyVersion,consentBy:user.uid,consentAt:Date.now(),chargeConsent:true},{merge:true});return NextResponse.json({url:session.url,mode:'test'});
 }
 if(b.action==='verify'){
  check(typeof b.sessionId==='string'&&b.sessionId.startsWith('cs_test_')&&b.sessionId.length<150,'Choose a Stripe test setup session.');const session=await stripe.checkout.sessions.retrieve(b.sessionId);check(session.livemode===false&&session.mode==='setup'&&session.status==='complete'&&session.metadata?.purpose==='marcopolo_auction_test','Test setup is not complete.');const buyerId=session.metadata!.buyerId;check(['test-a','test-b','test-c'].includes(buyerId),'Unknown fictional buyer.');const ref=db.doc(TEST_PAYMENT_PROFILES+'/'+buyerId),p=(await ref.get()).data();check(p?.sessionId===session.id&&p?.customerId===session.customer&&p?.chargeConsent===true&&p.pendingPolicyVersion===session.metadata!.policyVersion,'Test session does not match the saved customer consent.');const setup=await stripe.setupIntents.retrieve(session.setup_intent as string);check(setup.livemode===false&&setup.status==='succeeded'&&setup.customer===p!.customerId&&setup.usage==='off_session'&&typeof setup.payment_method==='string','Test card verification failed.');const method=await stripe.paymentMethods.retrieve(setup.payment_method as string);check(method.customer===p!.customerId&&method.type==='card','Test card belongs to another customer.');await ref.set({verified:true,setupIntentId:setup.id,paymentMethodId:method.id,acceptedPolicyVersion:session.metadata!.policyVersion,cardBrand:method.card?.brand||'',last4:method.card?.last4||'',verifiedAt:Date.now()},{merge:true});return NextResponse.json({verified:true,buyerId,last4:method.card?.last4});
 }
 check(typeof b.id==='string'&&/^TEST-AI-[a-f0-9]{24}$/.test(b.id),'Choose a consolidated test invoice.');if(b.action==='retry')return NextResponse.json({invoice:await retryTestInvoice(db,stripe,b.id,user.uid)});if(b.action==='charge')return NextResponse.json({invoice:await chargeTestInvoice(db,stripe,b.id,user.uid)});
 if(b.action==='sync'){const invoice=(await db.doc('auction_sandbox_invoices_v2/'+b.id).get()).data();check(invoice?.mode==='sandbox'&&invoice.paymentIntentId,'No test provider payment to reconcile.');return NextResponse.json({invoice:await syncTestIntent(db,await stripe.paymentIntents.retrieve(invoice!.paymentIntentId))});}
 throw Error('Unknown test payment action.');
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message.slice(0,300):'Stripe test operation failed. Live charging remains disabled.'},{status:400});}}
