'use client';
import {useEffect,useRef,useState} from 'react';
import * as faceapi from 'face-api.js';
import {matchFace} from '@/lib/employee-clock.mjs';
import {kioskKey} from '@/lib/employee-clock-client';
import styles from './EmployeeClock.module.css';
export default function EmployeeClock(){
 const [key,setKey]=useState(''),[employees,setEmployees]=useState<any[]>([]),[identifier,setIdentifier]=useState(''),[expected,setExpected]=useState(''),[message,setMessage]=useState('Opening attendance…'),[error,setError]=useState(''),[scanning,setScanning]=useState(false),[candidate,setCandidate]=useState<any>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[success,setSuccess]=useState<any>(null);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0),working=useRef(false),clocking=useRef(false),pending=useRef<any>(null),stable=useRef({id:'',count:0}),keyRef=useRef('');
 async function request(path:string,body?:any,token=keyRef.current){const r=await fetch('/api/employee-clock/'+path,{method:body?'POST':'GET',headers:{'x-clock-key':token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Attendance unavailable.');return d;}
 async function load(token=keyRef.current){const d=await request('session',undefined,token);setEmployees(d.employees);setReady(true);setMessage('Choose face scan or enter your exact employee ID / PIN.');return d.employees;}
 useEffect(()=>{let alive=true;const params=new URLSearchParams(window.location.search),emp=params.get('id')||'';setExpected(emp);setIdentifier(emp);const hash=new URLSearchParams(window.location.hash.slice(1));const token=hash.get('key')||sessionStorage.getItem('mp-clock-key')||'';
 async function init(){try{const t=token||await kioskKey();if(!alive)return;keyRef.current=t;setKey(t);sessionStorage.setItem('mp-clock-key',t);if(hash.has('key'))history.replaceState(null,'',window.location.pathname+window.location.search);await load(t);}catch(e){if(alive){setError(e instanceof Error?e.message:'Ask your manager for the new Shop QR.');setMessage('No employee account login is required. Older QR codes must be replaced by the manager.');}}}init();return()=>{alive=false;stop();};},[]);
 function stop(){generation.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;stable.current={id:'',count:0};}
 useEffect(()=>{if(!scanning)return;let cancelled=false;const n=generation.current;
 async function camera(){try{await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri('/models'),faceapi.nets.faceLandmark68Net.loadFromUri('/models'),faceapi.nets.faceRecognitionNet.loadFromUri('/models')]);if(cancelled)return;const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});if(cancelled){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play();}setMessage('Only one person in view. Look at the camera and hold still.');}catch(e){setError('Camera or face models could not open. Allow camera access, or use your ID / PIN.');stop();setScanning(false);}}
 camera();const timer=setInterval(async()=>{if(working.current||!video.current||video.current.readyState<2||cancelled)return;working.current=true;try{const faces=await faceapi.detectAllFaces(video.current,new faceapi.TinyFaceDetectorOptions({inputSize:416,scoreThreshold:0.75})).withFaceLandmarks().withFaceDescriptors();if(cancelled||generation.current!==n)return;const face=faces[0];if(faces.length!==1||!face||face.detection.score<0.85||face.detection.box.width*face.detection.box.height/(video.current.videoWidth*video.current.videoHeight)<0.08){stable.current={id:'',count:0};setMessage(faces.length>1?'Only one person may be in the camera.':'Move closer, face the camera and use brighter lighting.');return;}const matched=matchFace(face.descriptor,employees);if(!matched||expected&&matched.employee.empId!==expected){stable.current={id:'',count:0};setMessage('No confident match. Use your ID / PIN or ask your manager to update your face setup.');return;}stable.current=stable.current.id===matched.employee.id?{id:matched.employee.id,count:stable.current.count+1}:{id:matched.employee.id,count:1};setMessage('Hold still… confirming your face '+stable.current.count+'/4');if(stable.current.count>=4){setCandidate({...matched.employee,method:'face',descriptor:Array.from(face.descriptor)});stop();setScanning(false);setMessage('Check your name before recording attendance.');}}catch{stable.current={id:'',count:0};}finally{working.current=false;}},450);return()=>{cancelled=true;clearInterval(timer);stop();};},[scanning]);
 async function pin(){setError('');setCandidate(null);try{const all=await load();const id=identifier.trim().toLowerCase(),matches=all.filter((e:any)=>e.empId.toLowerCase()===id);if(matches.length===1&&(!expected||matches[0].empId===expected)){setCandidate({...matches[0],method:'pin',identifier:identifier.trim()});setMessage('Check your name and choose clock in or out.');}else{setCandidate({name:'Employee ID / PIN',method:'pin',identifier:identifier.trim(),status:null});setMessage('Your ID / PIN will be checked securely when you confirm.');}}catch(e){setError((e as Error).message);}}
 async function record(type:string){if(clocking.current||!candidate)return;clocking.current=true;setBusy(true);setError('');try{if(!pending.current){const position=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));pending.current={requestId:crypto.randomUUID(),type,method:candidate.method,employeeId:candidate.id||'',...(candidate.method==='face'?{descriptor:candidate.descriptor}:{identifier:candidate.identifier}),expectedEmpId:expected,location:{lat:position.coords.latitude,lng:position.coords.longitude,accuracy:position.coords.accuracy}};}const d=await request('record',pending.current);pending.current=null;setSuccess(d);setCandidate(null);setIdentifier(expected);await load();}catch(e){const m=e instanceof Error?e.message:'Allow precise location and try again.';setError(m);if(/Identity|already|last clock|accurate|showroom|conflict|replaced/.test(m))pending.current=null;}finally{clocking.current=false;setBusy(false);}}
 return <main className={styles.page}><section className={styles.card}><span className={styles.brand}>MARCO POLO RUGS · STAFF ATTENDANCE</span><h1>Clock in &amp; out</h1><p className={styles.muted}>No account login needed. Camera and precise location permission are required for face clock-in at the showroom.</p>{error&&<p className={styles.error} role="alert">{error}</p>}{success?<div role="status" className={styles.success}><h2>{success.employee.name}</h2><p>Clocked {success.log.type.toLowerCase()} · {new Date(success.log.timestamp).toLocaleTimeString()}</p><strong>Saved in Firebase</strong><button onClick={()=>{setSuccess(null);setError('');}}>Next employee</button></div>:candidate?<><h2>{candidate.name}</h2><p>{candidate.empId||'Enter your personal PIN only.'}</p><p>Confirm this is you. Current status: {candidate.status||'will be checked'}.</p><div className={styles.actions}><button disabled={busy||candidate.status==='IN'} onClick={()=>record('IN')}>Clock in</button><button disabled={busy||candidate.status==='OUT'} onClick={()=>record('OUT')}>Clock out</button></div><button className={styles.secondary} disabled={busy} onClick={()=>{setCandidate(null);pending.current=null;setError('');}}>Not me / Cancel</button></>:scanning?<><video ref={video} muted playsInline autoPlay className={styles.video}/><p role="status">{message}</p><button className={styles.secondary} onClick={()=>{stop();setScanning(false);}}>Cancel scan</button></>:<><p role="status">{message}</p><button disabled={!ready||!key} onClick={()=>{setError('');setSuccess(null);setScanning(true);setMessage('Loading camera…');}}>Scan my face</button><div className={styles.divider}>OR USE EMPLOYEE ID / PIN</div><form onSubmit={e=>{e.preventDefault();if(identifier.trim())pin();}}><label>Your employee ID / PIN<input type="password" autoComplete="off" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Enter your exact ID or PIN" maxLength={100}/></label><button disabled={!ready||!identifier.trim()} type="submit">Continue</button></form></>}<p className={styles.muted}>No clock action is saved until you confirm. If the name is wrong, cancel and ask your manager to update your face registration.</p></section></main>;
}
