'use client';
import {useRef,useState} from 'react';
import {useStaffAccess} from '@/hooks/useStaffAccess';
import {canAccess} from '@/lib/access-policy';
import {LiveOrder,orderRequest} from './client';
import styles from './LiveOrders.module.css';
export default function ShippoLabelControls({order,onUpdated}:{order:LiveOrder;onUpdated:()=>void}){
 const {staff}=useStaffAccess(),running=useRef(false),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rates,setRates]=useState<any[]>([]),[rate,setRate]=useState(''),[label,setLabel]=useState(order.shippingDetails?.labelUrl||'');
 const [parcels,setParcels]=useState({weight:'9',length:'27',width:'6',height:'6'});
 const eligible=order.deliveryOption==='Delivery'&&order.paymentStatus==='Paid'&&!order.reviewReason&&!order.refundedAmount&&!order.refundPending&&!['Delivered','Collected'].includes(order.fulfillment);
 async function request(purchase=false){if(running.current)return;if(purchase&&!window.confirm('Buy this shipping label for $'+rates.find(r=>r.id===rate)?.amount+' through Shippo?'))return;running.current=true;setBusy(true);setError('');try{const d=await orderRequest('/api/shipping/create-label',{orderId:order.id,dimensions:parcels,...(purchase?{selectedRate:rate}:{})});if(d.rates){setRates(d.rates);setRate('');}else{setLabel(d.labelUrl||'');setOpen(false);onUpdated();window.dispatchEvent(new Event('marcopolo-order-updated'));}}catch(e){setError(e instanceof Error?e.message:'Could not create label.');}finally{running.current=false;setBusy(false);}}
 if(order.deliveryOption!=='Delivery')return null;
 if(label||order.shippingDetails?.labelUrl)return <section className={styles.form}><h3>Shippo shipping label</h3><a className={styles.button} target="_blank" rel="noopener noreferrer" href={label||order.shippingDetails?.labelUrl}>Print / download shipping label</a><p className={styles.muted}>The label is saved. Mark the order Shipped only after the package leaves the showroom.</p></section>;
 return <section className={styles.form}><h3>Shippo shipping label</h3><button type="button" disabled={busy||!eligible||!canAccess(staff,'orders','write')||!!order.trackingNumber} onClick={()=>{setOpen(v=>!v);setError('');}}>Create shipping label with Shippo</button>{!eligible&&<p className={styles.muted}>Labels require a paid delivery order without a refund or review hold.</p>}{order.trackingNumber&&<p className={styles.muted}>Tracking is already recorded. Check Shippo before purchasing another label.</p>}{open&&<div><p className={styles.muted}>Default package: 9 lb, 27 × 6 × 6 inches for one Mushwani. Confirm the actual packed dimensions and weight for this shipment.</p><div className={styles.fields}>{Object.entries(parcels).map(([key,value])=><label key={key}>{key==='weight'?'Weight (lb)':key[0].toUpperCase()+key.slice(1)+' (in)'}<input type="number" min="0.1" max="1000" step="0.1" value={value} disabled={busy} onChange={e=>{setParcels({...parcels,[key]:e.target.value});setRates([]);setRate('');}}/></label>)}</div><button type="button" disabled={busy||Object.values(parcels).some(v=>!(Number(v)>0&&Number(v)<=1000))} onClick={()=>request()}>Get Shippo rates</button>{rates.length>0&&<><label>Choose carrier and service<select value={rate} disabled={busy} onChange={e=>setRate(e.target.value)}><option value="">Select a shipping rate</option>{rates.map(r=><option key={r.id} value={r.id}>{r.provider} · {r.service} · ${r.amount}</option>)}</select></label><button type="button" disabled={busy||!rate} onClick={()=>request(true)}>{busy?'Please wait…':'Buy selected label'}</button></>}</div>}{error&&<p role="alert" className={styles.error}>{error}</p>}</section>;
}
