const states='Alabama:AL|Alaska:AK|Arizona:AZ|Arkansas:AR|California:CA|Colorado:CO|Connecticut:CT|Delaware:DE|District of Columbia:DC|Florida:FL|Georgia:GA|Hawaii:HI|Idaho:ID|Illinois:IL|Indiana:IN|Iowa:IA|Kansas:KS|Kentucky:KY|Louisiana:LA|Maine:ME|Maryland:MD|Massachusetts:MA|Michigan:MI|Minnesota:MN|Mississippi:MS|Missouri:MO|Montana:MT|Nebraska:NE|Nevada:NV|New Hampshire:NH|New Jersey:NJ|New Mexico:NM|New York:NY|North Carolina:NC|North Dakota:ND|Ohio:OH|Oklahoma:OK|Oregon:OR|Pennsylvania:PA|Rhode Island:RI|South Carolina:SC|South Dakota:SD|Tennessee:TN|Texas:TX|Utah:UT|Vermont:VT|Virginia:VA|Washington:WA|West Virginia:WV|Wisconsin:WI|Wyoming:WY|Puerto Rico:PR|Guam:GU|U.S. Virgin Islands:VI|American Samoa:AS|Northern Mariana Islands:MP'.split('|').map(x=>x.split(':'));
export function normalizeCheckoutState(value){const raw=String(value??'').trim();return states.find(([name])=>name.toLowerCase()===raw.toLowerCase())?.[1]||raw.toUpperCase();}
export function checkoutContact(c={}){
 const text=(v,max,label,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw Error(required?`Check ${label}. It is required and must be no more than ${max} characters.`:`Check ${label}. Use no more than ${max} characters.`);return v.trim();};
 const out={name:text(c.name,150,'your full name'),email:text(c.email,254,'your email address'),phone:text(c.phone,40,'your phone number'),shippingAddress:text(c.shippingAddress,700,'your shipping address'),billingAddress:text(c.billingAddress,700,'your billing address'),notes:text(c.notes||'',2000,'your delivery instructions',false),billingCountry:c.billingCountry,shippingCountry:c.shippingCountry};
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email))throw Error('Enter a valid email address.');
 if(c.deliveryAddress){const a=c.deliveryAddress,state=normalizeCheckoutState(a.state),zip=String(a.zip??'').trim();if(!/^[A-Z]{2}$/.test(state))throw Error('Enter a delivery state such as VA or Virginia.');if(!/^\d{5}(-\d{4})?$/.test(zip))throw Error('Enter a delivery ZIP code with 5 digits, or ZIP+4.');
 out.deliveryAddress={street1:text(a.street1,200,'your street address'),street2:text(a.street2||'',200,'your apartment or unit',false),city:text(a.city,100,'your delivery city'),state,zip,country:'US'};
 out.shippingAddress=[out.deliveryAddress.street1,out.deliveryAddress.street2,out.deliveryAddress.city,state+' '+zip].filter(Boolean).join(', ');}
 return out;
}
