import {createHash} from 'node:crypto';
export const PICKUPS='service_pickup_bookings';
export const INVOICE_COLLECTION='invoices';
export function requireValue(ok,message){if(!ok)throw Error(message);}
export function pickupFields(input){const out={};for(const [key,max,required] of [['name',150,true],['phone',50,true],['email',200,false],['address',300,true],['city',100,true],['state',50,true],['zip',20,false],['notes',3000,false],['assignedTo',150,false]]){const v=String(input[key]||'').trim();requireValue(v.length<=max&&(!required||v.length>0),'Check '+key+'.');out[key]=v;}requireValue(!out.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email),'Check email address.');requireValue(out.phone.replace(/\D/g,'').length>=7,'Check phone number.');requireValue(/^\d{4}-\d{2}-\d{2}$/.test(input.date||'')&&new Date(input.date+'T12:00:00Z').toISOString().slice(0,10)===input.date,'Choose a valid pickup date.');requireValue(/^([01]\d|2[0-3]):[0-5]\d$/.test(input.time||''),'Choose a pickup time.');requireValue(['cleaning','repair','cleaning_repair','other'].includes(input.service),'Choose the requested service.');const count=Number(input.rugCount||0);requireValue(Number.isSafeInteger(count)&&count>=0&&count<=500,'Check estimated rug count.');return {...out,date:input.date,time:input.time,service:input.service,rugCount:count};}
export function pickupPrefill(p){return {documentType:'WASH',mode:'wash',soldTo:{name:p.name,phone:p.phone,email:p.email,address:p.address,city:p.city,state:p.state,zip:p.zip},notes:['Customer pickup: '+p.date+' '+p.time+' (America/New_York)', p.pickedUpAt?'Actually collected: '+new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',dateStyle:'medium',timeStyle:'short'}).format(new Date(p.pickedUpAt)):'', 'Requested service: '+p.service.replaceAll('_',' '),p.rugCount?'Estimated rugs: '+p.rugCount:'',p.assignedTo?'Assigned to: '+p.assignedTo:'',p.notes].filter(Boolean).join('\n'),status:p.service==='repair'?'repairing':'washing',sourcePickupId:p.id,sourcePickupVersion:p.version};}
export async function changePickup(db,input,actor,now=Date.now()){
 requireValue(/^[\w-]{10,100}$/.test(input.id||'')&&/^[\w-]{10,100}$/.test(input.requestId||''),'Invalid booking reference.');requireValue(['create','edit','reschedule','picked_up','cancel'].includes(input.action),'Invalid pickup action.');const ref=db.doc(PICKUPS+'/'+input.id),op=ref.collection('history').doc(input.requestId),fingerprint=createHash('sha256').update(JSON.stringify({actor,input})).digest('hex');
 return db.runTransaction(async tx=>{const [d,previous]=await tx.getAll(ref,op);if(previous.exists){requireValue(previous.data().fingerprint===fingerprint,'Request changed; refresh and retry.');return {id:ref.id};}const p=d.data()||{};let update;
 if(input.action==='create'){requireValue(!d.exists,'Pickup already exists.');update={...pickupFields(input.fields),id:ref.id,status:'scheduled',createdAt:now,createdBy:actor,version:1};}else{requireValue(d.exists&&p.version===input.version,'Booking changed; refresh before continuing.');requireValue(!p.invoiceId&&p.status!=='invoiced','Open the linked invoice to manage this completed booking.');if(['edit','reschedule'].includes(input.action)){requireValue(input.action==='reschedule'?['scheduled','cancelled'].includes(p.status):['scheduled','picked_up'].includes(p.status),'This booking cannot be rescheduled.');update={...pickupFields(input.fields),status:input.action==='reschedule'?'scheduled':p.status,...(input.action==='reschedule'?{cancellationReason:''}:{})};}else if(input.action==='picked_up'){requireValue(p.status==='scheduled','Only scheduled pickups can be collected.');update={status:'picked_up',pickedUpAt:now,pickedUpBy:actor};}else{requireValue(p.status==='scheduled','Only scheduled bookings can be cancelled.');requireValue(typeof input.reason==='string'&&input.reason.trim().length>=5&&input.reason.length<=500,'Record a cancellation reason.');update={status:'cancelled',cancellationReason:input.reason.trim(),cancelledAt:now};}update.version=p.version+1;}
 tx.set(ref,{...update,updatedAt:now,updatedBy:actor},{merge:true});tx.create(op,{action:input.action,actor,at:now,fingerprint,reason:input.reason||'',...(input.fields?{fields:update}:{})});return {id:ref.id};});
}
export async function createPickupInvoice(db,{pickupId,data,total,actor,now=Date.now()}){
 requireValue(/^[\w-]{10,100}$/.test(pickupId||''),'Invalid pickup.');const pickup=db.doc(PICKUPS+'/'+pickupId),invoice=db.doc(INVOICE_COLLECTION+'/pickup-'+pickupId),number=db.doc('counters/invoice-number-'+encodeURIComponent(INVOICE_COLLECTION+':'+data.invoiceNumber));const fingerprint=createHash('sha256').update(JSON.stringify(data)).digest('hex');
 return db.runTransaction(async tx=>{const [p,i,n]=await tx.getAll(pickup,invoice,number);requireValue(p.exists,'Pickup is missing.');const booking=p.data();if(booking.invoiceId){requireValue(booking.invoiceId===invoice.id&&i.data()?.pickupFingerprint===fingerprint,'This pickup already has an invoice. Open its linked invoice.');return {id:invoice.id};}requireValue(data.sourcePickupVersion===booking.version,'Pickup details changed; reload the invoice from this booking.');requireValue(booking.status==='picked_up','Mark the rugs picked up before creating the invoice.');requireValue(!i.exists&&!n.exists,'Invoice reference or number is already used.');const stamp=new Date(now);tx.create(number,{invoiceId:invoice.id,invoiceNumber:data.invoiceNumber,createdAt:stamp});tx.create(invoice,{invoiceNumber:data.invoiceNumber,customerName:data.soldTo.name,date:data.date,totalAmount:total,data,createdAt:stamp,updatedAt:stamp,pickupFingerprint:fingerprint});tx.update(pickup,{status:'invoiced',invoiceId:invoice.id,invoiceNumber:data.invoiceNumber,invoiceCollection:INVOICE_COLLECTION,version:booking.version+1,updatedAt:now});tx.create(pickup.collection('history').doc('invoice-created'),{action:'invoice_created',actor,at:now,invoiceId:invoice.id});return {id:invoice.id};});
}
