export function stockRows(items,source){
 return items.map(r=>({id:String(r.id||''),sku:String(r.sku||''),name:String(r.name||r.description||''),size:String(r.dimensions||`${r.widthFeet||0}' ${r.widthInches||0}" × ${r.lengthFeet||0}' ${r.lengthInches||0}"`),material:String(r.material||''),location:String(r.zone||r.location||''),status:String(r.availability||r.status||'Unknown'),photo:String(r.images?.[0]||r.image||''),source})).sort((a,b)=>a.sku.localeCompare(b.sku,undefined,{numeric:true})||a.id.localeCompare(b.id));
}
export const unsoldRow=r=>!['SOLD','Sold','Cancelled','Returned'].includes(r.status);
export function safePhoto(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)||/^data:image\/(png|jpeg|jpg|webp);base64,/i.test(value)?value:'';}catch{return '';}}
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function stockPrint(rows,source,at){
 return `<!doctype html><html><head><meta charset="utf-8"><title>Marco Polo stock check</title><style>body{font:12px Arial;color:#193e34;margin:24px}h1{font:26px Georgia;margin-bottom:6px}p{line-height:1.5}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:7px;text-align:left;vertical-align:top}thead{display:table-header-group}tr{break-inside:avoid}img{width:42px;height:58px;object-fit:contain}.check{width:46px;height:60px}.notes{min-width:70px}button{padding:12px;background:#193e34;color:white;border:0;border-radius:8px}@page{size:landscape;margin:12mm}@media print{button{display:none}body{margin:0}}</style></head><body><button id="print">Print / Save PDF</button><h1>Marco Polo Rugs — Physical stock check</h1><p>${escape(source)} · Snapshot: ${escape(at)} · ${rows.length} rugs<br>Checked by: ____________________ Date: ____________________<br>Mark one result per rug. Verify missing rugs against invoices, deliveries, approval and service records before changing status.</p><table><thead><tr><th>#</th><th>Photo</th><th>SKU / Rug</th><th>Size / Material</th><th>Location</th><th>System status</th><th>Found</th><th>Missing</th><th>Sold in person</th><th>Notes / invoice / initials</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${safePhoto(r.photo)?`<img src="${escape(safePhoto(r.photo))}" alt="">`:''}</td><td><strong>${escape(r.sku||'No SKU')}</strong><br>${escape(r.name)}<br><small>${escape(r.id)}</small></td><td>${escape(r.size)}<br>${escape(r.material)}</td><td>${escape(r.location)}</td><td>${escape(r.status)}</td><td class="check">□</td><td class="check">□</td><td class="check">□</td><td class="notes"></td></tr>`).join('')}</tbody></table></body></html>`;
}
export function stockExcelRows(rows){return rows.map((r,i)=>({'No.':i+1,SKU:r.sku,Rug:r.name,Size:r.size,Material:r.material,Location:r.location,'System status':r.status,Found:'',Missing:'','Sold in person':'','Notes / invoice':'','Checked by':'','Checked date':'','Photo link':/^https?:/.test(safePhoto(r.photo))?r.photo:'','Record ID':r.id,Source:r.source}));}
