'use client';
import {useEffect,useRef,useState} from 'react';
import {useStaffAccess} from '@/hooks/useStaffAccess';
import {canAccess} from '@/lib/access-policy';
import {pickupRequest} from '@/lib/service-pickup-client';
import styles from './Pickups.module.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const empty=()=>({name:'',phone:'',email:'',address:'',city:'Alexandria',state:'VA',zip:'',date:today(),time:'10:00',service:'cleaning',rugCount:0,assignedTo:'',notes:''});
const labels:any={scheduled:'Scheduled',picked_up:'Picked up — invoice needed',invoiced:'Invoice created',cancelled:'Cancelled'};
export default function PickupManager(){const {staff}=useStaffAccess(),write=canAccess(staff,'appointments','write');const [bookings,setBookings]=useState<any[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<any>(null),[show,setShow]=useState(false),[filter,setFilter]=useState('active'),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[more,setMore]=useState(false);const draftId=useRef('');const lock=useRef(false),operation=useRef<any>(null);
 async function load(){const d=await pickupRequest();setBookings(d.bookings);setMore(d.more);}useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),60000);return()=>clearInterval(t);},[]);
 async function action(body:any){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const serialized=JSON.stringify(body);if(operation.current?.serialized!==serialized)operation.current={serialized,id:crypto.randomUUID()};await pickupRequest('',{...body,requestId:operation.current.id});await load();operation.current=null;setMessage('Pickup booking saved to Firebase.');setShow(false);setEditing(null);window.dispatchEvent(new Event('pickup-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 const visible=bookings.filter(p=>(filter==='all'||filter==='active'&&['scheduled','picked_up'].includes(p.status)||p.status===filter)&&[p.name,p.phone,p.address,p.assignedTo].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 return <main className={styles.page}><div className={styles.header}><div><h1>Customer pickups</h1><p className={styles.muted}>Schedule collections for cleaning, repair or another service. All times are Alexandria / New York time.</p></div>{write&&<button onClick={()=>{setEditing(null);draftId.current=crypto.randomUUID();setForm(empty());setShow(true);}}>+ Schedule pickup</button>}</div>{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}
 {show&&<section className={styles.card}><h2>{editing?'Edit / reschedule pickup':'Schedule a customer pickup'}</h2><form onSubmit={e=>{e.preventDefault();action({action:editing?(editing.status==='cancelled'?'reschedule':'edit'):'create',id:editing?.id||draftId.current,version:editing?.version,fields:form});}}><fieldset disabled={busy} style={{border:0,padding:0}} className={styles.form}>{[['name','Customer name','text',true],['phone','Phone','tel',true],['email','Email (optional)','email',false],['address','Pickup street address','text',true],['city','City','text',true],['state','State','text',true],['zip','ZIP code','text',false],['date','Pickup date','date',true],['time','Pickup time','time',true],['assignedTo','Assigned driver / employee','text',false],['rugCount','Estimated number of rugs','number',false]].map(([key,label,type,required])=><label key={String(key)}>{label}<input required={!!required} type={String(type)} {...(type==='number'?{min:0,max:500}:{})} value={(form as any)[String(key)]} onChange={e=>setForm({...form,[String(key)]:type==='number'?Number(e.target.value):e.target.value})}/></label>)}<label>Requested service<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option value="cleaning">Cleaning / wash</option><option value="repair">Repair</option><option value="cleaning_repair">Cleaning &amp; repair</option><option value="other">Other service</option></select></label><label className={styles.wide}>Service details / access instructions<textarea maxLength={3000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Customer's request, parking, gate code, preferred call ahead…"/></label><div className={`${styles.actions} ${styles.wide}`}><button>Save pickup</button><button type="button" className={styles.secondary} onClick={()=>setShow(false)}>Close</button></div></fieldset></form></section>}
 <section className={styles.card}><div className={styles.form}><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active pickups</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{String(label)}</option>)}<option value="all">All / recent history</option></select></label><label>Search<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Customer, phone, address or driver"/></label></div><p className={styles.muted}>Active bookings are loaded separately. Completed and cancelled history shows up to 100 recent bookings; records remain saved in Firebase.</p>{more&&<p className={styles.error}>More than 500 active bookings. This view is limited; contact management for a full export.</p>}{!visible.length&&<p className={styles.muted}>No pickups match this view.</p>}{visible.map(p=><article key={p.id} className={styles.row}><div><span className={`${styles.badge} ${p.status==='scheduled'&&p.date<today()?styles.urgent:''}`}>{labels[p.status]}{p.status==='scheduled'&&p.date<today()?' · Overdue':''}</span><h3>{p.name}</h3><p>{p.date} · {p.time} · {p.service.replaceAll('_',' ')}{p.rugCount?' · '+p.rugCount+' rugs estimated':''}</p><p><a href={'tel:'+p.phone}>{p.phone}</a><br/>{p.address}, {p.city}, {p.state} {p.zip}</p>{p.assignedTo&&<p>Assigned: {p.assignedTo}</p>}{p.notes&&<p className={styles.muted} style={{whiteSpace:'pre-wrap'}}>{p.notes}</p>}{p.cancellationReason&&<p className={styles.muted}>Cancelled: {p.cancellationReason}</p>}</div><div className={styles.actions}>{write&&['scheduled','picked_up','cancelled'].includes(p.status)&&<button className={styles.secondary} disabled={busy} onClick={()=>{setEditing(p);setForm({...empty(),...p});setShow(true);window.scrollTo({top:0,behavior:'smooth'});}}>{p.status==='picked_up'?'Edit details':'Edit / reschedule'}</button>}{write&&p.status==='scheduled'&&<><button disabled={busy} onClick={()=>action({action:'picked_up',id:p.id,version:p.version})}>Mark picked up</button><button className={styles.secondary} disabled={busy} onClick={()=>{const reason=window.prompt('Why is this pickup cancelled?');if(reason)action({action:'cancel',id:p.id,version:p.version,reason});}}>Cancel pickup</button></>}{write&&p.status==='picked_up'&&canAccess(staff,'invoices','write')&&<a className={styles.button} href={'/admin/invoices/invoices/new?pickup='+encodeURIComponent(p.id)}>Create invoice →</a>}{p.invoiceId&&canAccess(staff,'invoices')&&<a className={styles.button} href={'/admin/invoices/invoices/new?edit='+encodeURIComponent(p.invoiceId)}>Open invoice {p.invoiceNumber}</a>}</div></article>)}</section></main>;
}
