import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import * as products from '../../lib/service-products.mjs';
const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/calculations.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:()=>products});const calc=exports.calculateInvoice;
const base={invoiceNumber:'TEST',date:'2026-10-05',terms:'',soldTo:{name:'Test'},mode:'wash',documentType:'WASH',items:[{id:'rug',sku:'MPW0001',description:'Washing',shape:'rectangle',widthFeet:1,widthInches:0,lengthFeet:1,lengthInches:0,fixedPrice:100}]};const pad={id:'pad',description:'Padding',quantity:1,unitPrice:50,taxable:true};
test('mixed service invoice charges tax only on separately priced products',()=>{const r=calc({...base,serviceProducts:[pad]});assert.equal(r.subtotal,150);assert.equal(r.salesTax,3);assert.equal(r.totalDue,153);assert.equal(r.balanceDue,153);assert.equal(r.items.length,1);assert.equal(base.items[0].sku,'MPW0001');});
test('service discounts and lump sums never silently change product price or tax',()=>{const r=calc({...base,serviceProducts:[pad],discountValue:10,discountType:'percentage'});assert.equal(r.discount,10);assert.equal(r.totalDue,143);const lump=calc({...base,isLumpSum:true,lumpSumAmount:80,serviceProducts:[pad]});assert.equal(lump.totalDue,133);});
test('quantities, tax exemption, returns and payments remain correct',()=>{assert.equal(calc({...base,serviceProducts:[{...pad,quantity:2}]}).totalDue,206);assert.equal(calc({...base,serviceProducts:[{...pad,taxable:false}]}).totalDue,150);const r=calc({...base,serviceProducts:[{...pad,returned:true}],payments:[{amount:100}]});assert.equal(r.netTotalDue,100);assert.equal(r.returnedAmount,53);assert.equal(r.balanceDue,0);});
test('product amounts round in cents and invalid quantities or prices cannot become totals',()=>{assert.equal(products.calculateServiceProducts([{...pad,unitPrice:19.99,quantity:3}]).tax,3.6);for(const p of [{...pad,quantity:0},{...pad,quantity:1.5},{...pad,unitPrice:NaN},{...pad,unitPrice:-1}])assert.throws(()=>products.calculateServiceProducts([p]));});
test('old service invoices retain zero tax and old retail invoices keep their existing tax',()=>{assert.equal(calc(base).totalDue,100);assert.equal(calc(base).salesTax,0);assert.equal(calc({...base,serviceProducts:[]}).totalDue,100);assert.equal(calc({...base,mode:'retail',documentType:'INVOICE'}).totalDue,106);});
test('customer invoice includes products and hides private product metadata',async()=>{const {customerInvoice}=await import('../../lib/server/invoice-share.mjs');const d=customerInvoice({...base,serviceProducts:[{...pad,internalCost:10}]});assert.equal(d.serviceProducts[0].unitPrice,50);assert.equal(d.serviceProducts[0].internalCost,undefined);assert.equal(calc(d).totalDue,153);});
