import test from 'node:test';import assert from 'node:assert/strict';
import {database} from '../auction/helpers/database.mjs';
import {pickupFields,pickupPrefill,changePickup,createPickupInvoice} from '../../lib/service-pickups.mjs';
const fields={name:'Customer',phone:'703-555-0123',email:'customer@example.test',address:'123 Main Street',city:'Alexandria',state:'VA',zip:'22314',date:'2026-10-07',time:'10:30',service:'cleaning_repair',rugCount:3,assignedTo:'Driver',notes:'Call before arriving.'};
const create={action:'create',id:'pickup-0000001',requestId:'request-0000001',fields};
const advance=(action,version,extra={})=>({action,id:create.id,requestId:'request-'+action+'-'+version,version,...extra});
const invoice={invoiceNumber:'MP00000100',sourcePickupId:create.id,sourcePickupVersion:2,soldTo:{name:'Customer'},date:'2026-10-07',items:[{id:'rug'}]};
test('booking fields validate dates, local time, customer contact and rug count',()=>{assert.equal(pickupFields(fields).date,'2026-10-07');for(const f of [{date:'2026-02-31'},{time:'25:00'},{name:''},{phone:'123'},{rugCount:-1},{email:'wrong'},{service:'unknown'}])assert.throws(()=>pickupFields({...fields,...f}));});
test('schedule is cloud-backed, retry-safe and records who booked it',async()=>{const db=database();await changePickup(db,create,'staff',1000);await changePickup(db,create,'staff',1001);assert.equal(db.read('service_pickup_bookings/'+create.id).version,1);assert.equal(db.read('service_pickup_bookings/'+create.id).createdBy,'staff');await assert.rejects(()=>changePickup(db,{...create,fields:{...fields,phone:'7035559999'}},'staff'),/Request changed/);});
test('concurrent collection and cancellation cannot overwrite each other',async()=>{const db=database();await changePickup(db,create,'staff');const results=await Promise.allSettled([changePickup(db,advance('picked_up',1),'staff'),changePickup(db,advance('cancel',1,{reason:'Customer requested cancellation.'}),'staff')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(db.read('service_pickup_bookings/'+create.id).status,'picked_up');});
test('rescheduling keeps booking identity and cancelled bookings stay in history',async()=>{const db=database();await changePickup(db,create,'staff');await changePickup(db,advance('cancel',1,{reason:'Customer needs another day.'}),'staff');await changePickup(db,advance('reschedule',2,{fields:{...fields,date:'2026-10-10'}}),'staff');assert.equal(db.read('service_pickup_bookings/'+create.id).date,'2026-10-10');assert.equal(db.read('service_pickup_bookings/'+create.id).status,'scheduled');assert.equal(db.keys().filter(k=>k.includes('/history/')).length,3);});
test('pickup details prefill service invoice without inventing rug prices or a ready date',()=>{const p=pickupPrefill({...fields,id:create.id});assert.equal(p.soldTo.name,fields.name);assert.equal(p.soldTo.phone,fields.phone);assert.equal(p.documentType,'WASH');assert.equal(p.mode,'wash');assert.match(p.notes,/Call before arriving/);assert.equal(p.pickupDate,undefined);assert.equal(p.items,undefined);});
test('invoice cannot be created before collection; number and booking link commit together',async()=>{const db=database();await changePickup(db,create,'staff');await assert.rejects(()=>createPickupInvoice(db,{pickupId:create.id,data:invoice,total:100,actor:'staff'}),/picked up|details changed/);await changePickup(db,advance('picked_up',1),'staff');const result=await createPickupInvoice(db,{pickupId:create.id,data:invoice,total:100,actor:'staff'});assert.equal(db.read('service_pickup_bookings/'+create.id).status,'invoiced');assert.equal(db.read('service_pickup_bookings/'+create.id).invoiceId,result.id);assert.equal(db.read('invoices/'+result.id).totalAmount,100);assert.equal(db.read('counters/invoice-number-invoices%3AMP00000100').invoiceId,result.id);});
test('double-clicks and competing tabs cannot create duplicate invoices for one pickup',async()=>{const db=database();await changePickup(db,create,'staff');await changePickup(db,advance('picked_up',1),'staff');const args={pickupId:create.id,data:invoice,total:100,actor:'staff'};const [a,b]=await Promise.all([createPickupInvoice(db,args),createPickupInvoice(db,args)]);assert.equal(a.id,b.id);await assert.rejects(()=>createPickupInvoice(db,{...args,data:{...invoice,invoiceNumber:'MP00000101'}}),/already has an invoice/);assert.equal(db.keys().filter(k=>k.startsWith('invoices/')).length,1);await assert.rejects(()=>changePickup(db,advance('edit',3,{fields}),'staff'),/linked invoice/);});
test('an occupied invoice number rolls back booking linkage',async()=>{const db=database({'counters/invoice-number-invoices%3AMP00000100':{invoiceId:'other'}});await changePickup(db,create,'staff');await changePickup(db,advance('picked_up',1),'staff');await assert.rejects(()=>createPickupInvoice(db,{pickupId:create.id,data:invoice,total:100,actor:'staff'}),/already used/);assert.equal(db.read('service_pickup_bookings/'+create.id).status,'picked_up');assert.equal(db.keys().filter(k=>k.startsWith('invoices/')).length,0);});

test('changed customer details cannot silently enter an invoice from an older prefill',async()=>{const db=database();await changePickup(db,create,'staff');await changePickup(db,advance('picked_up',1),'staff');await changePickup(db,advance('edit',2,{fields:{...fields,address:'456 Updated Street'}}),'other-staff');await assert.rejects(()=>createPickupInvoice(db,{pickupId:create.id,data:invoice,total:100,actor:'staff'}),/details changed/);assert.equal(db.read('service_pickup_bookings/'+create.id).status,'picked_up');});
