import {NextResponse} from 'next/server';
import {getStorage} from 'firebase-admin/storage';
import {randomUUID} from 'node:crypto';
import {adminApp,serverDb} from '@/lib/server/firebase-admin';
import {requireStaff} from '@/lib/server/staff-permission';
import {WashError} from '@/lib/server/washing.mjs';
import {digest,validateFile,pickup,readInvoice,compareInvoice,extraction,checkConfirmation} from '@/lib/server/washing-invoices.mjs';
export const dynamic='force-dynamic';export const runtime='nodejs';export const maxDuration=60;
const headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer'};
const reply=(v:any,status=200)=>NextResponse.json(v,{status,headers});
const id=(v:any)=>{if(typeof v!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(v))throw new WashError('Invalid record.');return v;};
const bucket=()=>{const name=process.env.FIREBASE_STORAGE_BUCKET||process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;if(!name)throw new WashError('Set the Firebase Storage bucket in Vercel to save invoice files.',503);return getStorage(adminApp()).bucket(name);};
const records=()=>serverDb().collection('wash_tracking_pickup_invoices');
function safe(d:any){const {storagePath,...v}=d.data();return {...v,id:d.id};}
async function staff(r:Request,write=false){if(r.headers.has('x-wash-link'))throw new WashError('Invoice files are for showroom staff only.',403);return requireStaff(r,'services',write?'write':'read');}
export async function GET(r:Request){try{await staff(r);const url=new URL(r.url),download=url.searchParams.get('download');
 if(download){const d=await records().doc(id(download)).get();if(!d.exists)throw new WashError('Invoice not found.',404);const x=d.data()!;const [bytes]=await bucket().file(x.storagePath).download();return new Response(new Uint8Array(bytes),{headers:{...headers,'Content-Type':x.type,'Content-Disposition':'attachment; filename="'+x.name.replace(/[^a-zA-Z0-9._-]/g,'_')+'"','X-Content-Type-Options':'nosniff'}});}
 const anchor=url.searchParams.get('anchor');if(anchor){const expected=await pickup(serverDb(),id(anchor)),result=await records().where('batchKey','==',expected.key).limit(101).get();return reply({expected,invoices:result.docs.slice(0,100).map(safe),more:result.size>100,aiConfigured:!!process.env.OPENAI_API_KEY});}
 let q:any=records();const company=url.searchParams.get('company'),cursor=url.searchParams.get('cursor');if(company)q=q.where('companyId','==',id(company));if(cursor){const s=await records().doc(id(cursor)).get();if(!s.exists||company&&s.data()?.companyId!==company)throw new WashError('Invalid page.');q=q.startAfter(s);}const result=await q.limit(51).get(),docs=result.docs.slice(0,50);return reply({invoices:docs.map(safe),nextCursor:result.size>50?docs.at(-1)!.id:null});
 }catch(e){return failure(e);}}
export async function POST(r:Request){try{
 if(r.headers.get('origin')&&r.headers.get('origin')!==new URL(r.url).origin)throw new WashError('Use the showroom website.',403);const user=await staff(r,true),db=serverDb(),now=new Date().toISOString();
 if(r.headers.get('content-type')?.includes('multipart/form-data')){
  if(Number(r.headers.get('content-length')||0)>3200000)throw new WashError('Upload up to 3 MB.');const form=await r.formData(),file=form.get('file');if(!(file instanceof File)||file.size>3000000)throw new WashError('Select a PDF or photo up to 3 MB.');const expected=await pickup(db,id(form.get('anchor'))),bytes=Buffer.from(await file.arrayBuffer()),type=validateFile(bytes,file.type),hash=digest(bytes),ref=records().doc(digest(expected.key+':'+hash)),storagePath='washing-private-invoices/'+expected.key+'/'+hash;
  const exists=await ref.get();if(exists.exists)return reply({invoice:safe(exists),duplicate:true});
  await bucket().file(storagePath).save(bytes,{resumable:false,metadata:{contentType:type,cacheControl:'private, no-store'},preconditionOpts:{ifGenerationMatch:0}}).catch((e:any)=>{if(e.code!==412)throw e;});
  await db.runTransaction(async tx=>{if((await tx.get(ref)).exists)return;tx.create(ref,{batchKey:expected.key,anchorId:expected.anchorId,companyId:expected.companyId,companyName:expected.companyName,pickupDate:expected.date,batchLabel:expected.label,expected,name:file.name.slice(0,120),type,size:bytes.length,hash,storagePath,status:'Needs review',version:1,createdAt:now,createdBy:user.uid});tx.create(ref.collection('history').doc(),{action:'Uploaded',at:now,by:user.uid});});return reply({invoice:safe(await ref.get())});
 }
 const raw=await r.text();if(raw.length>200000)throw new WashError('Review too large.');const b=JSON.parse(raw),ref=records().doc(id(b.id));
 if(b.action==='review'){
  const lease=randomUUID();let saved:any;const claimed=await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new WashError('Invoice not found.',404);saved=s.data();if(['Checked','Review ready'].includes(saved.status))return false;if(saved.leaseUntil>Date.now())throw new WashError('AI is already checking this invoice. Refresh shortly.',409);tx.update(ref,{lease,leaseUntil:Date.now()+55000,status:'AI checking',version:saved.version+1});return true;});if(!claimed)return reply({invoice:safe(await ref.get())});
  try{const [bytes]=await bucket().file(saved.storagePath).download(),result=await readInvoice(bytes,saved.type,saved.name),comparison=compareInvoice(saved.expected,result.extracted);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(s.data()?.lease!==lease)throw new WashError('Review changed. Refresh.',409);tx.update(ref,{...result,comparison,status:'Review ready',lease:'',leaseUntil:0,version:s.data()!.version+1,reviewedAt:now,reviewedBy:user.uid,error:''});tx.create(ref.collection('history').doc(),{action:'AI reviewed',at:now,by:user.uid,model:result.model,extracted:result.extracted,comparison});});}
  catch(e:any){await db.runTransaction(async tx=>{const s=await tx.get(ref);if(s.data()?.lease===lease)tx.update(ref,{status:'Needs review',lease:'',leaseUntil:0,error:(e instanceof WashError||e?.name==='InvoiceReviewError')?e.message:'AI review failed. Original invoice is saved.',version:s.data()!.version+1});});throw e;}
  return reply({invoice:safe(await ref.get())});
 }
 if(!['save','confirm'].includes(b.action))throw new WashError('Choose a review action.');
 await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new WashError('Invoice not found.',404);const x=s.data()!;if(x.version!==b.version)throw new WashError('Invoice changed. Refresh before saving.',409);if(x.status==='Checked')throw new WashError('This invoice is checked. Upload a revised invoice as another file.',409);if(x.leaseUntil>Date.now())throw new WashError('Wait for the AI review to finish.',409);const expected=await pickup(db,x.anchorId,tx);if(expected.key!==x.batchKey||digest(JSON.stringify(expected.rugs))!==digest(JSON.stringify(x.expected.rugs)))throw new WashError('Pickup rugs changed. Re-upload the corrected invoice for review.',409);const extracted=extraction(b.extracted),comparison=compareInvoice(expected,extracted),checked=b.action==='confirm'?checkConfirmation(expected,extracted,b):{};tx.update(ref,{extracted,comparison,...checked,status:b.action==='confirm'?'Checked':'Review ready',version:x.version+1,updatedAt:now,updatedBy:user.uid,...(b.action==='confirm'?{checkedAt:now,checkedBy:user.uid}:{})});tx.create(ref.collection('history').doc(),{action:b.action==='confirm'?'Checked':'Review corrected',by:user.uid,at:now,extracted,comparison,...checked});});return reply({invoice:safe(await ref.get())});
 }catch(e){return failure(e);}}
function failure(e:any){const m=e instanceof Error?e.message:'';return reply({error:(e instanceof WashError||e?.name==='InvoiceReviewError')?m:m==='FORBIDDEN'?'You need permission for this section.':/SIGN_IN_REQUIRED|auth\//.test(m)?'Please sign in again.':'Could not save or load the invoice. Please retry.'},(e instanceof WashError||e?.name==='InvoiceReviewError')?e.status:m==='FORBIDDEN'?403:/SIGN_IN_REQUIRED|auth\//.test(m)?401:503);}
