import {NextResponse} from 'next/server';
import {createHash} from 'node:crypto';
import {requireStaff} from '@/lib/server/staff-permission';
import {serverDb} from '@/lib/server/firebase-admin';
import {auctionFailure} from '@/lib/server/auction-errors';
import {check} from '@/lib/auction/engine.mjs';
import {DEFAULT_SETTINGS,AUCTION_SETTINGS,SANDBOX_INVOICES,SANDBOX_SALES,validateSettings,buildInvoices,termsText,storageSummary,validDate,nyDate} from '@/lib/auction/settlement.mjs';
export const runtime='nodejs';export const dynamic='force-dynamic';
const valid=(s:any)=>typeof s==='string'&&/^[\w-]{1,100}$/.test(s);
export async function GET(req:Request){try{await requireStaff(req,'settings','read');const db=serverDb();const [config,invoices,lots,bidders]=await Promise.all([db.doc(AUCTION_SETTINGS+'/current').get(),db.collection(SANDBOX_INVOICES).orderBy('createdAt','desc').limit(101).get(),db.collection('auction_sandbox_lots').orderBy('createdAt','desc').limit(101).get(),db.collection('auction_profiles').limit(101).get()]);const settings=config.data()||DEFAULT_SETTINGS;
 return NextResponse.json({bidders:bidders.docs.slice(0,100).map(d=>({id:d.id,bidderNumber:d.data().bidderNumber||'',name:[d.data().firstName,d.data().lastName].filter(Boolean).join(' '),email:d.data().email||'',phone:d.data().phone||'',accountStatus:d.data().accountStatus||'active',savedSearchCount:d.data().savedSearches?.length||0})),moreBidders:bidders.size>100,settings,terms:termsText(settings),invoices:invoices.docs.slice(0,100).map(d=>({...d.data(),id:d.id,storage:storageSummary(d.data())})),lots:lots.docs.slice(0,100).map(d=>({id:d.id,sourceAuction:d.data().sourceAuction||d.id,title:d.data().title,status:d.data().status,mode:d.data().mode})),moreInvoices:invoices.size>100,moreLots:lots.size>100,publicEnabled:false,liveChargingEnabled:false},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return auctionFailure(e);}}
export async function POST(req:Request){let user;try{user=await requireStaff(req,'settings','write');}catch(e){return auctionFailure(e);}try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return NextResponse.json({error:'Use the auction management website.'},{status:403});const text=await req.text();check(text.length<=20000,'Request too large.');const b=JSON.parse(text);check(valid(b.requestId),'Invalid operation reference.');const db=serverDb(),fingerprint=createHash('sha256').update(text).digest('hex'),event=db.doc('auction_operations_v2/'+b.requestId);let result:any={saved:true};
 await db.runTransaction(async tx=>{const prior=await tx.get(event);if(prior.exists){check(prior.data()?.actor===user.uid&&prior.data()?.fingerprint===fingerprint,'Operation conflict.');result=prior.data()?.result;return;}
 const at=Date.now();
 if(b.action==='settings'){
  const ref=db.doc(AUCTION_SETTINGS+'/current'),old=(await tx.get(ref)).data()||DEFAULT_SETTINGS;check(b.version===old.version,'Settings changed. Refresh before saving.');const settings=validateSettings(b,old.version);tx.set(ref,{...settings,updatedAt:at,updatedBy:user.uid});tx.create(ref.collection('versions').doc(String(settings.version)),{before:old,after:settings,actor:user.uid,at});result={saved:true,policyVersion:settings.policyVersion};
 }else if(b.action==='bidder_status'){
  check(valid(b.id)&&['active','suspended'].includes(b.status),'Choose a bidder status.');check(typeof b.reason==='string'&&b.reason.trim().length>=10&&b.reason.length<=500,'Record a bidder status reason (10–500 characters).');const ref=db.doc('auction_profiles/'+b.id),old=(await tx.get(ref)).data();check(old,'Bidder profile not found.');tx.set(ref,{accountStatus:b.status,statusReason:b.reason.trim(),statusUpdatedAt:at,statusUpdatedBy:user.uid},{merge:true});tx.create(ref.collection('events').doc(b.requestId),{action:'status',before:old!.accountStatus||'active',after:b.status,reason:b.reason.trim(),actor:user.uid,at});
 }else if(b.action==='consolidate'){
  check(valid(b.auctionId),'Choose a test auction.');const seal=db.doc(SANDBOX_SALES+'/'+b.auctionId);check(!(await tx.get(seal)).exists,'This auction already has consolidated invoices.');const config=(await tx.get(db.doc(AUCTION_SETTINGS+'/current'))).data()||DEFAULT_SETTINGS;
  const records=await tx.get(db.collection('auction_sandbox_lots').where('sourceAuction','==',b.auctionId).limit(101));let lots=records.docs.map(d=>({...d.data(),id:d.id}));if(!lots.length){const single=await tx.get(db.doc('auction_sandbox_lots/'+b.auctionId));check(single.exists&&!single.data()?.sourceAuction,'No test lots found.');lots=[{...single.data(),id:single.id}];}
  const invoices=buildInvoices(b.auctionId,lots,config,at);const refs=invoices.map(i=>db.doc(SANDBOX_INVOICES+'/'+i.id));const snapshots=refs.length?await tx.getAll(...refs):[];check(snapshots.every(s=>!s.exists),'A winning invoice already exists.');
  invoices.forEach((i,index)=>{tx.create(refs[index],i);i.items.forEach((item:any)=>tx.update(db.doc('auction_sandbox_lots/'+item.lotId),{consolidatedInvoiceId:i.id}));});tx.create(seal,{invoiceIds:invoices.map(i=>i.id),lotIds:lots.map(l=>l.id),closedAt:at,createdBy:user.uid,mode:'sandbox'});result={saved:true,invoiceCount:invoices.length};
 }else{
  check(valid(b.id),'Choose an invoice.');const ref=db.doc(SANDBOX_INVOICES+'/'+b.id),snap=await tx.get(ref),invoice=snap.data();check(snap.exists&&invoice?.mode==='sandbox','Test invoice not found.');check(invoice!.version===b.version,'Invoice changed. Refresh before continuing.');let update:any={};
  if(['paid','declined','requires_action'].includes(b.action)){
   check(invoice!.paymentStatus!=='paid'&&invoice!.paymentStatus!=='processing'&&!invoice!.paymentIntentId,'A paid or provider-managed invoice cannot be simulated again.');update={paymentStatus:b.action==='paid'?'paid':b.action==='declined'?'failed':'requires_action',paymentFailure:b.action==='paid'?'':b.action==='declined'?'Simulated card decline — unpaid invoice remains due.':'Simulated bank authentication required.',...(b.action==='paid'?{paidAt:at}:{})};
  }else if(b.action==='ready'){
   check(invoice!.paymentStatus==='paid'&&invoice!.delivery.method!=='shipping'&&!invoice!.readyDate,'Only paid pickup invoices can start their collection window.');update={readyDate:nyDate(at),readyAt:at,readyBy:user.uid};
  }else if(b.action==='collect'){
   check(invoice!.paymentStatus==='paid'&&invoice!.readyDate,'Verify payment and mark ready before collecting.');check(Array.isArray(b.lotIds)&&b.lotIds.length>0&&b.lotIds.length<=100&&new Set(b.lotIds).size===b.lotIds.length&&b.lotIds.every((id:any)=>invoice!.items.some((i:any)=>i.lotId===id&&!i.collectedDate)),'Choose uncollected invoice rugs.');check(typeof b.reference==='string'&&b.reference.trim().length>=3&&b.reference.length<=200,'Record a pickup identity / receipt reference.');update={items:invoice!.items.map((i:any)=>b.lotIds.includes(i.lotId)?{...i,collectedDate:nyDate(at),collectedBy:user.uid,reference:b.reference.trim()}:i)};
  }else if(b.action==='waive'){
   check(typeof b.reason==='string'&&b.reason.trim().length>=10&&b.reason.length<=500,'Record a waiver reason (10–500 characters).');const amount=Number(b.amount);check(Number.isSafeInteger(amount)&&amount>=0&&amount<=storageSummary({...invoice,storageWaiverCents:0},at).grossCents,'Waiver exceeds accrued storage.');update={storageWaiverCents:amount,storageWaiverReason:b.reason.trim()};
  }else throw Error('Unsupported action.');
  tx.update(ref,{...update,version:invoice!.version+1,updatedAt:at});tx.create(ref.collection('events').doc(b.requestId),{action:b.action,actor:user.uid,at,beforeVersion:invoice!.version,before:{paymentStatus:invoice!.paymentStatus,readyDate:invoice!.readyDate,storageWaiverCents:invoice!.storageWaiverCents},after:update,...(b.reason?{reason:b.reason}:{})});
 }
 tx.create(event,{fingerprint,actor:user.uid,at,action:b.action,result});});return NextResponse.json(result);
 }catch(e){if(e instanceof Error&&!(e as any).code)return NextResponse.json({error:e.message},{status:400});return auctionFailure(e);}}
