'use client';
import {useEffect,useState,FormEvent,useRef} from 'react';
import {getAuth} from 'firebase/auth';
import {app} from '@/lib/firebase';
import LotManagement from './LotManagement';
import StaffGate from '@/components/StaffGate';
import {increment} from '@/lib/auction/engine.mjs';
import styles from './Auction.module.css';
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);
const localDate=(n:number)=>{const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
async function api(query='',body?:object){const auth=getAuth(app);await auth.authStateReady();const user=auth.currentUser;if(!user||user.isAnonymous)throw Error('Please sign in as staff.');const response=await fetch('/api/auction/sandbox'+query,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+await user.getIdToken(),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Operation failed.');return data;}
export default function AuctionAdmin(){return <StaffGate section="settings"><AuctionWorkspace/></StaffGate>;}
function AuctionWorkspace(){const [tab,setTab]=useState('catalog');return <>{tab==='catalog'?<main className={styles.page}><a href="/?view=admin">← Showroom admin</a><p className={styles.eyebrow}>Marco Polo Rugs</p><h1>Auction management</h1><div className={styles.actions}><button aria-pressed>Catalog &amp; lots</button><button className={styles.secondary} onClick={()=>setTab('test')}>Bidding test lab</button><a className={`${styles.button} ${styles.secondary}`} href="/auctions/register">Bidder registration</a></div><LotManagement/></main>:<><div className={styles.page} style={{minHeight:0,paddingBottom:0}}><button className={styles.secondary} onClick={()=>setTab('catalog')}>← Catalog &amp; lots</button></div><Workspace/></>}</>;}

function Workspace(){
 const [lots,setLots]=useState<any[]>([]),[rugs,setRugs]=useState<any[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[now,setNow]=useState(Date.now()),[search,setSearch]=useState('');
 const lastOperation=useRef<{body:string;id:string}|null>(null);
 const active=useRef(false),offset=useRef(0),selection=useRef('');
 const [form,setForm]=useState({rugId:'',title:'',condition:'',starting:'50',reserve:'0',loading:'0',startAt:localDate(Date.now()),endAt:localDate(Date.now()+15*60000)});
 const [bid,setBid]=useState({bidderId:'test-a',maximum:'',method:'pickup_self',address:''}),[reason,setReason]=useState(''),[reference,setReference]=useState('');
 async function refresh(){const data=await api();setLots(data.lots);offset.current=data.serverNow-Date.now();setNow(data.serverNow);setLoaded(true);}
 async function choose(id:string){selection.current=id;setSelected(id);setDetail(null);setError('');try{const data=await api('?id='+encodeURIComponent(id));if(selection.current===id){setDetail(data);offset.current=data.serverNow-Date.now();}}catch(e){setError(e instanceof Error?e.message:'Could not load lot.');}}
 useEffect(()=>{Promise.all([refresh(),api('?inventory=1').then(d=>setRugs(d.rugs))]).catch(e=>setError(e.message));const timer=setInterval(()=>setNow(Date.now()+offset.current),1000);return()=>clearInterval(timer);},[]);
 async function operate(body:object,created=false){if(active.current)return;active.current=true;setBusy(true);setError('');setMessage('');try{const serialized=JSON.stringify(body);if(lastOperation.current?.body!==serialized)lastOperation.current={body:serialized,id:crypto.randomUUID()};const data=await api('',{...body,requestId:lastOperation.current.id});await refresh();await choose(created?data.id:selected);lastOperation.current=null;setMessage('Sandbox operation saved. No real payment or inventory change.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);active.current=false;}}
 function create(e:FormEvent){e.preventDefault();operate({action:'create',rugId:form.rugId,title:form.title,condition:form.condition,startingCents:Math.round(Number(form.starting)*100),reserveCents:Math.round(Number(form.reserve)*100),loadingCents:Math.round(Number(form.loading)*100),startAt:new Date(form.startAt).getTime(),endAt:new Date(form.endAt).getTime()},true);}
 const lot=detail?.lot;
 const open=lot?.status==='scheduled'&&now>=lot.startAt&&now<lot.endAt;
 return <main className={styles.page}><a href="/?view=admin">← Showroom admin</a><p className={styles.eyebrow}>Marco Polo Rugs · Auction management</p><h1>Your auction workspace.</h1><div className={styles.notice}><strong>Staff sandbox only.</strong> Public bidding and card verification are disabled. The three test bidders are fictional. Test lots do not reserve, sell or change showroom inventory. No payment provider, SMS or customer email is called.</div>
 <div className={styles.grid}>{[['Test lots',lots.length],['Scheduled',lots.filter(l=>l.status==='scheduled').length],['Test wins unpaid',lots.filter(l=>l.status==='sold'&&l.paymentStatus!=='paid').length]].map(([label,value])=><div className={styles.card} key={label}><span className={styles.stat}>{value}</span>{label}</div>)}</div>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}
 <details className={styles.card}><summary>Create a test lot from inventory</summary><form onSubmit={create}><fieldset disabled={busy} className={styles.form}>
 <label className={styles.wide}>Inventory rug (up to 500 items)<select required value={form.rugId} onChange={e=>{const rug=rugs.find(r=>r.id===e.target.value);setForm({...form,rugId:e.target.value,title:rug?.name||''});}}><option value="">Choose a rug</option>{rugs.map(r=><option key={r.id} value={r.id}>{r.sku?r.sku+' · ':''}{r.name}</option>)}</select></label>
 <label className={styles.wide}>Auction title<input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
 <label className={styles.wide}>Condition report<textarea required minLength={10} maxLength={3000} placeholder="Wear, repairs, stains, fringes and any defects…" value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}/></label>
 {([['starting','Starting bid ($)'],['reserve','Reserve ($; 0 = none)'],['loading','Assisted loading ($)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" required min={key==='starting'?1:0} max="1000000" step="0.01" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
 <label>Buyer’s premium<input disabled value="0% — no premium"/></label>
 {(['startAt','endAt'] as const).map(key=><label key={key}>{key==='startAt'?'Opens':'Closes'} (your local time)<input type="datetime-local" required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
 <p className={`${styles.muted} ${styles.wide}`}>Use a short closing time to test the full lifecycle. Bids in the last two minutes extend the closing time to two minutes after that bid. Terms are draft test settings, not published auction terms.</p><button type="submit" className={styles.wide}>Create sandbox draft</button></fieldset></form></details>
 <div className={styles.split} style={{marginTop:24}}><aside className={styles.card}><div className={styles.row}><h2>Test lots</h2><button className={styles.secondary} disabled={busy} onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh</button></div><label>Search title / SKU<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a test lot…"/></label>{!loaded&&!error&&<p>Loading…</p>}{loaded&&!lots.length&&<p>No test lots yet. Create your first sandbox draft above.</p>}{lots.filter(l=>(l.title+' '+l.snapshot?.sku).toLowerCase().includes(search.toLowerCase())).map(l=><button key={l.id} className={styles.lot} aria-pressed={selected===l.id} disabled={busy} onClick={()=>choose(l.id)}><strong>{l.title}</strong><br/><small>{l.status} · {money(l.currentCents)} · {l.bidCount} bid submissions</small></button>)}<p className={styles.muted}>Showing the latest 100 test lots.</p></aside>
 <section className={styles.card}>{!lot?<><h2>Select a test lot</h2><p>Inspect bids, simulate a winner’s payment and record test fulfillment here.</p></>:<><span className={styles.badge}>{lot.status} · Sandbox</span><h2 style={{marginTop:16}}>{lot.title}</h2><p>{lot.condition}</p>{lot.snapshot.image && <img src={lot.snapshot.image} alt={lot.title} style={{width:"100%",maxHeight:300,objectFit:"contain",background:"#f7f5f0",borderRadius:8}}/>}<p className={styles.muted}>SKU {lot.snapshot.sku||'—'} · Origin {lot.snapshot.origin||'Not recorded'} · {lot.snapshot.size||'See inventory for measurements'}</p><div className={styles.price}>{money(lot.currentCents)}</div><p>{lot.leaderId?'Leading: '+lot.leaderId:'No bids yet'} · {lot.bidCount} bid submissions</p><p>Closes {new Date(lot.endAt).toLocaleString()}<br/>{lot.status==='scheduled'?(now<lot.startAt?'Not started':now>=lot.endAt?'Closed — ready to finalize':Math.ceil((lot.endAt-now)/1000)+' seconds remaining'):''}</p><p className={styles.muted}>Reserve: {money(lot.reserveCents)} · Loading assistance: {money(lot.loadingCents)} · Free padding included</p>
 <div className={styles.actions}>{lot.status==='draft'&&<button disabled={busy} onClick={()=>operate({action:'schedule',id:selected})}>Schedule test lot</button>}{lot.status==='scheduled'&&now>=lot.endAt&&<button disabled={busy} onClick={()=>operate({action:'close',id:selected})}>Finalize result</button>}<button className={styles.secondary} disabled={busy} onClick={()=>choose(selected)}>Refresh lot</button></div>
 {open&&<form onSubmit={e=>{e.preventDefault();operate({action:'bid',id:selected,bidderId:bid.bidderId,maximumCents:Math.round(Number(bid.maximum)*100),delivery:{method:bid.method,address:bid.address}});}}><fieldset disabled={busy} className={styles.form}><h3 className={styles.wide}>Simulate a maximum bid</h3><label>Fictional bidder<select value={bid.bidderId} onChange={e=>setBid({...bid,bidderId:e.target.value})}>{['test-a','test-b','test-c'].map(id=><option key={id}>{id}</option>)}</select></label><label>Maximum bid ($)<input type="number" required min="1" step="0.01" value={bid.maximum} onChange={e=>setBid({...bid,maximum:e.target.value})}/></label><label className={styles.wide}>Delivery choice<select value={bid.method} onChange={e=>setBid({...bid,method:e.target.value})}><option value="pickup_self">Pickup — customer loads</option><option value="pickup_assisted">Pickup — Marco Polo assists</option><option value="shipping">Shipping — simulated choice only</option></select></label>{bid.method==='shipping'&&<label className={styles.wide}>Fictional shipping address<input required minLength={10} value={bid.address} onChange={e=>setBid({...bid,address:e.target.value})}/></label>}<p className={`${styles.muted} ${styles.wide}`}>Next challenger minimum: {money(lot.bidCount?lot.currentCents+increment(lot.currentCents):lot.startingCents)}. Shipping rates and tax are not calculated in this sandbox.</p><button className={styles.wide}>Submit test maximum</button></fieldset></form>}
 {lot.status==='sold'&&<div><h3>Test winning order</h3><p>{lot.testOrderNumber}<br/>Payment: {lot.paymentStatus} · Fulfillment: {lot.fulfillmentStatus}<br/>Pay by: {new Date(lot.paymentDueAt).toLocaleString()}<br/>Delivery: {lot.winningDelivery?.method}</p><div className={styles.actions}><button disabled={busy||lot.paymentStatus==='paid'} onClick={()=>operate({action:'payment_paid',id:selected})}>Simulate successful payment</button><button className={styles.secondary} disabled={busy||lot.paymentStatus==='paid'} onClick={()=>operate({action:'payment_failed',id:selected})}>Simulate failed payment</button></div>{lot.paymentStatus==='paid'&&lot.fulfillmentStatus!=='complete'&&<form onSubmit={e=>{e.preventDefault();operate({action:'fulfill',id:selected,reference});}}><label>Test tracking number or pickup confirmation<input required minLength={3} maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><div className={styles.actions}><button disabled={busy}>Record test fulfillment</button></div></form>}</div>}
 {['draft','scheduled'].includes(lot.status)&&<details><summary>Cancel test lot</summary><label>Reason<textarea minLength={10} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<10} onClick={()=>operate({action:'cancel',id:selected,reason})}>Cancel and record reason</button></details>}
 <details><summary>Maximum bids — staff sandbox only</summary><ul className={styles.list}>{detail.bidders.map((b:any)=><li key={b.bidderId}>{b.bidderId}: {money(b.maximumCents)} · {b.delivery.method}</li>)}</ul></details><details><summary>Recorded activity</summary><ol className={styles.scroll}>{detail.events.map((e:any,i:number)=><li key={i}>{new Date(e.at).toLocaleString()} · {e.action}{e.bidder?' · '+e.bidder:''}{e.reason?' · '+e.reason:''}{e.extended?' · Closing time extended':''}</li>)}</ol><small>Latest 50 events. Events are retained in the database; this screen has no delete action.</small></details></>}</section></div>
 <section className={styles.card} style={{marginTop:24}}><h2>Public launch checklist</h2><p>Public bidding stays locked in code. These requirements are still outstanding:</p><ul><li>Payment provider approval for auctions and eligible rug origins</li><li>Phone verification and provider-confirmed card verification</li><li>Final auction terms, fees and customer acceptance</li><li>Accurate shipping quotes, tax and inventory reservation across all sales channels</li><li>Automatic closing, payment processing, notifications and customer bidding dashboard</li><li>Live-environment security, concurrency, mobile and end-to-end testing</li></ul><a href="/auctions/register">Preview the bidder registration page</a></section>
 </main>;
}
