'use client';
import {useEffect,useState} from 'react';
import {auctionRequest,auctionMoney as money} from './client';
import {matchesSearch,matchesSize,SHOP_SIZE_OPTIONS} from '@/lib/rug-discovery.mjs';
import styles from './Auction.module.css';
export default function AuctionCatalog(){
 const [lots,setLots]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[size,setSize]=useState(''),[event,setEvent]=useState(''),[sort,setSort]=useState('title'),[limit,setLimit]=useState(12);
 async function load(){setError('');try{const response=await fetch('/api/auction/catalog',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setLots(data.lots);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Catalog unavailable.');}}
 useEffect(()=>{load();},[]);
 const filtered=lots.filter(l=>(!event||l.eventTitle===event)&&matchesSearch({...l.snapshot,name:l.title},query)&&matchesSize(l.snapshot,size)).sort((a,b)=>sort==='price'?a.startingCents-b.startingCents:sort==='ending'?(a.endAt||Infinity)-(b.endAt||Infinity):a.title.localeCompare(b.title));
 return <section className={styles.catalog} id="auction-catalog"><div className={styles.row}><div><span className={styles.eyebrow}>Browse without an account</span><h2>Auction catalog</h2></div><a href="/auctions/register">Your bidder profile</a></div><div className={styles.notice}>Preview upcoming auction lots. Bidding is closed while launch preparations are completed. Opening prices and planned dates are shown when available.</div><div className={styles.catalogFilters}><label>Search lots<input type="search" placeholder="Rug, color, size or SKU" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/></label><label>Size<select value={size} onChange={e=>{setSize(e.target.value);setLimit(12);}}><option value="">All sizes</option>{SHOP_SIZE_OPTIONS.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="title">Title A–Z</option><option value="price">Opening bid: low to high</option><option value="ending">Planned closing</option></select></label><label>Auction event<select value={event} onChange={e=>{setEvent(e.target.value);setLimit(12);}}><option value="">All events</option>{Array.from(new Set(lots.map(l=>String(l.eventTitle)))).map(e=><option key={e}>{e}</option>)}</select></label><button className={styles.secondary} onClick={()=>{setQuery('');setSize('');setEvent('');}}>Clear filters</button></div>
 {error&&<div className={styles.error} role="alert"><p>{error}</p><button className={styles.secondary} onClick={load}>Retry catalog</button></div>}{!loaded&&!error&&<p>Loading auction lots…</p>}{loaded&&<p role="status">{filtered.length} published auction lots</p>}{loaded&&!filtered.length&&<div className={styles.card}><h3>{lots.length?'No lots match your filters.':'The next auction catalog is being prepared.'}</h3><p>{lots.length?'Try a different search or size.':'Auction lots appear here after Marco Polo publishes them. You do not need an account to browse.'}</p><a href="/?view=shop">Browse the regular shop collection</a></div>}
 <div className={styles.rugGrid}>{filtered.slice(0,limit).map(l=><article key={l.id} className={styles.rugCard}><a className={styles.rugPhoto} href={'/auctions/lots/'+l.id}>{l.snapshot.images?.[0]&&<img loading="lazy" src={l.snapshot.images[0]} alt={l.title}/>}</a><div className={styles.rugInfo}><span className={styles.badge}>{l.lotNumber} · Preview</span><h3><a href={'/auctions/lots/'+l.id}>{l.title}</a></h3><p>{l.snapshot.dimensions} · {l.snapshot.material}</p><p className={styles.price}>{money(l.startingCents)}</p><p>Opening bid · No bids accepted yet</p><p className={styles.muted}>{l.endAt?'Planned close: '+new Date(l.endAt).toLocaleString():'Dates to be announced'}</p><a className={styles.button} href={'/auctions/lots/'+l.id}>View auction lot</a></div></article>)}</div>{filtered.length>limit&&<div className={styles.actions}><button className={styles.secondary} onClick={()=>setLimit(limit+12)}>Show more lots</button></div>}</section>;
}
