'use client';
import {useEffect,useRef,useState} from 'react';
import {getAuth,RecaptchaVerifier,linkWithPhoneNumber} from 'firebase/auth';
import {app} from '@/lib/firebase';
import {auctionRequest} from './client';
import styles from './Auction.module.css';
export default function AuctionCardSetup(){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[phone,setPhone]=useState(''),[code,setCode]=useState('');const verifier=useRef<RecaptchaVerifier|null>(null),confirmation=useRef<any>(null);
 async function load(){setData(await auctionRequest('live'));}
 useEffect(()=>{load().catch(e=>setError(e.message));const id=new URLSearchParams(window.location.search).get('auctionSetup');if(id)auctionRequest('live',{action:'verify',sessionId:id}).then(()=>{history.replaceState(null,'','/auctions/account');return load();}).catch(e=>setError(e.message));return()=>verifier.current?.clear();},[]);
 async function action(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className={styles.card}><h3>Verified phone &amp; saved payment card</h3>{error&&<p className={styles.error} role="alert">{error}</p>}{data?.phoneVerified?<p>Phone verified. Your profile phone must match this verified number before bidding.</p>:<><label>Phone in international format<input type="tel" placeholder="+17035551234" value={phone} onChange={e=>setPhone(e.target.value)}/></label><div id="auction-phone-recaptcha"/><button type="button" disabled={busy} onClick={()=>action(async()=>{const auth=getAuth(app);await auth.authStateReady();if(!auth.currentUser)throw Error('Sign in first.');if(!verifier.current)verifier.current=new RecaptchaVerifier(auth,'auction-phone-recaptcha',{size:'normal'});confirmation.current=await linkWithPhoneNumber(auth.currentUser,phone,verifier.current);})}>Send verification code</button>{confirmation.current&&<><label>SMS code<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>action(async()=>{await confirmation.current.confirm(code);confirmation.current=null;})}>Verify phone</button></>}</>}
 {data?.card?<p>Verified {data.card.brand} ending {data.card.last4}.</p>:<p>Save a card before placing your first bid. Card details are entered securely with Stripe.</p>}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I authorize Marco Polo Rugs to automatically charge my saved card for all items I win on one invoice per auction, including the disclosed tax and accepted delivery fees.</label><button type="button" disabled={busy||!consent} onClick={()=>action(async()=>{const d=await auctionRequest('live',{action:'setup',consent:true});window.location.assign(d.url);})}>{data?.card?'Update saved card':'Save payment card'}</button></section>;
}
