'use client';
import {useEffect,useRef,useState} from 'react';
import Papa from 'papaparse';
import {auctionRequest,auctionMoney} from './client';
import styles from './Auction.module.css';
const columns=['rugId','sku','title','origin','dimensions','material','condition','image','starting','reserve','loading'];
const blank=()=>({id:crypto.randomUUID(),version:0,title:'New rug auction',status:'draft',startAt:0,endAt:0,stagger:30,rows:[] as any[],issues:[] as string[]});
const dateInput=(n:number)=>n?new Date(n-new Date(n).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const label=(s:string)=>({draft:'Draft',ready:'Ready to publish',coming_soon:'Coming soon',next_auction:'Next auction',archived:'Archived'}[s]||s);
export default function AuctionPlanning({onTest}:{onTest:(id:string)=>void}){
 const [auctions,setAuctions]=useState<any[]>([]),[rugs,setRugs]=useState<any[]>([]),[plan,setPlan]=useState<any>(null),[search,setSearch]=useState(''),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[inventoryOpen,setInventoryOpen]=useState(false),[preview,setPreview]=useState(false),[dirty,setDirty]=useState(false);
 const pending=useRef<{body:string,id:string}|null>(null),lock=useRef(false);
 async function load(){const d=await auctionRequest('planning');setAuctions(d.auctions);return d.auctions;}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function inventory(){const d=await auctionRequest('manage?inventory=1');setRugs(d.rugs);return d.rugs;}
 async function toggleInventory(){if(inventoryOpen){setInventoryOpen(false);return;}try{await inventory();setInventoryOpen(true);}catch(e){setError(e instanceof Error?e.message:'Could not load inventory.');}}
 function change(update:any){setPlan((p:any)=>({...p,...update}));setDirty(true);setMessage('');}
 function open(p:any){if(dirty&&!window.confirm('Discard unsaved changes?'))return;setPlan(p);setDirty(false);setPreview(false);setInventoryOpen(false);setSelected([]);setError('');setMessage('');}
 function addInventory(){const additions=rugs.filter(r=>selected.includes(r.rugId)&&!plan.rows.some((x:any)=>x.rugId===r.rugId)).map(r=>({rugId:r.rugId,sku:r.sku,title:r.name,origin:r.origin,dimensions:r.dimensions,material:r.material,image:r.images[0]||'',condition:'',starting:50,reserve:0,loading:0}));if(plan.rows.length+additions.length>100){setError('Maximum 100 lots per auction.');return;}change({rows:[...plan.rows,...additions]});setSelected([]);}
 async function operate(action='save',index?:number){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body=action==='save'?{...plan,action}:{id:plan.id,version:plan.version,action,index};const serialized=JSON.stringify(body);if(pending.current?.body!==serialized)pending.current={body:serialized,id:crypto.randomUUID()};const result=await auctionRequest('planning',{...body,requestId:pending.current.id});pending.current=null;const all=await load();setPlan(all.find((p:any)=>p.id===plan.id));setDirty(false);setMessage('Saved privately. Customer visibility is controlled separately above.');if(result.testId)onTest(result.testId);}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{lock.current=false;setBusy(false);}}
 function template(){const csv=Papa.unparse([Object.fromEntries(columns.map(k=>[k,k==='starting'?'50':k==='reserve'||k==='loading'?'0':'']))]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Marco-Polo-auction-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async function importFile(file:File){setError('');try{const rugs:any[]=await inventory();if(file.size>500000)throw Error('CSV must be smaller than 500 KB.');const parsed=Papa.parse<Record<string,string>>(await file.text(),{header:true,skipEmptyLines:'greedy'});if(parsed.errors.length)throw Error('CSV: '+parsed.errors[0].message);if(!parsed.meta.fields?.includes('sku'))throw Error('Use the template: the sku column is required.');if(parsed.data.length+plan.rows.length>100)throw Error('Maximum 100 lots per auction.');const rows=parsed.data.map((r,i)=>{const matches=rugs.filter(x=>r.rugId?x.rugId===r.rugId:r.sku&&x.sku.toLowerCase()===r.sku.toLowerCase().trim());if(matches.length>1)throw Error(`Row ${i+2}: SKU matches multiple rugs; provide rugId.`);const match=matches[0];if(match&&!match.eligible)throw Error(`Row ${i+2}: rug is unavailable or held for review.`);return {...Object.fromEntries(columns.map(k=>[k,r[k]||''])),...(match?{rugId:match.rugId,sku:match.sku,origin:match.origin,title:r.title||match.name,dimensions:r.dimensions||match.dimensions,material:r.material||match.material,image:r.image||match.images[0]||''}:{}),starting:r.starting||'50',reserve:r.reserve||'0',loading:r.loading||'0'};});change({rows:[...plan.rows,...rows]});setMessage(`Imported ${rows.length} draft rows. Review and save; showroom inventory is unchanged.`);}catch(e){setError(e instanceof Error?e.message:'Import failed.');}}
 const available=rugs.filter(r=>r.eligible&&`${r.name} ${r.sku} ${r.dimensions}`.toLowerCase().includes(search.toLowerCase()));
 return <><div className={styles.notice}><strong>Private auction preparation.</strong> All stages below are staff-only. Customer page visibility is controlled separately above. Test bids, payments and fulfillment are simulated.</div>
 <div className={styles.grid}>{['draft','ready','next_auction'].map(s=><div className={styles.card} key={s}><span className={styles.stat}>{auctions.filter(a=>a.status===s).length}</span>{label(s)}</div>)}</div>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}
 <div className={styles.actions}><button disabled={busy} onClick={()=>open(blank())}>+ Prepare an auction</button><button className={styles.secondary} disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh auction list</button></div>
 <section className={styles.card}><h2>Auction calendar</h2><p>Latest 100 auctions · times shown in your device’s local timezone.</p>{!auctions.length&&<p>No auctions prepared yet. Start with an auction, then add rugs in bulk.</p>}<div className={styles.actions}>{auctions.map(a=><button key={a.id} className={styles.secondary} disabled={busy} onClick={()=>open(a)}>{a.title} · {label(a.status)} · {a.rows.length} lots<br/>{a.startAt?new Date(a.startAt).toLocaleString():'Date to be set'}</button>)}</div></section>
 {plan&&<fieldset disabled={busy} style={{border:0,padding:0}}><section className={styles.card} style={{marginTop:24}}><h2>{plan.title}</h2><p>{dirty?'Unsaved changes':'Saved version '+plan.version} · Preparation does not publish to customers.</p><div className={styles.form}><label>Auction name<input maxLength={160} value={plan.title} onChange={e=>change({title:e.target.value})}/></label><label>Internal stage<select value={plan.status} onChange={e=>change({status:e.target.value})}>{['draft','ready','coming_soon','next_auction','archived'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>{['startAt','endAt'].map(k=><label key={k}>{k==='startAt'?'Opens':'First lot closes'} (local time)<input type="datetime-local" value={dateInput(plan[k])} onChange={e=>change({[k]:e.target.value?new Date(e.target.value).getTime():0})}/></label>)}<label>Seconds between lot closings<input type="number" min={0} max={600} value={plan.stagger} onChange={e=>change({stagger:Number(e.target.value)})}/></label></div><div className={styles.actions}><button onClick={()=>operate()}>Save auction &amp; check readiness</button><button className={styles.secondary} onClick={()=>setPreview(!preview)}>{preview?'Edit lots':'Private catalog preview'}</button></div>{plan.issues?.length>0&&<details><summary>{plan.issues.length} saved readiness items</summary><ul>{plan.issues.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul></details>}</section>
 {!preview&&<><section className={styles.card} style={{marginTop:24}}><h2>Add rugs in bulk</h2><p>Choose existing inventory or import a CSV. CSV photo links must use HTTPS. New items remain auction drafts until linked to reviewed showroom inventory.</p><div className={styles.actions}><button className={styles.secondary} onClick={template}>Download CSV template</button><label>Import CSV<input type="file" accept=".csv,text/csv" onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);e.target.value='';}}/></label></div><button className={styles.secondary} aria-expanded={inventoryOpen} onClick={toggleInventory}>{inventoryOpen?'Close inventory selector':'Choose rugs from inventory'}</button>{inventoryOpen&&<><label>Search inventory (first 500 records)<input placeholder="Name, SKU or size" value={search} onChange={e=>setSearch(e.target.value)}/></label><div style={{maxHeight:240,overflow:'auto'}}>{available.map(r=><label key={r.rugId} style={{display:'flex',alignItems:'center',gap:12,padding:8}}><input style={{width:20,minHeight:20}} type="checkbox" checked={selected.includes(r.rugId)} onChange={e=>setSelected(e.target.checked?[...selected,r.rugId]:selected.filter(id=>id!==r.rugId))}/>{r.sku} · {r.name} · {r.dimensions}</label>)}</div><div className={styles.actions}><button className={styles.secondary} onClick={()=>setSelected(available.filter(r=>!plan.rows.some((x:any)=>x.rugId===r.rugId)).slice(0,100-plan.rows.length).map(r=>r.rugId))}>Select up to remaining capacity</button><button disabled={!selected.length} onClick={addInventory}>Add {selected.length} selected rugs</button></div></>}</section>
 <section className={styles.card} style={{marginTop:24}}><h2>{plan.rows.length} prepared lots</h2><p>Enter a specific condition report for each rug. Removing a draft row never deletes inventory.</p>{plan.rows.map((r:any,i:number)=><details key={i} style={{borderBottom:'1px solid #ddd',padding:'16px 0'}}><summary>Lot {i+1} · {r.sku||'No SKU'} · {r.title||'Untitled rug'}</summary><div className={styles.form}>{columns.filter(k=>k!=='rugId').map(k=><label key={k}>{k}{['starting','reserve','loading'].includes(k)?' ($)':''}<input value={r[k]} maxLength={k==='condition'?3000:k==='image'?2000:160} readOnly={!!r.rugId&&['sku','origin'].includes(k)} onChange={e=>change({rows:plan.rows.map((x:any,j:number)=>j===i?{...x,[k]:e.target.value}:x)})}/></label>)}</div><div className={styles.actions}><button className={styles.secondary} onClick={()=>change({rows:plan.rows.filter((_:any,j:number)=>j!==i)})}>Remove draft row</button><button disabled={dirty||!plan.version||!r.rugId} onClick={()=>operate('test',i)}>Create bidding test copy</button></div><small>Save changes before testing. Copies open for 15 minutes after scheduling in the test lab.</small></details>)}</section></>}
 {preview&&<section style={{marginTop:24}}><h2>Private preview · {plan.title}</h2><p>Opening bids shown below are planned amounts. No customers can see or bid on this catalog.</p><div className={styles.rugGrid}>{plan.rows.map((r:any,i:number)=><article className={styles.card} key={i}>{r.image&&<img src={r.image} alt={r.title} style={{width:'100%',height:220,objectFit:'contain'}}/>}<p className={styles.eyebrow}>Lot {i+1} · {label(plan.status)}</p><h3>{r.title}</h3><p>{r.dimensions} · {r.material} · {r.origin}</p><p>{r.condition||'Condition report needed'}</p><strong>Opening bid {auctionMoney(Math.round(Number(r.starting)*100))}</strong><p>{plan.endAt?'Planned close: '+new Date(plan.endAt+i*plan.stagger*1000).toLocaleString():'Closing time not set'}</p><small>Pickup: self loading or assisted loading ({auctionMoney(Math.round(Number(r.loading)*100))}). Shipping quote required before live bidding.</small></article>)}</div></section>}</fieldset>}
 </>;
}
