'use client';
import {useEffect,useState} from 'react';
import {auctionRequest,auctionMoney as money} from './client';
import styles from './Auction.module.css';
export default function AuctionLot({id}:{id:string}){
 const [lot,setLot]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[photo,setPhoto]=useState(0),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[method,setMethod]=useState('pickup_self');
 useEffect(()=>{let live=true;fetch('/api/auction/catalog?id='+encodeURIComponent(id),{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(live)setLot(data.lots[0]);}).catch(e=>{if(live)setError(e.message);});auctionRequest('watch').then(data=>{if(live)setSaved(data.ids.includes(id));}).catch(()=>{});return()=>{live=false;};},[id]);
 async function watch(){if(busy)return;setBusy(true);setMessage('');try{await auctionRequest('watch',{id,saved:!saved});setSaved(!saved);setMessage(saved?'Removed from your watchlist.':'Saved to your auction watchlist.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <main className={styles.page}><a href="/?view=auction">← Auction catalog</a>{error?<div role="alert" className={styles.error}>{error}</div>:!lot?<p>Loading auction lot…</p>:<><p className={styles.eyebrow}>{lot.eventTitle} · {lot.lotNumber}</p><div className={styles.split}><section><div className={styles.card}>{lot.snapshot.images[photo]&&<a href={lot.snapshot.images[photo]} target="_blank" rel="noreferrer"><img src={lot.snapshot.images[photo]} alt={lot.title} className={styles.detailImage}/></a>}<p className={styles.muted}>Open the photo for a larger view.</p><div className={styles.thumbnails}>{lot.snapshot.images.map((url:string,i:number)=><button key={i} className={styles.secondary} aria-label={'Photo '+(i+1)} aria-pressed={photo===i} onClick={()=>setPhoto(i)}><img src={url} alt=""/></button>)}</div></div><section className={styles.card} style={{marginTop:20}}><h2>Condition &amp; description</h2><p style={{whiteSpace:'pre-wrap'}}>{lot.condition}</p><p style={{whiteSpace:'pre-wrap'}}>{lot.description}</p><dl className={styles.specifications}>{[['Exact size',lot.snapshot.dimensions],['Material',lot.snapshot.material],['Origin',lot.snapshot.origin],['Construction',lot.snapshot.construction],['SKU',lot.snapshot.sku]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not recorded'}</dd></div>)}</dl></section></section>
 <section className={styles.card}><span className={styles.badge}>Upcoming auction preview</span><h1 style={{fontSize:38}}>{lot.title}</h1><p className={styles.price}>{money(lot.startingCents)}</p><p>Opening bid · {lot.hasReserve?'Reserve applies':'No reserve'}</p><p>No bids accepted yet · Buyer’s premium 0%</p><div className={styles.notice}><strong>Bidding is not open.</strong><br/>Account and payment verification must be available before bids can be accepted. Preparing an account does not place a bid.</div><p>{lot.startAt?'Planned opening: '+new Date(lot.startAt).toLocaleString():'Opening date to be announced'}<br/>{lot.endAt?'Planned closing: '+new Date(lot.endAt).toLocaleString():'Closing date to be announced'}</p><div className={styles.actions}><button disabled>Place bid — not open</button><button disabled={busy} className={styles.secondary} onClick={watch}>{saved?'♥ Watching':'♡ Watch this lot'}</button><a className={`${styles.button} ${styles.secondary}`} href="/auctions/register">Complete bidder profile</a></div>{message&&<p role="status" className={styles.notice}>{message} <a href="/sign-in">Sign in</a></p>}
 <h3>Delivery &amp; pickup</h3><label>Explore your options<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pickup_self">Pickup — I will load</option><option value="pickup_assisted">Pickup — Marco Polo loading assistance</option>{lot.shippingOffered&&<option value="shipping">Shipping — request a quote</option>}</select></label><p>{method==='shipping'?'Shipping must be quoted for the packed rug and your destination before bidding. No shipping price has been calculated here.':method==='pickup_assisted'?'Loading assistance: '+money(lot.loadingCents)+'. Appointment and suitable vehicle required.':'Customer pickup: bring a suitable vehicle and enough help to load the rug.'}</p><p className={styles.muted}>Pickup: 3260 Duke St, Alexandria, VA 22314. Free padding included. Applicable tax and delivery charges must be confirmed before a future bid. This selection does not book pickup or shipping.</p><a href={'mailto:marcopolorugs@aol.com?subject='+encodeURIComponent('Auction inquiry: '+lot.lotNumber+' '+lot.title)}>Ask about this lot or request shipping</a>
 <details><summary>How maximum bidding will work</summary><p>Enter the most you want to bid. The system increases your bid only as needed against other bidders, up to your maximum. Earlier equal maximum bids take priority. Bids placed in the final two minutes extend closing to two minutes after acceptance.</p></details><details><summary>Payment and auction terms</summary><p>Proposed payment deadline: 48 hours after closing. Full payment is required before collection or dispatch. Final auction terms and verification must be completed before bidding opens.</p></details><a href="/auctions/account">View your watchlist</a></section></div></>}</main>;
}
