'use client';
import {useEffect,useState} from 'react';
import {getAuth,sendPasswordResetEmail} from 'firebase/auth';
import {app} from '@/lib/firebase';
import {auctionRequest,auctionMoney as money} from './client';
import styles from './Auction.module.css';
import accountStyles from './AuctionOperations.module.css';
const tabs=['Account info','Addresses','Payment methods','Notification preferences','Saved searches','Won items & invoices','User preferences'];
export default function AuctionBuyerAccount(){
 const [tab,setTab]=useState(tabs[0]),[data,setData]=useState<any>(null),[form,setForm]=useState<any>({country:'US',preferences:{language:'en',emailOutbid:true,emailReminders:true,emailMarketing:false},savedSearches:[]}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 async function load(){const d=await auctionRequest('account');setData(d);if(d.profile)setForm({...form,...d.profile,preferences:{...form.preferences,...d.profile.preferences}});}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function save(){setBusy(true);setError('');try{await auctionRequest('account',form);await load();setMessage('Your account settings were saved. Public bidding remains closed.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 const field=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input type={type} required={required} value={form[key]||''} maxLength={150} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const invoices=data?.invoices||[],unpaid=invoices.filter((i:any)=>i.paymentStatus!=='paid');
 return <main className={styles.page}><p className={styles.eyebrow}>Private buyer-account preview · Your signed-in account</p><h1>Your auction account</h1><div className={styles.notice}><strong>Auctions are under construction.</strong> Bidding, real card charges and public lots remain closed. This preview saves your own account settings; no inventory is displayed.</div>{data?.profile?.accountStatus==='suspended'&&<p role="alert" className={styles.error}>Your bidder account is suspended. Please contact the showroom before bidding opens.</p>}{unpaid.length>0&&<div className={styles.error}><strong>You have {unpaid.length} unpaid auction invoice(s).</strong> Balance {money(unpaid.reduce((n:number,i:any)=>n+i.total,0))}. <button onClick={()=>setTab('Won items & invoices')}>View unpaid invoices</button></div>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{!data?<p>Sign in to load your account settings.</p>:<div className={accountStyles.account}><nav className={accountStyles.navigation} aria-label="Buyer account settings">{tabs.map(t=><button key={t} className={tab===t?'':styles.secondary} aria-current={tab===t?'page':undefined} onClick={()=>{setTab(t);setMessage('');}}>{t}</button>)}</nav><section className={styles.card}><h2>{tab}</h2><p className={styles.muted}>Bidder number: {data.profile?.bidderNumber||'Assigned when your complete profile is saved'}</p><form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className={styles.form}>
 {tab==='Account info'&&<>{field('firstName','First name','text',true)}{field('lastName','Last name','text',true)}<label>Email<input type="email" disabled value={data.email}/></label>{field('phone','Mobile phone, e.g. +17035551234','tel',true)}{field('homePhone','Home phone (optional)','tel')}{field('gender','Gender (optional)')}{field('incomeRange','Household income range (optional)')}{field('birthDate','Birth date (optional)','date')}<p className={styles.muted}>Only contact and address fields are required. Optional demographic details are not required to bid.</p><button type="button" className={styles.secondary} onClick={async()=>{setBusy(true);setError('');try{await sendPasswordResetEmail(getAuth(app),data.email);setMessage('Password reset email sent. Check Spam or Junk too.');}catch{setError('Password reset email could not send.');}finally{setBusy(false);}}}>Send password reset email</button></>}
 {tab==='Addresses'&&<>{field('address1','Street address','text',true)}{field('address2','Apartment / suite (optional)')}{field('city','City','text',true)}{field('region','State / region','text',true)}{field('postalCode','ZIP / postal code','text',true)}{field('country','Country code, e.g. US','text',true)}<p className={styles.muted}>Pickup or delivery is selected once at the first bid in each auction. Shipping cost and address must be accepted before that bid.</p></>}
 {tab==='Payment methods'&&<><p>Cards will be entered through Stripe's secure card form before launch. Card numbers are never stored in your auction profile.</p><p>Saving a card must include consent to automatically charge the consolidated winning invoice. A card decline or bank verification request leaves an unpaid invoice visible here.</p><button type="button" disabled>Card setup opens before bidding launches</button></>}
 {tab==='Notification preferences'&&<>{[['emailOutbid','Outbid notifications'],['emailReminders','Auction and pickup reminders'],['emailMarketing','Promotions (optional)']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!form.preferences?.[key]} onChange={e=>setForm({...form,preferences:{...form.preferences,[key]:e.target.checked}})}/>{label}</label>)}<p className={styles.muted}>Winning invoices, payment failures and essential service notices remain transactional notices. Preferences are saved now; auction email delivery is not enabled yet.</p></>}
 {tab==='Saved searches'&&<><label>Save a search<input maxLength={150} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Blue wool runner"/></label><button type="button" disabled={!query.trim()||form.savedSearches.length>=20} onClick={()=>{setForm({...form,savedSearches:[...form.savedSearches,query.trim()]});setQuery('');}}>Add search</button>{form.savedSearches.map((q:string,i:number)=><p key={i}>{q} <button type="button" className={styles.secondary} onClick={()=>setForm({...form,savedSearches:form.savedSearches.filter((_:string,n:number)=>n!==i)})}>Remove</button></p>)}</>}
 {tab==='Won items & invoices'&&<>{!invoices.length&&<p>No auction wins yet. Public auctions have not opened.</p>}{invoices.map((i:any)=><article className={styles.card} key={i.id}><h3>{i.number}</h3><p>{i.items.length} items · {i.paymentStatus} · {money(i.total)}</p>{i.paymentFailure&&<p role="alert">{i.paymentFailure}</p>}<p>{i.delivery.method} · Pickup deadline: {i.storage.dueDate||'Not ready for pickup'} · Storage: {money(i.storage.cents)}</p></article>)}{data.moreInvoices&&<p>Showing the first 100 invoices. Contact the showroom for older records.</p>}</>}
 {tab==='User preferences'&&<><label>Language<select value={form.preferences?.language||'en'} onChange={e=>setForm({...form,preferences:{...form.preferences,language:e.target.value}})}><option value="en">English</option><option value="fa">Dari / Persian preference</option></select></label><p className={styles.muted}>This saves your language preference. The current preview is in English.</p><p>Watched lots: {data.watchCount}. Public auction items remain hidden until launch.</p></>}
 {!['Payment methods','Won items & invoices'].includes(tab)&&<><p className={styles.muted}>Complete Account info and Addresses before your first save.</p><button disabled={busy}>{busy?'Saving…':'Save account settings'}</button></>}
 </fieldset></form><details><summary>Auction terms and storage policy</summary><p className={accountStyles.terms}>{data.terms}</p></details></section></div>}</main>;
}
