'use client';
import {useEffect,useState} from 'react';
import {auctionRequest,auctionMoney as money} from './client';
import styles from './Auction.module.css';
export default function AuctionAccount(){
 const [lots,setLots]=useState<any[]>([]),[count,setCount]=useState(0),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{(async()=>{const watch=await auctionRequest('watch');const response=await fetch('/api/auction/catalog',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setLots(data.lots.filter((l:any)=>watch.ids.includes(l.id)));setCount(watch.ids.length);setLoaded(true);})().catch(e=>setError(e.message));},[]);
 return <main className={styles.page}><a href="/?view=auction">← Auction catalog</a><p className={styles.eyebrow}>Marco Polo Rugs · My auctions</p><h1>Your auction watchlist.</h1><div className={styles.actions}><a className={styles.button} href="/auctions/register">Bidder profile &amp; verification</a><a className={`${styles.button} ${styles.secondary}`} href="/?view=auction">Browse lots</a></div><div className={styles.notice}>Bidding and payments have not opened. Watched lots are saved to your customer account across devices. Watching does not reserve a rug.</div>{error&&<div role="alert" className={styles.error}>{error} <a href="/sign-in">Sign in / create account</a></div>}{!error&&!loaded&&<p>Loading your watchlist…</p>}{loaded&&<p>{lots.length} available watched lots{count>lots.length?`; ${count-lots.length} watched lots are currently unavailable.`:'.'}</p>}{loaded&&!lots.length&&<div className={styles.card}><h2>Find something worth watching.</h2><p>Open an auction lot and select Watch this lot.</p></div>}<div className={styles.rugGrid}>{lots.map(l=><article className={styles.rugCard} key={l.id}>{l.snapshot.images[0]&&<img src={l.snapshot.images[0]} alt={l.title} className={styles.managementImage}/>}<div className={styles.rugInfo}><span className={styles.badge}>{l.lotNumber}</span><h3>{l.title}</h3><p>Opening bid {money(l.startingCents)}</p><a className={styles.button} href={'/auctions/lots/'+l.id}>View lot</a></div></article>)}</div></main>;
}
