'use client';
import AuctionCardSetup from './AuctionCardSetup';
import AuctionInvoicePrint from './AuctionInvoicePrint';
import AuctionInvoicePayment from './AuctionInvoicePayment';
import {useEffect,useState} from 'react';
import {getAuth,sendPasswordResetEmail} from 'firebase/auth';
import {app} from '@/lib/firebase';
import {auctionRequest,auctionMoney as money} from './client';
import styles from './Auction.module.css';
import accountStyles from './AuctionOperations.module.css';
const tabs=['Watching & bids','Account info','Addresses','Payment methods','Notification preferences','Saved searches','Won items & invoices','User preferences'];
export default function AuctionBuyerAccount(){
 const [tab,setTab]=useState('Account info'),[data,setData]=useState<any>(null),[form,setForm]=useState<any>({country:'US',preferences:{language:'en',emailOutbid:true,emailReminders:true,emailMarketing:false},savedSearches:[]}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[bids,setBids]=useState<any[]>([]),[watching,setWatching]=useState<any[]>([]);
 async function load(){const d=await auctionRequest('account');setData(d);if(d.profile)setForm({...form,...d.profile,preferences:{...form.preferences,...d.profile.preferences}});}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(tab!=='Watching & bids')return;Promise.all([auctionRequest('live?bids=1'),auctionRequest('watch'),fetch('/api/auction/catalog',{cache:'no-store'}).then(r=>r.json())]).then(([b,w,c])=>{setBids(b.bids);setWatching((c.lots||[]).filter((l:any)=>w.ids.includes(l.id)));}).catch(e=>setError(e.message));},[tab]);async function save(){setBusy(true);setError('');try{await auctionRequest('account',form);await load();setMessage('Your auction account settings were saved.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 const field=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input type={type} required={required} value={form[key]||''} maxLength={150} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const invoices=data?.invoices||[],unpaid=invoices.filter((i:any)=>!['paid','paid_review'].includes(i.paymentStatus));
 return <main className={styles.page}><p className={styles.eyebrow}>Marco Polo Rugs · Buyer account</p><h1>Your auction account</h1><div className={styles.actions}><a href="/auctions">Browse auction rugs</a><button type="button" className={styles.secondary} onClick={()=>load().catch(e=>setError(e.message))}>Refresh account</button></div><div className={styles.notice}><strong>{data?.publicEnabled?'Welcome to Marco Polo auctions.':'Auction bidding is not open yet.'}</strong> Manage your contact details, verified phone, saved payment card and winning invoices here.</div>{data?.profile?.accountStatus==='suspended'&&<p role="alert" className={styles.error}>Your bidder account is suspended. Please contact the showroom before bidding opens.</p>}{unpaid.length>0&&<div className={styles.error}><strong>You have {unpaid.length} unpaid auction invoice(s).</strong> Balance {money(unpaid.reduce((n:number,i:any)=>n+i.total,0))}. <button onClick={()=>setTab('Won items & invoices')}>View unpaid invoices</button></div>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{!data?<p>Sign in to load your account settings.</p>:<div className={accountStyles.account}><nav className={accountStyles.navigation} aria-label="Buyer account settings">{tabs.map(t=><button key={t} className={tab===t?'':styles.secondary} aria-current={tab===t?'page':undefined} onClick={()=>{setTab(t);setMessage('');}}>{t}</button>)}</nav><section className={styles.card}><h2>{tab}</h2><p className={styles.muted}>Shipping quote account ID: {data.buyerId}</p><p className={styles.muted}>Bidder number: {data.profile?.bidderNumber||'Assigned when your complete profile is saved'}</p><form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className={styles.form}>
 {tab==='Account info'&&<>{field('firstName','First name','text',true)}{field('lastName','Last name','text',true)}<label>Email<input type="email" disabled value={data.email}/></label>{field('phone','Mobile phone, e.g. +17035551234','tel',true)}{field('homePhone','Home phone (optional)','tel')}{field('gender','Gender (optional)')}{field('incomeRange','Household income range (optional)')}{field('birthDate','Birth date (optional)','date')}<p className={styles.muted}>Only contact and address fields are required. Optional demographic details are not required to bid.</p><button type="button" className={styles.secondary} onClick={async()=>{setBusy(true);setError('');try{await sendPasswordResetEmail(getAuth(app),data.email);setMessage('Password reset email sent. Check Spam or Junk too.');}catch{setError('Password reset email could not send.');}finally{setBusy(false);}}}>Send password reset email</button></>}
 {tab==='Addresses'&&<>{field('address1','Street address','text',true)}{field('address2','Apartment / suite (optional)')}{field('city','City','text',true)}{field('region','State / region','text',true)}{field('postalCode','ZIP / postal code','text',true)}{field('country','Country code, e.g. US','text',true)}<p className={styles.muted}>Pickup or delivery is selected once at the first bid in each auction. Shipping cost and address must be accepted before that bid.</p></>}
 {tab==='Payment methods'&&<AuctionCardSetup/>}
 {tab==='Notification preferences'&&<>{[['emailOutbid','Outbid notifications'],['emailReminders','Auction and pickup reminders'],['emailMarketing','Promotions (optional)']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!form.preferences?.[key]} onChange={e=>setForm({...form,preferences:{...form.preferences,[key]:e.target.checked}})}/>{label}</label>)}<p className={styles.muted}>Winning invoices, payment failures and essential service notices remain transactional notices. Preferences are saved now; auction email delivery is not enabled yet.</p></>}
 {tab==='Saved searches'&&<><label>Save a search<input maxLength={150} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Blue wool runner"/></label><button type="button" disabled={!query.trim()||form.savedSearches.length>=20} onClick={()=>{setForm({...form,savedSearches:[...form.savedSearches,query.trim()]});setQuery('');}}>Add search</button>{form.savedSearches.map((q:string,i:number)=><p key={i}>{q} <button type="button" className={styles.secondary} onClick={()=>setForm({...form,savedSearches:form.savedSearches.filter((_:string,n:number)=>n!==i)})}>Remove</button></p>)}</>}
 {tab==='Watching & bids'&&<div className={styles.wide}><h3>Your active bids</h3>{!bids.length&&<p>No active bids.</p>}{bids.map((b:any)=><p key={b.id}><a href={'/auctions/lots/'+b.id}>{b.title}</a> · {b.leading?'You are leading':'Outbid'}<br/>Current {money(b.currentCents)} · Your private maximum {money(b.maximumCents)}<br/>Closes {new Date(b.endAt).toLocaleString()}</p>)}<h3>Watching</h3>{!watching.length&&<p>No currently available watched rugs.</p>}{watching.map((l:any)=><p key={l.id}><a href={'/auctions/lots/'+l.id}>{l.title}</a> · {money(l.currentCents||l.startingCents)}</p>)}</div>}{tab==='Won items & invoices'&&<>{!invoices.length&&<p>No auction wins yet.</p>}{invoices.map((i:any)=><article className={styles.card} key={i.id}><h3>{i.number}</h3><AuctionInvoicePrint invoice={i}/><AuctionInvoicePayment invoiceId={i.id} status={i.paymentStatus}/><ul>{i.items.map((r:any)=><li key={r.lotId}>{r.sku} · {r.title} · {money(r.amount)}</li>)}</ul><p>Items {money(i.subtotal)} · Premium {money(i.premium)} · Delivery {money(i.shipping+i.loading)} · Tax {money(i.tax)}</p><p>{i.items.length} items · {i.paymentStatus} · {money(i.total)}</p>{!!i.refundedCents&&<p>Refund confirmed: {money(i.refundedCents)}</p>}{i.paymentFailure&&<p role="alert">{i.paymentFailure}</p>}{i.trackingReference&&<p>Carrier / tracking: {i.trackingReference}</p>}<p>{i.delivery.method} · Pickup deadline: {i.storage.dueDate||'Not ready for pickup'} · Storage: {money(i.storage.cents)}</p></article>)}{data.moreInvoices&&<p>Showing the first 100 invoices. Contact the showroom for older records.</p>}</>}
 {tab==='User preferences'&&<><label>Language<select value={form.preferences?.language||'en'} onChange={e=>setForm({...form,preferences:{...form.preferences,language:e.target.value}})}><option value="en">English</option><option value="fa">Dari / Persian preference</option></select></label><p className={styles.muted}>This saves your language preference. The current preview is in English.</p><p>Watched lots: {data.watchCount}. Public auction items remain hidden until launch.</p></>}
 {!['Payment methods','Won items & invoices'].includes(tab)&&<><p className={styles.muted}>Complete Account info and Addresses before your first save.</p><button disabled={busy}>{busy?'Saving…':'Save account settings'}</button></>}
 </fieldset></form><details><summary>Auction terms and storage policy</summary><p className={accountStyles.terms}>{data.terms}</p></details></section></div>}</main>;
}
