'use client';
import {useEffect,useState,FormEvent} from 'react';
import {getAuth,onAuthStateChanged,sendEmailVerification,User} from 'firebase/auth';
import {app} from '@/lib/firebase';
import styles from './Auction.module.css';
const fields=[['firstName','First name','given-name'],['lastName','Last name','family-name'],['phone','Phone number (+1…)','tel'],['address1','Street address','street-address'],['city','City','address-level2'],['region','State / province','address-level1'],['postalCode','ZIP / postal code','postal-code'],['country','Country code (US)','country']];
export default function BidderRegistration(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [form,setForm]=useState<Record<string,string>>({country:'US'}),[requirements,setRequirements]=useState<Record<string,boolean>>({});
 async function load(u:User){const response=await fetch('/api/auction/profile',{headers:{Authorization:'Bearer '+await u.getIdToken(true)},cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setRequirements(data.requirements);if(data.profile)setForm(data.profile);}
 useEffect(()=>onAuthStateChanged(getAuth(app),u=>{setUser(u&&!u.isAnonymous?u:null);if(u&&!u.isAnonymous)load(u).catch(e=>setError(e.message)).finally(()=>setLoading(false));else setLoading(false);}),[]);
 async function save(event:FormEvent){event.preventDefault();if(!user||busy)return;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/auction/profile',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await user.getIdToken()},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)throw Error(data.error);await load(user);setMessage('Your bidder profile is saved. Bidding remains closed.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function verify(){if(!user)return;setBusy(true);setError('');try{await sendEmailVerification(user);setMessage('Verification email sent. Open the link, then use Check verification below.');}catch{setError('Unable to send verification. Please wait a moment and try again.');}finally{setBusy(false);}}
 return <main className={styles.page}><a href="/?view=auction">← Marco Polo Rugs auctions</a><p className={styles.eyebrow}>Bidder registration</p><h1>Ready for your next find.</h1><div className={styles.notice}>Auctions are not open for bidding. You may save your details now. Phone and card verification will become available before launch; do not send card details to the showroom or enter them in this form.</div>
 {loading?<p>Loading your account…</p>:!user?<div className={styles.card}><h2>Start with your customer account</h2><p>Sign in or create an account, then return to this page to complete your bidder profile.</p><a className={styles.button} href="/sign-in">Sign in / create account</a></div>:<div className={styles.split}><aside className={styles.card}><h2>Your bidder checklist</h2><p>{user.email}</p><ul className={styles.list}>{[['profile','Contact details'],['email','Email verification'],['phone','Phone verification'],['payment','Payment method verification'],['terms','Final auction terms']].map(([key,label])=><li className={styles.row} key={key}><span>{label}</span><span className={styles.badge}>{requirements[key]?'Complete':key==='profile'||key==='email'?'Required':'Not open yet'}</span></li>)}</ul><div className={styles.actions}>{!requirements.email&&<button onClick={verify} disabled={busy}>Verify email</button>}<button className={styles.secondary} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await user.reload();await load(user);}catch{setError('Could not refresh verification.');}finally{setBusy(false);}}}>Check verification</button></div></aside><section className={styles.card}><h2>Contact and billing details</h2><form onSubmit={save}><fieldset disabled={busy} className={styles.form}>{fields.map(([key,label,auto])=><label key={key}>{label}<input required maxLength={150} autoComplete={auto} type={key==='phone'?'tel':'text'} value={form[key]||''} onChange={e=>setForm({...form,[key]:key==='country'?e.target.value.toUpperCase():e.target.value})}/></label>)}<label className={styles.wide}>Email address<input value={user.email||''} disabled type="email"/></label><button className={styles.wide} type="submit">{busy?'Saving…':'Save bidder profile'}</button></fieldset></form><p className={styles.muted}>Saving your profile does not mean you are approved to bid. Verification and final terms must be completed when registration fully opens.</p></section></div>}
 {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}</main>;
}
