'use client';
import {useEffect,useRef,useState,FormEvent} from 'react';
import {auctionRequest,auctionMoney as money} from './client';
import styles from './Auction.module.css';
const fresh=()=>({id:'',version:0,rugId:'',title:'',eventTitle:'Marco Polo Rugs · Rug Auction',condition:'',description:'',starting:'50',reserve:'0',loading:'0',startAt:'',endAt:'',shippingOffered:true});
const localDate=(n:number|null)=>{if(!n)return '';const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function LotManagement(){
 const [lots,setLots]=useState<any[]>([]),[rugs,setRugs]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState(false),[form,setForm]=useState(fresh),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[reason,setReason]=useState('');
 const active=useRef(false),last=useRef<{body:string;id:string}|null>(null);
 async function load(){const [catalog,inventory]=await Promise.all([auctionRequest('manage'),auctionRequest('manage?inventory=1')]);setLots(catalog.lots);setRugs(inventory.rugs);setLoaded(true);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function mutate(body:object){if(active.current)return;active.current=true;setBusy(true);setError('');setNotice('');try{const serialized=JSON.stringify(body);if(last.current?.body!==serialized)last.current={body:serialized,id:crypto.randomUUID()};await auctionRequest('manage',{...body,requestId:last.current.id});await load();last.current=null;setEditing(false);setNotice('Saved. Published previews remain closed for bidding.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);active.current=false;}}
 function edit(lot:any){setForm({id:lot.id,version:lot.version,rugId:lot.snapshot.rugId,title:lot.title,eventTitle:lot.eventTitle,condition:lot.condition,description:lot.description,starting:String(lot.startingCents/100),reserve:String(lot.reserveCents/100),loading:String(lot.loadingCents/100),startAt:localDate(lot.startAt),endAt:localDate(lot.endAt),shippingOffered:lot.shippingOffered});setEditing(true);}
 function save(e:FormEvent){e.preventDefault();mutate({action:form.id?'edit':'create',id:form.id,version:form.version,rugId:form.rugId,title:form.title,eventTitle:form.eventTitle,condition:form.condition,description:form.description,startingCents:Math.round(Number(form.starting)*100),reserveCents:Math.round(Number(form.reserve)*100),loadingCents:Math.round(Number(form.loading)*100),startAt:form.startAt?new Date(form.startAt).getTime():null,endAt:form.endAt?new Date(form.endAt).getTime():null,shippingOffered:form.shippingOffered});}
 return <><div className={styles.row}><div><span className={styles.eyebrow}>Catalog management</span><h2>Choose what goes to auction.</h2></div><button disabled={busy||!loaded} onClick={()=>{setForm(fresh());setEditing(true);}}>+ Create auction lot</button></div><div className={styles.notice}>Create actual auction drafts here, then publish them for public preview. Publishing does not open bidding, reserve stock or charge customers. Live activation remains unavailable while the auction system and payment approval are pending.</div>
 <div className={styles.grid}>{[['Draft lots','draft'],['Public previews','preview'],['Archived','archived']].map(([label,status])=><button className={styles.secondary} key={status} onClick={()=>setFilter(status)}><span>{loaded?lots.filter(l=>l.status===status).length:'—'} · {label}</span></button>)}</div>
 {error&&<div className={styles.error} role="alert"><p>{error}</p><button className={styles.secondary} disabled={busy} onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>Retry connection</button></div>}{notice&&<p role="status" className={styles.success}>{notice}</p>}
 {editing&&<section className={styles.card}><h2>{form.id?'Edit draft':'New auction lot'}</h2><form onSubmit={save}><fieldset disabled={busy} className={styles.form}>
 <label className={styles.wide}>Rug from inventory<select required value={form.rugId} onChange={e=>{const r=rugs.find(r=>r.rugId===e.target.value);setForm({...form,rugId:e.target.value,title:r?.name||''});}}><option value="">Choose an eligible rug</option>{rugs.filter(r=>r.eligible).map(r=><option key={r.rugId} value={r.rugId}>{r.sku} · {r.name}</option>)}</select></label>
 <label>Auction / event name<input required minLength={3} maxLength={160} value={form.eventTitle} onChange={e=>setForm({...form,eventTitle:e.target.value})}/></label><label>Lot title<input required minLength={3} maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
 <label className={styles.wide}>Condition report<textarea required minLength={10} maxLength={3000} placeholder="Describe wear, repairs, stains and fringe condition." value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}/></label><label className={styles.wide}>Auction description<textarea maxLength={5000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
 {([['starting','Starting bid ($)'],['reserve','Private reserve ($; 0 = none)'],['loading','Assisted loading fee ($)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" required min={key==='starting'?1:0} step="0.01" max="1000000" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Buyer’s premium<input disabled value="0%"/></label>
 <label>Planned opening (optional)<input type="datetime-local" value={form.startAt} onChange={e=>setForm({...form,startAt:e.target.value})}/></label><label>Planned closing (optional)<input type="datetime-local" value={form.endAt} onChange={e=>setForm({...form,endAt:e.target.value})}/></label><label className={styles.wide}>Delivery options<select value={form.shippingOffered?'shipping':'pickup'} onChange={e=>setForm({...form,shippingOffered:e.target.value==='shipping'})}><option value="shipping">Pickup and shipping (shipping quote required)</option><option value="pickup">Pickup only</option></select></label><p className={`${styles.muted} ${styles.wide}`}>Photos, exact size, material and origin come from the selected inventory rug. Planned dates are not a promise that bidding will open. All times use your local timezone. Review-held and sold rugs cannot be published.</p><div className={`${styles.actions} ${styles.wide}`}><button type="submit">Save draft</button><button type="button" className={styles.secondary} onClick={()=>setEditing(false)}>Cancel editing</button></div></fieldset></form></section>}
 <div className={styles.catalogFilters}><label>Search lots<input type="search" placeholder="Name, lot number or SKU" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All lots</option><option value="draft">Draft</option><option value="preview">Public preview</option><option value="archived">Archived</option></select></label><a className={styles.button} href="/?view=auction">View public catalog</a></div>
 {!loaded&&!error&&<p>Loading auction records…</p>}{loaded&&!lots.length&&<div className={styles.card}><h3>Create your first auction lot</h3><p>Only lots you create and publish here will appear in the public auction catalog. Your whole showroom inventory is no longer displayed as auction stock.</p></div>}
 <div className={styles.rugGrid}>{lots.filter(l=>(filter==='all'||l.status===filter)&&(l.title+' '+l.lotNumber+' '+l.snapshot.sku).toLowerCase().includes(query.toLowerCase())).map(l=><article className={styles.rugCard} key={l.id}>{l.snapshot.images?.[0]&&<img src={l.snapshot.images[0]} alt={l.title} className={styles.managementImage}/>}<div className={styles.rugInfo}><span className={styles.badge}>{l.status} · {l.lotNumber}</span><h3>{l.title}</h3><p>{l.eventTitle}</p><p>{l.snapshot.dimensions} · SKU {l.snapshot.sku}</p><p>Opening {money(l.startingCents)}<br/>Private reserve {money(l.reserveCents)}</p><div className={styles.actions}>{l.status==='draft'&&<><button className={styles.secondary} disabled={busy} onClick={()=>edit(l)}>Edit draft</button><button disabled={busy} onClick={()=>mutate({action:'publish',id:l.id,version:l.version})}>Publish preview</button></>}{l.status==='preview'&&<a className={styles.button} href={'/auctions/lots/'+l.id}>View auction lot</a>}</div>{l.status!=='archived'&&<details><summary>Unpublish / archive</summary><label>Reason<input minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className={styles.actions}>{l.status==='preview'&&<button className={styles.secondary} disabled={busy||reason.trim().length<5} onClick={()=>mutate({action:'unpublish',id:l.id,version:l.version,reason})}>Return to draft</button>}<button className={styles.secondary} disabled={busy||reason.trim().length<5} onClick={()=>mutate({action:'archive',id:l.id,version:l.version,reason})}>Archive</button></div></details>}</div></article>)}</div><p className={styles.muted}>Latest 100 auction lots. Up to 500 inventory rugs available for selection. Historical changes are recorded on the server.</p></>;
}
