import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {database} from './helpers/database.mjs';import * as engine from '../../lib/auction/engine.mjs';
const id='MPA-'+ 'a'.repeat(24),path='auction_buyer_invoices_v2/'+id;
function setup(){const db=database({[path]:{id,mode:'live',buyerId:'buyer',total:10600,version:1,paymentStatus:'unpaid',items:[{rugId:'rug',lotId:'lot'}]},'showroom_rugs/rug':{availability:'Reserved',auctionLotId:'lot'},'auction_live_cards/buyer':{mode:'live',verified:true,consent:true,customerId:'cus_1',paymentMethodId:'pm_1',setupIntentId:'seti_1'}});let created=0,confirms=0,fail=false;let intent={id:'pi_1',livemode:true,currency:'usd',amount:10600,amount_received:0,customer:'cus_1',status:'requires_payment_method',metadata:{purpose:'marcopolo_auction_live',invoiceId:id,buyerId:'buyer'}};
const stripe={paymentMethods:{retrieve:async()=>({id:'pm_1',livemode:true,customer:'cus_1'})},setupIntents:{retrieve:async()=>({livemode:true,status:'succeeded',customer:'cus_1',payment_method:'pm_1'})},paymentIntents:{create:async()=>{created++;if(fail)throw Error('Network uncertain');return {...intent};},retrieve:async()=>({...intent}),confirm:async()=>{confirms++;intent={...intent,status:'succeeded',amount_received:10600};return {...intent};}}};const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/server/auction-charge.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,Date,Error,Promise,require:n=>n==='server-only'?{}:n.includes('firebase-admin')?{serverDb:()=>db}:n.includes('auction-live')?{auctionStripe:()=>stripe}:n.includes('live-ledger')?{LIVE_INVOICES:'auction_buyer_invoices_v2'}:engine});return {db,api:exports,stats:()=>({created,confirms}),fail:()=>fail=true,intent:()=>intent};}
test('live payment persists original intent and duplicate attempts never charge twice',async()=>{const s=setup();await s.api.chargeAuctionInvoice(id);await s.api.chargeAuctionInvoice(id);assert.deepEqual(s.stats(),{created:1,confirms:1});assert.equal(s.db.read(path).paymentStatus,'paid');assert.equal(s.db.read('showroom_rugs/rug').availability,'Sold');});
test('forged amount and customer cannot mark a live invoice paid',async()=>{const s=setup();s.db.change(path,{paymentIntentId:'pi_1',stripeCustomerId:'cus_1'});for(const change of [{amount:1},{customer:'cus_other'},{livemode:false},{metadata:{...s.intent().metadata,buyerId:'other'}}])await assert.rejects(()=>s.api.reconcileAuctionPayment({...s.intent(),...change,status:'succeeded',amount_received:10600}));assert.equal(s.db.read(path).paymentStatus,'unpaid');});
test('paid status is monotonic and receipt outbox is unique',async()=>{const s=setup();await s.api.chargeAuctionInvoice(id);await s.api.reconcileAuctionPayment({...s.intent(),status:'requires_payment_method'});assert.equal(s.db.read(path).paymentStatus,'paid');assert.equal(s.db.keys().filter(k=>k.startsWith('auction_notification_outbox/')).length,1);});
test('unknown provider outcome records review and prevents a second intent',async()=>{const s=setup();s.fail();await assert.rejects(()=>s.api.chargeAuctionInvoice(id));await assert.rejects(()=>s.api.chargeAuctionInvoice(id),/already being processed/);assert.equal(s.stats().created,1);assert.equal(s.db.read(path).paymentStatus,'needs_review');});
test('inventory mismatch after provider success blocks release and flags staff review',async()=>{const s=setup();s.db.change(path,{paymentIntentId:'pi_1',stripeCustomerId:'cus_1'});s.db.change('showroom_rugs/rug',{auctionLotId:'other'});await s.api.reconcileAuctionPayment({...s.intent(),status:'succeeded',amount_received:10600});assert.equal(s.db.read(path).paymentStatus,'paid_review');assert.equal(s.db.read('showroom_rugs/rug').availability,'Reserved');});
test('declined retry reuses the original intent and enforces a bounded retry count',async()=>{const s=setup();s.db.change(path,{paymentIntentId:'pi_1',stripeCustomerId:'cus_1',paymentStatus:'declined'});await s.api.retryAuctionInvoice(id);assert.deepEqual(s.stats(),{created:0,confirms:1});assert.equal(s.db.read(path).paymentStatus,'paid');await assert.rejects(()=>s.api.retryAuctionInvoice(id),/declined/);});

test('off-session authentication-required failures route to bank verification',async()=>{const s=setup();s.db.change(path,{paymentIntentId:'pi_1',stripeCustomerId:'cus_1'});await s.api.reconcileAuctionPayment({...s.intent(),status:'requires_payment_method',last_payment_error:{code:'authentication_required'}});assert.equal(s.db.read(path).paymentStatus,'requires_action');});
