import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './helpers/database.mjs';
import {scheduleLiveAuction,acceptLiveBid,closeLiveLot,consolidateLiveAuction,cancelLiveLot} from '../../lib/auction/live-ledger.mjs';
import {DEFAULT_SETTINGS,choiceId} from '../../lib/auction/settlement.mjs';
const buyer={uid:'buyer-a',emailVerified:true,phoneNumber:'+17035551234',staff:false};
function fixture(count=1){const seed={'auction_worker_status/current':{lastSuccessAt:1000000,degraded:false},'auction_launch/current':{biddingEnabled:true},'auction_visibility/current':{mode:'open'},'auction_profiles/buyer-a':{firstName:'A',lastName:'Buyer',email:'buyer@example.test',phone:buyer.phoneNumber,address1:'123 Main Street',city:'Alexandria',region:'VA',postalCode:'22314',country:'US'},'auction_live_cards/buyer-a':{mode:'live',verified:true,consent:true}};for(let n=0;n<count;n++){seed['auction_lots/lot-'+n]={id:'lot-'+n,eventTitle:'Autumn rugs',title:'Test rug '+n,condition:'Excellent wool rug condition.',snapshot:{rugId:'rug-'+n,sku:'SKU'+n,dimensions:'6 x 9 feet',images:['https://example.test/rug.jpg']},status:'preview',startAt:100000,endAt:1000000,shippingOffered:true,startingCents:10000,reserveCents:0,loadingCents:500,version:1};seed['showroom_rugs/rug-'+n]={availability:'In Stock',origin:'Afghanistan'};}return database(seed);}
const request=(id='request-0000001')=>({requestId:id,maximumCents:20000,accepted:true,policyVersion:DEFAULT_SETTINGS.policyVersion,delivery:{method:'pickup_self'}});
const schedule=db=>scheduleLiveAuction(db,{id:'auction-live-0001',lotIds:db.keys().filter(k=>k.startsWith('auction_lots/')).map(k=>k.split('/')[1])},'owner',0);
test('scheduling explicitly reserves selected rugs and rejects duplicate scheduling',async()=>{const db=fixture();await schedule(db);assert.equal(db.read('showroom_rugs/rug-0').availability,'Reserved');await assert.rejects(()=>schedule(db),/already scheduled/);});
test('scheduling rejects sold, origin-review and missing-condition rugs atomically',async()=>{for(const change of [{availability:'Sold'},{origin:'Iran'}]){const db=fixture();db.change('showroom_rugs/rug-0',change);await assert.rejects(()=>schedule(db));assert.equal(db.read('auction_lots/lot-0').status,'preview');}});
test('bid acceptance is idempotent, maximum stays private and pause is atomic',async()=>{const db=fixture();await schedule(db);const r=await acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,110000);assert.equal(r.currentCents,10000);assert.equal(r.maximumCents,undefined);assert.deepEqual(await acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,110001),r);assert.equal(db.read('auction_lots/lot-0').bidCount,1);db.change('auction_launch/current',{biddingEnabled:false});await assert.rejects(()=>acceptLiveBid(db,'lot-0',buyer,request('request-0000002'),DEFAULT_SETTINGS,112000),/paused/);});
test('unverified buyers, staff, suspended profiles and cardless buyers cannot bid',async()=>{for(const type of ['email','phone','staff','suspended','card']){const db=fixture();await schedule(db);const u={...buyer};if(type==='email')u.emailVerified=false;if(type==='phone')u.phoneNumber='';if(type==='staff')u.staff=true;if(type==='suspended')db.change('auction_profiles/buyer-a',{accountStatus:'suspended'});if(type==='card')db.change('auction_live_cards/buyer-a',{verified:false});await assert.rejects(()=>acceptLiveBid(db,'lot-0',u,request(),DEFAULT_SETTINGS,110000));assert.equal(db.read('auction_lots/lot-0').bidCount,0);}});
test('late bids extend closing; early close cannot seal invoice; unsold releases stock',async()=>{const db=fixture(2);await schedule(db);const r=await acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,990000);assert.equal(r.endAt,1110000);assert.deepEqual(await closeLiveLot(db,'lot-0',1000000),{skipped:true});await assert.rejects(()=>consolidateLiveAuction(db,'auction-live-0001',DEFAULT_SETTINGS,1000000),/Close every lot/);await closeLiveLot(db,'lot-1',1000000);assert.equal(db.read('showroom_rugs/rug-1').availability,'In Stock');});
test('100 winning rugs produce exactly one invoice with 6% tax and repeat close stays idempotent',async()=>{const db=fixture(100);await schedule(db);for(let n=0;n<100;n++){await acceptLiveBid(db,'lot-'+n,buyer,request('request-'+String(n).padStart(12,'0')),DEFAULT_SETTINGS,110000+n*1001);await closeLiveLot(db,'lot-'+n,1000000);}const r=await consolidateLiveAuction(db,'auction-live-0001',DEFAULT_SETTINGS,1000000);assert.equal(r.invoiceIds.length,1);const i=db.read('auction_buyer_invoices_v2/'+r.invoiceIds[0]);assert.equal(i.items.length,100);assert.equal(i.subtotal,1000000);assert.equal(i.tax,60000);assert.equal(i.total,1060000);assert.equal(i.buyerEmail,'buyer@example.test');assert.match(i.number,/^MPA-[A-F0-9]{8}$/);assert.deepEqual(await consolidateLiveAuction(db,'auction-live-0001',DEFAULT_SETTINGS,1000010),r);});
test('shipping freezes per-lot quotes and charges only won rugs',async()=>{const db=fixture(2);await schedule(db);db.change('auction_live_shipping_quotes/quote-0000001',{buyerId:buyer.uid,auctionId:'auction-live-0001',address:'123 Main Street, Alexandria VA',lotFees:{'lot-0':2500,'lot-1':4000},expiresAt:2000000});const input={...request(),delivery:{method:'shipping'},shippingQuoteId:'quote-0000001'};await acceptLiveBid(db,'lot-0',buyer,input,DEFAULT_SETTINGS,110000);await closeLiveLot(db,'lot-0',1000000);await closeLiveLot(db,'lot-1',1000000);const r=await consolidateLiveAuction(db,'auction-live-0001',DEFAULT_SETTINGS);const i=db.read('auction_buyer_invoices_v2/'+r.invoiceIds[0]);assert.equal(i.shipping,2500);assert.equal(i.tax,750);assert.equal(i.total,13250);assert.equal(db.read('auction_live_choices/'+choiceId('auction-live-0001',buyer.uid)).delivery.method,'shipping');});

test('withdrawal releases an unbid rug and cannot erase accepted bids',async()=>{const db=fixture(2);await schedule(db);await cancelLiveLot(db,'lot-1','owner','Withdraw for a condition review.');assert.equal(db.read('showroom_rugs/rug-1').availability,'In Stock');await acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,110000);await assert.rejects(()=>cancelLiveLot(db,'lot-0','owner','Withdraw for a condition review.'),/unbid/);});

test('private rehearsal excludes other buyers inside the bid transaction',async()=>{const db=fixture();await schedule(db);db.change('auction_launch/current',{pilotOnly:true,pilotBuyerIds:['different-buyer']});await assert.rejects(()=>acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,110000),/private launch rehearsal/);db.change('auction_launch/current',{pilotBuyerIds:[buyer.uid]});assert.equal((await acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,110000)).accepted,true);});

test('stale closing worker prevents new obligations',async()=>{const db=fixture();await schedule(db);db.change('auction_worker_status/current',{lastSuccessAt:1});await assert.rejects(()=>acceptLiveBid(db,'lot-0',buyer,request(),DEFAULT_SETTINGS,990000),/scheduled worker/);});
