import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import ts from 'typescript';
import * as engine from '../../lib/auction/engine.mjs';import * as settlement from '../../lib/auction/settlement.mjs';import * as account from '../../lib/auction/account.mjs';import {database} from './helpers/database.mjs';
const headers={authorization:'Bearer staff','content-type':'application/json'};
function route(path,db,allowed=true,uid='customer'){
 const output={},code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
 vm.runInNewContext(code,{exports:output,Error,Date,Set,URL,JSON,console:{error(){}},process:{env:{}},require:name=>{if(name==='next/server')return {NextResponse:{json:(body,o)=>({body,status:o?.status||200})}};if(name.includes('auction-live'))return {auctionLaunch:async()=>({biddingEnabled:false})};if(name==='node:crypto')return crypto;if(name.includes('staff-permission'))return {requireStaff:async(r,section,action)=>{assert.equal(section,'settings');if(!allowed)throw Error('Denied');return {uid:'staff'};}};if(name.includes('firebase-admin'))return {serverDb:()=>db,caller:async()=>({uid,email:uid+'@example.test',firebase:{sign_in_provider:'password'}}),serverAuth:()=>({getUser:async()=>({uid,email:uid+'@example.test',emailVerified:true})})};if(name.includes('auction-errors'))return {auctionFailure:()=>({body:{error:'Denied'},status:403})};if(name.endsWith('engine.mjs'))return engine;if(name.endsWith('settlement.mjs'))return settlement;if(name.endsWith('account.mjs'))return account;throw Error(name);}});
 const post=body=>output.POST(new Request('https://example.test/api/auction',{method:'POST',headers,body:JSON.stringify({...body,requestId:body.requestId||crypto.randomUUID()})}));return {...output,post};
}
function lots(){return Object.fromEntries([1,2].map(i=>['auction_sandbox_lots/lot'+i,{id:'lot'+i,sourceAuction:'auction',snapshot:{rugId:'rug'+i,sku:'MP'+i},mode:'sandbox',status:'sold',paymentStatus:'unpaid',leaderId:'test-a',winningDelivery:{method:'pickup_self'},currentCents:10000,title:'Rug'}]));}
test('consolidated invoice is atomic, idempotent and sealed; no source inventory or retail invoice changes',async()=>{const db=database({...lots(),'showroom_rugs/rug1':{availability:'In Stock'}}),api=route('app/api/auction/operations/route.ts',db);const body={action:'consolidate',auctionId:'auction',requestId:crypto.randomUUID()};const results=await Promise.all([api.post(body),api.post({...body,requestId:crypto.randomUUID()})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);assert.equal((await api.post(body)).status,200);assert.equal(db.keys().filter(k=>k.startsWith(settlement.SANDBOX_INVOICES+'/')).length,1);const invoice=db.read(settlement.SANDBOX_INVOICES+'/'+settlement.invoiceId('auction','test-a'));assert.equal(invoice.items.length,2);assert.equal(invoice.total,21200);assert.equal(db.read('showroom_rugs/rug1').availability,'In Stock');assert.equal(db.keys().some(k=>k.startsWith('invoices/')),false);});
test('consolidation refuses an unfinished lot and unauthorized staff without partial writes',async()=>{const db=database(lots());db.change('auction_sandbox_lots/lot2',{status:'scheduled'});const api=route('app/api/auction/operations/route.ts',db);assert.equal((await api.post({action:'consolidate',auctionId:'auction'})).status,400);assert.equal(db.keys().filter(k=>k.startsWith(settlement.SANDBOX_INVOICES+'/')).length,0);assert.equal((await route('app/api/auction/operations/route.ts',db,false).post({action:'settings'})).status,403);});
test('pickup cannot start before payment; collection records only selected rugs and retains history',async()=>{const db=database(lots()),api=route('app/api/auction/operations/route.ts',db);await api.post({action:'consolidate',auctionId:'auction'});const id=settlement.invoiceId('auction','test-a');assert.equal((await api.post({action:'ready',id,version:1})).status,400);assert.equal((await api.post({action:'declined',id,version:1})).status,200);assert.equal(db.read(settlement.SANDBOX_INVOICES+'/'+id).paymentStatus,'failed');assert.equal((await api.post({action:'paid',id,version:2})).status,200);assert.equal((await api.post({action:'ready',id,version:3})).status,200);assert.equal((await api.post({action:'collect',id,version:4,lotIds:['lot1'],reference:'Buyer identity checked'})).status,200);const invoice=db.read(settlement.SANDBOX_INVOICES+'/'+id);assert.ok(invoice.items[0].collectedDate);assert.equal(invoice.items[1].collectedDate,null);assert.equal((await api.post({action:'collect',id,version:4,lotIds:['lot2'],reference:'Other pickup'})).status,400);});
test('account fields cannot forge payment, suspension or bidder number; optional demographics remain optional',()=>{const fields={firstName:'A',lastName:'B',phone:'+17035551234',address1:'123 Main',city:'Alexandria',region:'VA',postalCode:'22314',country:'US',paymentVerified:true,accountStatus:'active',bidderNumber:'OWNER',acceptedPolicyVersion:'forged'};const out=account.accountFields(fields);for(const key of ['paymentVerified','accountStatus','bidderNumber','acceptedPolicyVersion'])assert.equal(out[key],undefined);assert.equal(out.incomeRange,'');assert.throws(()=>account.accountFields({...fields,birthDate:'2026-02-30'}));});
test('buyer account is scoped to authenticated owner and safe projections hide provider and staff details',async()=>{const seed={'auction_profiles/customer':{firstName:'A',paymentMethodId:'pm_private',customerId:'cus_private',bidderNumber:'MPB-1'},'auction_buyer_invoices_v2/own':{buyerId:'customer',id:'own',items:[{lotId:'lot',title:'Rug',amount:100,reference:'private check',collectedBy:'staff'}],paymentStatus:'unpaid',total:100,delivery:{method:'pickup_self'},paymentIntentId:'pi_private'},'auction_buyer_invoices_v2/other':{buyerId:'other',total:999},'auction_settings_v2/current':{...settlement.DEFAULT_SETTINGS,updatedBy:'staff-private'}};const api=route('app/api/auction/account/route.ts',database(seed));const r=await api.GET(new Request('https://example.test'));assert.equal(r.status,200);assert.equal(r.body.invoices.length,1);assert.equal(r.body.invoices[0].total,100);assert.equal(r.body.profile.paymentMethodId,undefined);assert.equal(r.body.invoices[0].paymentIntentId,undefined);assert.equal(r.body.invoices[0].items[0].collectedBy,undefined);assert.equal(r.body.settings.updatedBy,undefined);});
test('account saves assign one bidder number and never trust submitted email or payment state',async()=>{const db=database(),api=route('app/api/auction/account/route.ts',db),fields={firstName:'A',lastName:'B',phone:'+17035551234',address1:'123 Main',city:'Alexandria',region:'VA',postalCode:'22314',country:'US',email:'forged',paymentVerified:true};assert.equal((await api.post(fields)).status,200);assert.equal((await api.post(fields)).status,200);assert.equal(db.read('auction_profiles/customer').bidderNumber,'MPB-000001');assert.equal(db.read('auction_private_counters/bidders').value,1);assert.equal(db.read('auction_profiles/customer').email,'customer@example.test');assert.equal(db.read('auction_profiles/customer').paymentVerified,undefined);});

test('live bidding stays disabled and visibility is controlled separately from invoice settings',()=>{
 for(const path of ['app/(public)/auctions/page.tsx','app/(public)/auctions/account/page.tsx','app/(public)/auctions/register/page.tsx','app/(public)/auctions/lots/[id]/page.tsx'])assert.ok(fs.readFileSync(path,'utf8').includes('AuctionUnderConstruction'));
 assert.ok(fs.readFileSync('app/api/auction/catalog/route.ts','utf8').includes('lots:[]'));
 assert.ok(fs.readFileSync('app/api/auction/bid/route.ts','utf8').includes('status:423'));
 assert.equal(settlement.validateSettings({...settlement.DEFAULT_SETTINGS,publicEnabled:true},1).publicEnabled,false);
});
test('auction test provider never accepts live credentials or exposes a public live-charge toggle',()=>{
 const source=fs.readFileSync('app/api/auction/test-payments/route.ts','utf8');assert.ok(source.includes("startsWith('sk_test_')"));assert.ok(source.includes("requireStaff(req,'settings','write')"));assert.equal(source.includes("sk_live_"),false);
});
