import test from 'node:test';import assert from 'node:assert/strict';import {buildInvoices,DEFAULT_SETTINGS,SANDBOX_INVOICES} from '../../lib/auction/settlement.mjs';import {chargeTestInvoice,syncTestIntent,testIntentState,TEST_PAYMENT_PROFILES} from '../../lib/auction/payment.mjs';import {database} from './helpers/database.mjs';
function setup(){const invoice=buildInvoices('a',[{id:'lot',mode:'sandbox',status:'sold',leaderId:'test-a',snapshot:{rugId:'rug',sku:'SKU'},winningDelivery:{method:'pickup_self'},currentCents:10000,title:'Rug',paymentStatus:'unpaid'}],DEFAULT_SETTINGS,1)[0];const profile={buyerId:'test-a',mode:'test',verified:true,customerId:'cus_test',paymentMethodId:'pm_test',setupIntentId:'seti_test',acceptedPolicyVersion:invoice.policy.policyVersion,chargeConsent:true};const db=database({[SANDBOX_INVOICES+'/'+invoice.id]:invoice,[TEST_PAYMENT_PROFILES+'/test-a']:profile});let creates=0,confirms=0;const intent={id:'pi_test',livemode:false,currency:'usd',amount:invoice.total,customer:profile.customerId,metadata:{purpose:'marcopolo_auction_test',invoiceId:invoice.id},status:'requires_confirmation',amount_received:0};const stripe={setupIntents:{retrieve:async()=>({livemode:false,status:'succeeded',customer:profile.customerId,payment_method:profile.paymentMethodId,usage:'off_session'})},paymentMethods:{retrieve:async()=>({customer:profile.customerId})},paymentIntents:{create:async(params,options)=>{creates++;assert.equal(params.amount,10600);assert.ok(options.idempotencyKey.endsWith(invoice.id));return {...intent};},confirm:async(id,params)=>{confirms++;assert.equal(params.off_session,true);intent.status='succeeded';intent.amount_received=invoice.total;return {...intent};},retrieve:async()=>({...intent})}};return {invoice,profile,db,stripe,intent,creates:()=>creates,confirms:()=>confirms};}
test('one test payment per invoice; retry and concurrent attempts cannot double-charge',async()=>{const h=setup();const results=await Promise.allSettled([chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff'),chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff')]);assert.ok(results.some(r=>r.status==='fulfilled'));await chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff');assert.equal(h.creates(),1);assert.equal(h.confirms(),1);assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'paid');});
test('forged provider amount, customer, mode and metadata cannot mark an invoice paid',()=>{const h=setup();for(const changes of [{livemode:true},{amount:10000},{customer:'cus_other'},{metadata:{invoiceId:'other'}},{currency:'eur'}])assert.throws(()=>testIntentState(h.invoice,h.profile,{...h.intent,...changes}));});
test('decline and bank action stay unpaid; reordered events cannot undo confirmed payment',async()=>{const h=setup();await syncTestIntent(h.db,{...h.intent,status:'requires_payment_method',last_payment_error:{decline_code:'insufficient_funds'}});assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'failed');await syncTestIntent(h.db,{...h.intent,status:'requires_action'});assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'requires_action');await syncTestIntent(h.db,{...h.intent,status:'succeeded',amount_received:10600});await syncTestIntent(h.db,{...h.intent,status:'processing'});assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'paid');});
test('unverified card or mismatched consent cannot call Stripe',async()=>{for(const change of [{verified:false},{acceptedPolicyVersion:'wrong'},{chargeConsent:false},{mode:'live'}]){const h=setup();h.db.change(TEST_PAYMENT_PROFILES+'/test-a',change);await assert.rejects(chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff'));assert.equal(h.creates(),0);}});
test('unknown provider result is recorded for review and cannot silently start another payment',async()=>{const h=setup();h.stripe.paymentIntents.create=async()=>{throw Error('Network lost');};await assert.rejects(chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff'));assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'needs_review');await assert.rejects(chargeTestInvoice(h.db,h.stripe,h.invoice.id,'staff'),/already started/);});

import {retryTestInvoice,TEST_PAYMENT_OPERATIONS} from '../../lib/auction/payment.mjs';
test('declined-card retry reuses the same PaymentIntent and blocks concurrent retries',async()=>{
 const h=setup();h.intent.status='requires_payment_method';await syncTestIntent(h.db,h.intent);h.db.change(TEST_PAYMENT_OPERATIONS+'/'+h.invoice.id,{phase:'reconciled',retryAttempts:0});let updates=0;h.stripe.paymentIntents.update=async id=>{updates++;assert.equal(id,'pi_test');return h.intent;};
 const results=await Promise.allSettled([retryTestInvoice(h.db,h.stripe,h.invoice.id,'staff'),retryTestInvoice(h.db,h.stripe,h.invoice.id,'staff')]);assert.ok(results.some(r=>r.status==='fulfilled'));assert.equal(updates,1);assert.equal(h.creates(),0);assert.equal(h.confirms(),1);assert.equal(h.db.read(SANDBOX_INVOICES+'/'+h.invoice.id).paymentStatus,'paid');
});

import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import Stripe from 'stripe';
test('webhook requires valid Stripe signature and ignores live events before database access',async()=>{
 const key='sk_test_mock',secret='whsec_test_mock';let synced=0,dbCalls=0;
 const api={},source=ts.transpileModule(fs.readFileSync('app/api/auction/test-webhook/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
 vm.runInNewContext(source,{exports:api,Error,process:{env:{MARCO_POLO_AUCTION_STRIPE_TEST_ENABLED:'true',STRIPE_AUCTION_TEST_SECRET_KEY:key,STRIPE_AUCTION_TEST_WEBHOOK_SECRET:secret}},require:name=>{if(name==='next/server')return {NextResponse:{json:(body,o)=>({body,status:o?.status||200})}};if(name==='stripe')return {default:Stripe};if(name.includes('firebase-admin'))return {serverDb:()=>{dbCalls++;return {};}};return {syncTestIntent:async()=>{synced++;}};}});
 const payload=JSON.stringify({id:'evt_test',object:'event',livemode:false,type:'payment_intent.succeeded',data:{object:{metadata:{purpose:'marcopolo_auction_test'}}}});
 const signature=Stripe.webhooks.generateTestHeaderString({payload,secret});
 const req=signature=>new Request('https://example.test',{method:'POST',headers:{'stripe-signature':signature},body:payload});
 assert.equal((await api.POST(req('invalid'))).status,400);assert.equal(dbCalls,0);
 assert.equal((await api.POST(req(signature))).status,200);assert.equal(synced,1);
 const live=JSON.stringify({id:'evt_live',object:'event',livemode:true,type:'payment_intent.succeeded',data:{object:{}}});const signed=Stripe.webhooks.generateTestHeaderString({payload:live,secret});assert.equal((await api.POST(new Request('https://example.test',{method:'POST',headers:{'stripe-signature':signed},body:live}))).status,200);assert.equal(dbCalls,1);
});
