import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import crypto from 'node:crypto';import * as catalog from '../../lib/auction/catalog.mjs';import * as engine from '../../lib/auction/engine.mjs';import * as planning from '../../lib/auction/planning.mjs';
function setup(authorized=true){
 const records=new Map();let queue=Promise.resolve();
 const ref=path=>({path,id:path.split('/').at(-1),collection:name=>collection(path+'/'+name)});const collection=path=>({doc:id=>ref(path+'/'+id)});
 const db={doc:ref,collection,runTransaction:fn=>{const work=queue.then(async()=>{const writes=[];await fn({get:async r=>({exists:records.has(r.path),id:r.id,data:()=>records.get(r.path)}),set:(r,v)=>writes.push([r.path,{...records.get(r.path),...v}]),create:(r,v)=>{assert.ok(!records.has(r.path));writes.push([r.path,v]);}});for(const [p,v]of writes)records.set(p,v);});queue=work.catch(()=>{});return work;}};
 const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/auction/planning/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,Error,Date,console,require:name=>name==='next/server'?{NextResponse:{json:(body,init)=>({body,status:init?.status||200})}}:name==='crypto'?crypto:name.includes('staff-permission')?{requireStaff:async()=>{if(!authorized)throw Error('FORBIDDEN');return {uid:'owner'};}}:name.includes('firebase-admin')?{serverDb:()=>db}:name.includes('auction-errors')?{auctionFailure:()=>({status:403})}:name.includes('planning.mjs')?planning:name.includes('catalog.mjs')?catalog:engine});
 const post=body=>exports.POST(new Request('https://example.test',{method:'POST',body:JSON.stringify(body)}));return {records,post};
}
const uuid=()=>crypto.randomUUID();
const rug={name:'Afghan rug',sku:'MP-123',origin:'Afghanistan',dimensions:'8 x 10',material:'Wool',availability:'In Stock',images:['https://example.test/rug.jpg']};
const row={rugId:'rug1',title:rug.name,sku:rug.sku,origin:rug.origin,dimensions:rug.dimensions,material:rug.material,image:rug.images[0],condition:'Minor wear at the fringes.',starting:'50.25',reserve:'100',loading:'0'};
const draft=()=>({action:'save',id:uuid(),requestId:uuid(),version:0,title:'Autumn rug auction',status:'draft',startAt:Date.now()+86400000,endAt:Date.now()+172800000,stagger:30,rows:[row]});
test('bulk save is atomic, retries are idempotent and inventory is unchanged',async()=>{const {records,post}=setup();records.set('showroom_rugs/rug1',rug);const d=draft();assert.equal((await post(d)).status,200);assert.equal((await post(d)).status,200);assert.equal(records.get('auction_workspaces_v1/'+d.id).version,1);assert.deepEqual(records.get('showroom_rugs/rug1'),rug);assert.equal((await post({...d,requestId:uuid()})).status,400);const bad=draft();bad.rows.push({...row,sku:'SECOND',rugId:'missing'});assert.equal((await post(bad)).status,400);assert.equal(records.has('auction_workspaces_v1/'+bad.id),false);});
test('staff permission is checked before any writes',async()=>{const {post,records}=setup(false);assert.equal((await post(draft())).status,403);assert.equal(records.size,0);});
test('readiness blocks incomplete, unlinked, duplicate and unavailable inventory',async()=>{assert.throws(()=>planning.prepareAuction({...draft(),status:'ready',rows:[{...row,condition:''}]}));assert.throws(()=>planning.prepareAuction({...draft(),status:'ready',rows:[{...row,rugId:''}]}));assert.throws(()=>planning.prepareAuction({...draft(),rows:[row,row]}));const {post,records}=setup();records.set('showroom_rugs/rug1',{...rug,availability:'Sold'});assert.equal((await post(draft())).status,400);});
test('test copies use saved reviewed lots and never publish or update inventory',async()=>{const {records,post}=setup();records.set('showroom_rugs/rug1',rug);const d=draft();await post(d);const op={action:'test',id:d.id,version:1,index:0,requestId:uuid()};assert.equal((await post(op)).status,200);assert.equal((await post(op)).status,200);const lot=records.get('auction_sandbox_lots/'+op.requestId);assert.equal(lot.mode,'sandbox');assert.equal(lot.startingCents,5025);assert.equal(lot.status,'draft');assert.deepEqual(records.get('showroom_rugs/rug1'),rug);assert.equal(records.get('auction_workspaces_v1/'+d.id).publicEnabled,false);});
test('money rejects fractions of cents and negative or excessive amounts',()=>{assert.equal(planning.dollars('50.25'),5025);for(const v of ['-1','1.001','Infinity','1000001'])assert.throws(()=>planning.dollars(v));});
test('public catalog remains empty without touching Firebase',async()=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/auction/catalog/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:n=>{assert.equal(n,'next/server');return {NextResponse:{json:body=>body}};}});const d=await exports.GET();assert.equal(d.lots.length,0);assert.equal(d.status,'under_construction');});
